[backend] Device cellular connection
edgehog-device-manager/edgehog pull request #114
Opened 2022-01-25 08:59 UTC by szakhlypa

Fetch CellularConnectionProperties and CellularConnectionStatus data from AppEngine and expose it via GraphQL

Closes #104

2022-02-03 12:13 UTC, davidebriani approved these changes

2022-02-03 17:05 UTC, bettio approved these changes

2022-02-03 17:22 UTC, rbino requested changes

2022-02-03 17:22 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +            end)
If you have to build a map you can use directly `Map.new/2`, and you can use the compact lambda syntax:
```elixir
Map.new(modem_status_list, &{&1.slot, &1})
```

2022-02-03 17:22 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +            %{}
Create a `%ModemProperties` struct with `nil` values here, so you can just update the map below (see next note)
```elixir
%ModemProperties{
  slot: nil,
  apn: nil,
  imei: nil,
  imsi: nil
}
```

2022-02-03 17:22 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +          }
Initialize the connection map from properties, unpack the status in one go and just update the missing fields with the update syntax:
```elixir
connection_map = Map.from_struct(modem_properties)

%{
  carrier: carrier,
  cell_id: cell_id,
  ...
} = modem_status

%{
  connection_map
  | carrier: carrier,
    cell_id: cell_id,
  ...
}

2022-02-04 14:12 UTC, rbino approved these changes

2022-02-04 14:14 UTC, bettio approved these changes

2022-02-04 14:14 UTC, merged