[Frontend] Manual OTA update improvements
edgehog-device-manager/edgehog pull request #128
Opened 2022-02-07 17:30 UTC by Pavinati

- reuse generated relay types
- hide full images URLs in favor of just the image name

2022-02-07 17:59 UTC, davidebriani requested changes

2022-02-07 17:59 UTC, davidebriani commented on frontend/src/components/OperationTable.tsx
> +type TableRecord = OperationTable_otaOperations["otaOperations"][0];
We could just call it `OtaOperation` instead of `TableRecord`

2022-02-07 17:59 UTC, davidebriani commented on frontend/src/components/OperationTable.tsx
> +        value={new Date(value)}
`FormattedDate` will happily accepts the value without pre-parsing it into a `Date`

2022-02-07 17:59 UTC, davidebriani commented on frontend/src/components/OperationTable.tsx
> +  // TODO change this only a solution has been found
change this **once** a solution has been found

2022-02-07 17:59 UTC, davidebriani commented on frontend/src/components/OperationTable.tsx
> +  fragment OperationTable_otaOperations on Device {
This can be fine but we would have to revert it if we added a page with the list of all ota operations, since the fragment would not be on `Device` anymore.
Just adding this note on the general pattern of mixing GraphQL with inner React components

2022-02-07 18:07 UTC, Pavinati commented on frontend/src/components/OperationTable.tsx
> +  fragment OperationTable_otaOperations on Device {
If the fragment comes from a different node, for example the list of all operations, it may have access to additional information, like the target device. In general over generalisation may have other problems. I think it's best to evaluate what to do case by case instead of walking the preemptive optimization path

2022-02-07 18:09 UTC, davidebriani commented on frontend/src/components/OperationTable.tsx
> +type TableRecord = OperationTable_otaOperations["otaOperations"][0];
Alright, let's settle with that

2022-02-08 16:32 UTC, davidebriani approved these changes

2022-02-08 17:53 UTC, bettio approved these changes

2022-02-08 17:54 UTC, bettio approved these changes

2022-02-08 17:54 UTC, merged