Remove authentication on graphiql route and allow token sign in dev env
edgehog-device-manager/edgehog pull request #144
Opened 2022-02-23 15:52 UTC by Pavinati

2022-03-07 10:18 UTC, davidebriani approved these changes

2022-03-08 16:29 UTC, bettio requested changes

2022-03-08 16:29 UTC, bettio commented on backend/lib/edgehog_web/auth/token.ex
> +  # However, we want to be able to generate tokens for testsing purposes or
`testsing`

2022-03-08 16:31 UTC, rbino approved these changes

2022-03-08 17:18 UTC, bettio approved these changes

2022-03-08 17:18 UTC, merged