Update frontend dependencies
edgehog-device-manager/edgehog pull request #147
Opened 2022-02-28 13:21 UTC by Pavinati

npm update

Signed-off-by: Mattia Pavinati <mattia.pavinati@secomind.com>

2022-02-28 13:39 UTC, szakhlypa requested changes

2022-02-28 13:39 UTC, szakhlypa commented on frontend/src/api/__generated__/CellularConnectionTabs_cellularConnection.graphql.ts
> +import { FragmentRefs as  } from "relay-runtime";
We need to use `relay-compiler-language-typescript` [v15.0.0](https://github.com/relay-tools/relay-compiler-language-typescript/releases/tag/v15.0.0) o newer, see also [PR](https://github.com/relay-tools/relay-compiler-language-typescript/pull/519)

2022-02-28 14:23 UTC, Pavinati commented on frontend/src/api/__generated__/CellularConnectionTabs_cellularConnection.graphql.ts
> +import { FragmentRefs as  } from "relay-runtime";
I only updated minors hoping they wouldn't introduce breaking changes.
In the end i took this opportunity to upgrade to relay 13

2022-02-28 17:55 UTC, szakhlypa approved these changes

2022-03-01 09:40 UTC, davidebriani approved these changes

2022-03-01 09:41 UTC, merged