Handle missing interfaces
edgehog-device-manager/edgehog pull request #149
Opened 2022-03-08 14:05 UTC by Pavinati

closes #112

Signed-off-by: Mattia Pavinati <mattia.pavinati@secomind.com>

2022-03-09 14:35 UTC, szakhlypa requested changes

2022-03-09 16:20 UTC, Pavinati commented on backend/lib/edgehog/astarte.ex
> +      %{name: "io.edgehog.devicemanager.CellularConnectionProperties", major: 0, minor: 1}
I confronted with @FrancescoVaiani to have a clearer view on what those interfaces so, and we agreed it doesn't make much sense to have a device that gives you hardware information about its modem but doesn't say whether is connected or no to something. The devices should have both interfaces to support said capability, and if disconnected it won't publish data on the status one.

2022-03-09 16:32 UTC, rbino requested changes

2022-03-09 16:32 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +
Since this function cannot fail by definition and it always returns a list, it's more akin to a `list` function rather than a `fetch` function, so I would call it `list_device_capabilities` and just return a list without the wrapping tuple

2022-03-09 16:32 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +    capabilities
Just
```
[:geolocation | capabilities]
```

2022-03-09 16:32 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +             )
You can do
```elixir
assert :software_updates not in Astarte.get_device_capabilities(partial_introspection_1)
```
it reads more fluently

2022-03-10 15:08 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +      _ -> []
Should this be `[:geolocation]` even without an introspection since it is added unconditionally in `get_device_capabilities`?

2022-03-10 17:33 UTC, Pavinati commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +      _ -> []
my reasoning was: If i'm able to obtain the introspection, i won't get the last seen IP too, hence no geolocalization

2022-03-14 11:30 UTC, rbino approved these changes

2022-03-14 11:52 UTC, szakhlypa approved these changes

2022-03-14 15:13 UTC, bettio approved these changes

2022-03-14 15:16 UTC, merged