Add footer with frontend version
edgehog-device-manager/edgehog pull request #163
Opened 2022-03-14 14:43 UTC by Pavinati

Closes #153 
![2022-03-14_15-43](https://user-images.githubusercontent.com/5071605/158196002-46401b2a-b595-4efc-96fa-120ec474b212.png)

2022-03-14 15:35 UTC, szakhlypa requested changes

2022-03-14 15:35 UTC, szakhlypa commented on frontend/src/components/Footer.scss
> +footer img {
Let's add header with `Copyright` and `SPDX-License-Identifier` for REUSE

2022-03-14 15:35 UTC, szakhlypa commented on frontend/src/App.tsx
> +import { name, version, homepage, repository, bugs } from "../package.json";
`name` is unnecessary here

2022-03-14 15:42 UTC, Pavinati commented on frontend/src/App.tsx
> +import { name, version, homepage, repository, bugs } from "../package.json";
i was pushing the fixes at the same time as i got a notification about this comment :smile:

2022-03-14 15:48 UTC, szakhlypa approved these changes

2022-03-14 15:53 UTC, davidebriani commented on frontend/src/components/Footer.tsx
> +    <footer className="pt-2 pb-1 border-top">
Why distinguish the padding `pt-2 pb-1`? I think a simpler `ph-2` would also look better.

2022-03-14 15:55 UTC, Pavinati commented on frontend/src/components/Footer.tsx
> +    <footer className="pt-2 pb-1 border-top">
it was `py-2` before, but i didn't like it much when i added the top border.
It doesn't make much of a difference though

2022-03-14 15:58 UTC, davidebriani commented on frontend/src/components/Footer.tsx
> +    <footer className="pt-2 pb-1 border-top">
Right, I meant `py-2`. Ok, let's roll like this then

2022-03-14 16:20 UTC, davidebriani approved these changes

2022-03-15 16:25 UTC, bettio approved these changes

2022-03-15 16:25 UTC, merged