[backend] Fix to resolve device capabilities in GraphQL
edgehog-device-manager/edgehog pull request #164
Opened 2022-03-14 16:07 UTC by szakhlypa

Signed-off-by: Sergey Zakhlypa <sergey.zakhlypa@secomind.com>

2022-03-14 16:44 UTC, Pavinati approved these changes

2022-03-15 15:18 UTC, Pavinati approved these changes

2022-03-15 16:32 UTC, rbino requested changes
Let's change this as discussed during the previous meeting

2022-03-16 15:39 UTC, rbino approved these changes

2022-03-16 16:56 UTC, merged