doc: add documentation on OTA Updates, Tags, Attributes and Groups
edgehog-device-manager/edgehog pull request #187
Opened 2022-03-24 18:25 UTC by rbino

Document the (future) supported features of Edgehog's OTA mechanism, including
Groups, Tag and Attribute functionalities

Signed-off-by: Riccardo Binetti <riccardo.binetti@secomind.com>

2022-03-29 09:52 UTC, bettio requested changes

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/core_concepts.md
> +Collection for, e.g., e-bikes from each specific country to handle the different speed limitations.
Let's keep 1 system model = 1 base image collection ATM

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/core_concepts.md
> +A distribution channel identifies the set of Base Images that some specific Devices will receive.
I would love to call it "a software subscription" maybe. A device subscribes for software updates for its system model using a distribution channel or something like it.

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/core_concepts.md
> +## OTA Campaign
I would rather say maybe an Update Campaign

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/core_concepts.md
> +Each Distribution Channel can have only one live campaign at a time, so creating a new campaign
for a given system model.  Different system models can have campaigns in parallel.

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/ota_updates.md
> +Model and their
and their what?

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/ota_updates.md
> +- Description (optional): a localized description of the content of the Base Image.
as a reminder, I think we are moving away from fingerprint for image identification towards an unique constraint on version.

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/ota_updates.md
> +  currently using a later version of the Base Image. Defaults to `false`.
I'm not sure if "allow downgrade" and supported starting version" should be a property of the roll-out or of the base image itself.

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/ota_updates.md
> +##### `remote` (Push-based)
maybe we should directly call it "push"

2022-03-29 09:52 UTC, bettio commented on doc/pages/user/ota_updates.md
> +available. The update is pushed to the device only after the user accepts the update. The update is
The update is downloaded to the device only after the user accepts the update.

2022-03-30 08:37 UTC, harlem88 commented on doc/pages/user/core_concepts.md
> +Each Device is always associated with a specific Distribution Channel (e.g. `default`, `stable`,
Who decides that device was associated with a specific distribution Channel? Is it possible to choose it from device side? Server side? Or both of them?

2022-03-30 14:13 UTC, bettio commented
"Distribution Channel" or "Update Channel"?

2022-04-05 05:45 UTC, rbino commented on doc/pages/user/ota_updates.md
> +  currently using a later version of the Base Image. Defaults to `false`.
my 2 cents (and what I've done in this new round): "Supported starting version" is a property of the Base Image, "Allow downgrade" is a property of the Rollout

2022-04-05 05:46 UTC, rbino commented on doc/pages/user/core_concepts.md
> +A distribution channel identifies the set of Base Images that some specific Devices will receive.
I've used "Update Channel" as discussed in person

2022-04-05 05:49 UTC, rbino commented on doc/pages/user/core_concepts.md
> +A distribution channel identifies the set of Base Images that some specific Devices will receive.
Also clarified the description as indicated

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/core_concepts.md
> +Tags are string values that can be freely attached to Devices. There are no predefined semantics so
There ~~are~~**is** no predefined semantics

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/core_concepts.md
> +Some examples of tags which can be assigned to the e-bikes or electric scooters in our examples
examples of tags ~~which~~**that** can be assigned

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/core_concepts.md
> +(TODO: maybe we want to support other type of values? Casting everything to string reduces a lot
support other type**s** of values

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/core_concepts.md
> +depending on the usecase, but it usually contains the operating system image or the device firmware.
`usecase` -> `use case`

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/core_concepts.md
> +Basically the job of a Base Image Collection is to limit what can be installled to a System Model,
`installled` -> `installed`

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/groups.md
> +jAll the concepts used below are detailed in the [Core
`jAll` -> `All`

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/ota_updates.md
> +higher priority.
`the higher` -> `the highest` or `higher`

2022-04-05 11:23 UTC, davidebriani commented on doc/pages/user/ota_updates.md
> +  automatically get asssigned to this Update Channel
`asssigned` -> `assigned`

2022-04-12 15:21 UTC, rbino commented on doc/pages/user/core_concepts.md
> +(TODO: maybe we want to support other type of values? Casting everything to string reduces a lot
After some internal discussion, we're going to support all Astarte types for the attribute values (i.e. they're not going to be limited to strings). The keys type on the other hand will always be string.

2022-04-12 15:26 UTC, rbino commented on doc/pages/user/core_concepts.md
> +  (TODO: we need a concept to decide _which_ values to track, e.g. "watch").
See above. Add details about Attribute Value Source

2022-04-12 15:38 UTC, rbino commented on doc/pages/user/core_concepts.md
> +
```
### Attribute Value Source

An Attribute Value Source attaches attributes to a Device according to some rule.

Currently, the only supported type of Attribute Value Source is `astarte-value`, which updates Device attributes using a value from an Astarte interface.

2022-04-12 15:53 UTC, rbino commented on doc/pages/user/groups.md
> +TODO
```
To populate an attribute using a value coming from an Astarte interface, an Attribute Value Source must be added. This will create an attribute whose value will be eventually consistent with the value of the target Astarte interface and path.

When creating the Attribute Value Source, the following information must be provided:

- Type: the type of Attribute Value Source. Right now only `astarte-value` is supported, and the following keys are valid for the `astarte-value` type
- Interface: the target interface to be used
- Major version: the target major version of the interface
- Path: the target path containing the value that will be used as attribute value

During its creation, the Attribute Value Source will install an Astarte trigger, so when the target interface value changes, the change will be (eventually) reflected in the Attribute value. The Attribute key will be `astarte-value:<interface-name><path>`. The value will be also initialized asynchronously for all devices by querying AppEngine API in a background task.
```

2022-04-12 15:55 UTC, rbino commented on doc/pages/user/core_concepts.md
> +  periodically?).
Attributes will be eventually consistent, and in a first implementation they could be implemented by lazily updating them whenever a Device status is requested and by querying them just before starting an Update Campaign.

2022-04-12 16:15 UTC, rbino commented on doc/pages/user/core_concepts.md
> +specific group. When there's a conflict, manual associations always have the higher priority.
After some internal discussion:
- There can be _no_ manual assignment to an Update Channel. To be assigned to an Update Channel, a Device _must_ pass through a Group
- Similarly, there is _no_ manual assignment to a Group, the Group membership _must_ pass through a Selector

So, to "forcefully" assign, e.g., the `beta` Update Channel to a Device, users must create a `forced-beta` Group with a `"forced-beta" in tags` Selector and then add a `"forced-beta"` tag to the Device.

This streamlines the Update Channel assignment by making sure there is a single way to assign it (and avoiding possible corner-cases).

2022-04-12 16:17 UTC, rbino commented on doc/pages/user/core_concepts.md
> +  attribute is _not_ equal to `value`
Since we now support different types, add some more operators (e.g. `>`, `<`, `>=`, `<=`, `~=` (regexp) e `in`

2022-04-12 16:19 UTC, rbino commented on doc/pages/user/core_concepts.md
> +  `city` instead of `attributes["edgehog-synthetic:city"]`)
Let's be explicit for now, syntactic sugar can be added later

2022-04-12 16:30 UTC, rbino commented on doc/pages/user/ota_updates.md
> +- (TODO: Mainteinance Window?)
Move the Maintenance Window at the Device level. To aid batch processing (since manually setting it to all devices can be tedious) we will support setting a Maintenance Window with a batch one-shot operation using a Group to choose the targets.
Not that the Maintenance Window is _not_ a property of the Group but will remain a property of the single Device.

2022-04-20 14:24 UTC, harlem88 requested changes

2022-04-20 14:24 UTC, harlem88 commented on doc/pages/user/core_concepts.md
> +  Note that nomeric comparison operators are valid only when used with an attribute with a numeric
`nomeric` -> `numeric`

2022-04-20 14:45 UTC, harlem88 requested changes

2022-04-20 14:45 UTC, harlem88 commented on doc/pages/user/devices.md
> +Channel](core_concepts.html#update-channel). Usually this is used to manually override
core_concepts.md#update-channel**s**

2022-04-20 14:58 UTC, rbino commented on doc/pages/user/groups.md
> +- Handle: an handle matching the `^[a-z][a-z\d\-]*$` regular expression.
We're actually going to support the original regex since there's (currently) no technical reason to restrict users about the handle format

2022-04-23 09:21 UTC, FrancescoVaiani approved these changes

2022-04-26 11:09 UTC, szakhlypa approved these changes

2022-06-21 09:18 UTC, davidebriani approved these changes

2022-06-21 09:20 UTC, bettio approved these changes

2022-06-21 09:43 UTC, Pavinati approved these changes

2022-06-21 09:54 UTC, merged