[Backend] Migrate from freegeoip.app APIs to ipbase.com APIs for geolocation
edgehog-device-manager/edgehog pull request #190
Opened 2022-05-13 13:17 UTC by davidebriani

The geolocation service offered at [freegeoip.app](https://freegeoip.app/) has been deprecated in favor of an updated service exposed at [ipbase.com](https://ipbase.com).

The MR reflects this change by renaming references of freegeoip.app to ipbase.com and by making sure that the new APIs are used when geolocating devices.

2022-05-13 15:20 UTC, szakhlypa requested changes

2022-05-13 15:20 UTC, szakhlypa commented on backend/test/edgehog/geolocation/providers/ipbase_test.exs
> +      assert {:ok, position} = IPBase.geolocate(device)
We also need to update mock response above to
```
response = %{
  "data" => %{
    "location" => %{
      "latitude" => 45.4019498,
      "longitude" => 11.8706081
    }
  }
}
```

2022-05-13 15:34 UTC, szakhlypa approved these changes

2022-05-26 14:34 UTC, bettio approved these changes

2022-05-26 14:35 UTC, merged