Add support for device tags
edgehog-device-manager/edgehog pull request #191
Opened 2022-05-18 07:04 UTC by rbino

Allow tagging a device, showing its tags when querying it and filtering for a specific tag when requesting the device list.

2022-05-19 11:45 UTC, davidebriani requested changes

2022-05-19 11:45 UTC, davidebriani commented on backend/priv/repo/migrations/20220517063737_create_devices_tags.exs
> +          references(:tags, with: [tenant_id: :tenant_id], match: :full, on_delete: :nothing),
I think we can use `on_delete: :delete_all`. It doesn't make sense to keep the Tag -> Device association when the referenced tag doesn't exist.
Or, if you want to use custom logic when deleting a used tag, we can use `on_delete: :restrict`

2022-05-19 11:45 UTC, davidebriani commented on backend/lib/edgehog/devices/device_tag.ex
> +    field :tenant_id, :integer, autogenerate: {Edgehog.Repo, :get_tenant_id, []}
Shouldn't `:tenant_id` be an `:id` instead of `:integer`?

2022-05-19 11:45 UTC, davidebriani commented on backend/lib/edgehog/astarte.ex
> +      %{tags: nil} ->
Naming each Multi step with something that matches the performed action would make the logic easier to follow.

For instance, the step that updates the device could be named `:update_device`, so we can maintain a uniform naming between `update_device/1`, `update_device_multi/2` and the `:update_device`  step that would contain the end result of the Multi.
With such convention, I could already expect `ensure_tags_multi()` to contain a step `:ensure_tags` with the end result for that Multi.

2022-05-19 11:45 UTC, davidebriani commented on backend/lib/edgehog/devices.ex
> +  def ensure_tags_multi(multi, %{tags: _tags} = attrs) do
`ensure_tags_multi` does not convey a clear meaning for this function, we could use something like `upsert_tags_multi`.

2022-05-19 11:45 UTC, davidebriani commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +      resolve &Resolvers.Devices.extract_device_tags/3
What about just supporting the serialization of Tags to string instead of manually using `extract_device_tags/3`:

```elixir
defimpl String.Chars, for: Edgehog.Devices.Tag do
  def to_string(%Edgehog.Devices.Tag{name: name}), do: name
end
```
This way you won't need to replicate the serialization should you wish to expose tags on some other queries.

2022-05-23 06:30 UTC, rbino commented on backend/lib/edgehog/devices/device_tag.ex
> +    field :tenant_id, :integer, autogenerate: {Edgehog.Repo, :get_tenant_id, []}
Explicit `autogenerate` tuples do not work with `id` fields, so this has to be an `integer`.
This is the new status quo to populate the `tenant_id` (I want to gradually introduce it everywhere (it's already used in `OtaOperation`), because it has the advantage of allowing application code to override the `tenant_id` if there's the need (e.g. in tests) by passing a struct with the `tenant_id` already populated while still automatically populating it with the saved `tenant_id` in the average case

2022-05-23 06:31 UTC, rbino commented on backend/lib/edgehog/devices/device_tag.ex
> +    |> validate_required([])
No, in fact we might as well remove the whole changeset since this is just used as a support schema for associations and we never create it explicitly.

2022-05-23 06:34 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +      %{tags: nil} ->
I checked and it seems there's no established convention for naming multi steps, what you proposed makes total sense, changed the code to reflect it

2022-05-23 06:37 UTC, rbino commented on backend/lib/edgehog/devices.ex
> +  def ensure_tags_multi(multi, %{tags: _tags} = attrs) do
Actually I think that `ensure` is better than `upsert` here: there's actually no update happening, what this steps are doing is that if tags are not there, they insert them. It's akin to what `ensure_device_exists` is doing in some other part of the codebase, hence the similar name.
If you have another verb that conveys the same meaning I'm open to suggestions.

2022-05-23 07:11 UTC, davidebriani commented on backend/lib/edgehog/astarte.ex
> +      %{tags: nil} ->
Another reason for adopting a naming convention would be that you cannot have steps with the same name in a Multi. So following a convention with specific names for specific actions can save you from conflicts when merging Multis

2022-05-23 07:14 UTC, davidebriani commented on backend/lib/edgehog/devices.ex
> +  def ensure_tags_multi(multi, %{tags: _tags} = attrs) do
You're right. Indeed the meaning is clear if you use the verb too, i.e. `ensure_tags_exist_multi`

2022-05-26 07:34 UTC, rbino commented on backend/lib/edgehog/devices/tag.ex
> +    |> unique_constraint(:name)
Correct

2022-05-26 07:40 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +      resolve &Resolvers.Devices.extract_device_tags/3
Explicit is better than implicit, the explicit resolver is still reusable with other queries and it doesn't force the same Tag string representation application-wide

2022-05-26 07:46 UTC, rbino commented on backend/priv/repo/migrations/20220517063737_create_devices_tags.exs
> +          references(:tags, with: [tenant_id: :tenant_id], match: :full, on_delete: :nothing),
I'll use `:restrict`. Tags in the `tags` table are basically thought to be append-only (i.e. only the association is deleted if the tag is deleted), so I'd rather disallow them from being deleted than cascade (since they should normally not be deleted anyway).

2022-05-26 07:51 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +
Fixed adding `on_replace: :delete` to the association, I also added your new tests to the suite

2022-05-26 08:48 UTC, davidebriani commented on backend/lib/edgehog/devices/tag.ex
> +    field :tenant_id, :id
Could we use :autogenerate here too?
```elixir
field :tenant_id, :integer, autogenerate: {Edgehog.Repo, :get_tenant_id, []}
```

2022-05-26 09:14 UTC, rbino commented on backend/lib/edgehog/devices/tag.ex
> +    field :tenant_id, :id
I'll add it for consistency, but currently tags are inserted using `Repo.insert_all` which doesn't populate `autogenerate` fields, so we still have to populate it manually in `ensure_tags_exist_multi`

2022-05-26 10:21 UTC, szakhlypa requested changes

2022-05-26 10:21 UTC, szakhlypa commented on backend/test/edgehog/astarte_test.exs
> +      assert ["new"] == Enum.map(device.tags, & &1.name)
Should we also check that unused tags were deleted?
It seems they are not.
`assert length(Repo.all(Edgehog.Devices.Tag)) == 1` fails with 3 != 1

2022-05-26 14:23 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +      assert ["new"] == Enum.map(device.tags, & &1.name)
Unused tags shouldn't get deleted - only their association. Basically the `tags` table is append-only. This is how it's usually done in all examples I've found.

2022-05-27 07:48 UTC, davidebriani approved these changes

2022-05-27 08:26 UTC, szakhlypa commented on backend/lib/edgehog/astarte.ex
> +            where: ilike(t.name, ^"%#{tag}%"),
Just for my understanding, does [`prepare_query`](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/repo.ex#L39) works for subquery too?
Or should we also filter Devices.Tag with `tenant_id` in subquery?

2022-05-27 08:31 UTC, szakhlypa approved these changes

2022-05-27 09:45 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +            where: ilike(t.name, ^"%#{tag}%"),
Good catch, I checked the generated query and indeed `prepare_query` was not executed for the subquery, fixed this by explicitly matching `tenant_id` in the subquery.

2022-05-27 14:42 UTC, szakhlypa approved these changes

2022-05-30 10:32 UTC, davidebriani approved these changes

2022-05-30 11:15 UTC, bettio requested changes
Let's add something to the changelog

2022-06-08 13:56 UTC, merged