Fix queries and mutations for translated descriptions
edgehog-device-manager/edgehog pull request #201
Opened 2022-06-06 11:33 UTC by davidebriani

Currently, saving translated descriptions for System Models doesn't work when the browser displaying the Edgehog's frontend has a preferred locale that differs from the default one configured for the tenant. Indeed, browsers can query descriptions for a custom locale, but they can only save descriptions in the tenant's default locale.

Sample steps to reproduce the issue:
1. The browser queries a System Model asking for its translated description with, an `it-IT` locale.
2. The backend returns the System Model without a description because there is none.
3. The browser tries to update the System Model with a description in the tenant's default locale: `en-US`.
4. The subsequent query to get the updated System Model still asks for a description in `it-IT`, the preferred locale for the browser, so the backend still returns no description. Although it is persisted, the previously inserted description seems to have disappeared from the user's point of view.

The change proposed here fixes the odd behavior in the backend by:
- Preloading both the default locale of the tenant and the locale specified by the user, if any.
- Extracting the best match of translated descriptions according to locale preferences when rendering System Models in the GraphQL layer.
This way, the user is always presented with a translated description for one of the locales, if it exists at least for the tenant's default locale.

Then another fix is added to support removing previously entered descriptions:
1. Allow the frontend to pass blank descriptions.
2. Make sure the backend discards and remove empty descriptions.

With these changes in place, users can now correctly see and manage descriptions at least in the tenant's locale until a full i18n support is implemented.

2022-06-06 12:42 UTC, Pavinati commented on CHANGELOG.md
> +- Correctly handle queries and mutations on translated descriptions.
`Correctly` doesn't explain how it changed.
I'd rather write something like: "Return the text in the default tenant language when the selected language is not available or no translation was inserted"

2022-06-06 12:45 UTC, Pavinati commented on CHANGELOG.md
> +## [0.5.2] - Unreleased
Should this be under the 0.6.0 tag?
Regardless, we usually make a dedicated commit for the new release preparation (whether it is 0.5.2 or 0.6.0) and then add the changelog row directly in the commit that introduces it.

2022-06-06 12:47 UTC, Pavinati commented on backend/lib/edgehog/devices/system_model_description.ex
> +  def localized(locales) when is_list(locales) do
changing this function forces you to edit all the existing code that uses a single locale.
I would add a new function with a different name or use the same name but differentiate using guards

2022-06-06 12:51 UTC, Pavinati commented on backend/test/edgehog_web/schema/query/system_models_test.exs
> -    test "returns empty description for non existing locale", %{
I would still keep a test for nonexisting descriptions. In that instance we should still return null

2022-06-06 12:56 UTC, Pavinati commented on backend/lib/edgehog_web/resolvers/devices.ex
> +        |> localize_system_model_description(context)
same as above

2022-06-06 16:38 UTC, rbino requested changes

2022-06-06 16:38 UTC, rbino commented on backend/lib/edgehog_web/context.ex
> +  end
This is a `Plug`, and as such it usually doesn't expose additional functions. This should probably be moved in the resolver.
Moreover on the implementation: the `:default_locale` is non-null at the database level (and it also has a default), so you can be sure it's present. So instead of building the list and rejecting you could just
```elixir
%{default_locale: default_locale} = tenant
case Map.fetch(context, :locale) do
  {:ok, locale} ->
    [locale, default_locale]
  :error ->
    [default_locale]
end
```

2022-06-06 16:38 UTC, rbino commented on backend/lib/edgehog_web/resolvers/devices.ex
> +  def extract_localized_description(%SystemModel{descriptions: nil}, _args, _resolution) do
`descriptions` would probably be an empty list instead of `nil` since it's populated with `Repo.all`

2022-06-06 16:50 UTC, davidebriani commented on backend/lib/edgehog/devices/system_model_description.ex
> +  def localized(locales) when is_list(locales) do
I'd avoid having the same function with different signatures. Also, it makes sense to use the same function throughout the code and in the tests, where previously you had to call it twice since it didn't support preloading two locales at the same time.

2022-06-06 16:52 UTC, davidebriani commented on frontend/src/forms/UpdateSystemModel.tsx
> +    },
I updated this piece so that a `null` value is passed to the backend when the description is erased, i.e. in the case of `description` == `""`.
Note that only the fields that have changed are sent to the backend in the update mutation by the upper layer, the SystemModel page.

2022-06-08 08:54 UTC, Pavinati approved these changes

2022-06-15 09:41 UTC, rbino requested changes

2022-06-15 09:41 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +    descriptions_query = Devices.localized_system_model_description_query(preferred_locales)
Use pipes since you're just passing the intermediate result to the next function
```elixir
descriptions_query =
  context
  |> preferred_locales()
  |> Devices.localized_system_model_description_query()
```

2022-06-15 09:41 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +  defp list_preferred_locales(%{current_tenant: tenant} = context) do
Actually now that I think about it: you're actually copy-pasting this function in a couple of resolvers, and this made me realize it probably belongs to the `EdgehogWeb.Context` plug instead. You have both the tenant and the explicit locale there, just populate a `:preferred_locales` key in the context there and access it in the resolvers (check if `:locale` is still used at that point, if it's not you can remove it from the context).

Moreover this also unlocks another interesting feature: the `accept-language` header can actually contain a list of accepted languages, but we were [just using the first one](https://github.com/edgehog-device-manager/edgehog/blob/b1193c26f403132dead6964c1c052e5dcae533af/backend/lib/edgehog_web/context.ex#L51). If you populate `:preferred_locales` there you can put all the languages in the `accept-language` first and at the end add the default tenant locale.

2022-06-15 09:41 UTC, rbino commented on backend/lib/edgehog_web/resolvers/devices.ex
> +      |> Enum.flat_map(fn locale -> Enum.filter(descriptions, &(&1.locale == locale)) end)
There should be no need to filter for preferred locales here since the DB query should already have taken care of that, what you should do instead is find a way to sort descriptions with the same order as the locales preference and extract the first one

2022-06-15 16:55 UTC, davidebriani commented on backend/lib/edgehog_web/resolvers/devices.ex
> +      |> Enum.flat_map(fn locale -> Enum.filter(descriptions, &(&1.locale == locale)) end)
You're right. However here I'm already ordering by preferred locales since I'm looping on them, and I'm using `Enum.filter` just because it works well with `Enum.flat_map` and lets you discard void results of descriptions for a certain locale.
A different approach would be to directly take the descriptions and sort them, e.g.:
```elixir
description =
      descriptions
      |> Enum.sort_by(&Enum.find_index(preferred_locales, &1.locale))
      |> List.first()
```
I have no preference here, you tell me.

2022-06-16 10:45 UTC, rbino requested changes

2022-06-16 10:45 UTC, rbino commented on backend/lib/edgehog_web/context.ex
> +    default_locale = get_current_tenant(conn).default_locale
You're already querying the tenant in `build_context`, query it once and pass it as an argument to `get_preferred_locales` too

2022-06-16 10:45 UTC, rbino commented on backend/lib/edgehog_web/context.ex
> +      _ -> nil
This gets run on a _single_ `accept-language` header, but an header can contain multiple languages. If you want to add them all you should probably do
```elixir
    |> Plug.Conn.get_req_header("accept-language")
    |> Enum.flat_map(&get_locale/1)
    |> Enum.concat([default_locale])
```

and

```elixir
defp get_locale(string) when is_binary(string) do
  case Regex.run(~r/[a-z]{2,3}-[A-Z]{2}/, string) do
    matches when is_list(matches) -> matches
    nil -> []
  end
end
```

Your code would currently not return any language (besides the default locale) if there's more than one language in `accept-language`

2022-06-16 10:45 UTC, rbino commented on backend/lib/edgehog_web/resolvers/devices.ex
> +      |> Enum.flat_map(fn locale -> Enum.filter(descriptions, &(&1.locale == locale)) end)
Imho the second approach is clearer in its intent. Both approaches are not ideal since they possibly scan the other list entirely for each element of the original list though, but we can optimize in a second pass, maybe leave a TODO at least.

2022-06-17 10:52 UTC, rbino requested changes

2022-06-17 10:52 UTC, rbino commented on backend/lib/edgehog_web/context.ex
> +    |> Enum.reject(&is_nil/1)
You replaced `Regex.run` with `Regex.scan`, which returns an empty list with no matches, so this is not needed anymore.

2022-06-17 14:13 UTC, rbino approved these changes

2022-06-17 14:15 UTC, merged