endpoint: increase upload size
edgehog-device-manager/edgehog pull request #208
Opened 2022-06-16 13:42 UTC by rbino

Allow uploading files with dimensions up to 500MB

Signed-off-by: Riccardo Binetti <riccardo.binetti@secomind.com>

2022-06-16 16:19 UTC, bettio requested changes

2022-06-16 16:19 UTC, bettio commented on backend/lib/edgehog_web/endpoint.ex
> +    parsers: [:urlencoded, {:multipart, length: 500_000_000}, :json],
This should be a configuration parameter, and we should start I think with 1GB/2GB or maybe 4GB.

2022-06-17 06:49 UTC, rbino commented on backend/lib/edgehog_web/endpoint.ex
> +    parsers: [:urlencoded, {:multipart, length: 500_000_000}, :json],
I'm not sure if this is actually configurable at runtime - Plug initialization happens (or actually can happen) at compile time

2022-06-17 06:52 UTC, rbino commented on backend/lib/edgehog_web/endpoint.ex
> +    parsers: [:urlencoded, {:multipart, length: 500_000_000}, :json],
Ok the library provides the support for [dynamic configuration](https://hexdocs.pm/plug/Plug.Parsers.MULTIPART.html#module-dynamic-configuration), so that's feasible.

2022-06-17 08:53 UTC, bettio approved these changes

2022-06-17 08:53 UTC, merged