[frontend] Add Device Groups
edgehog-device-manager/edgehog pull request #217
Opened 2022-08-10 12:06 UTC by szakhlypa

Add forms and logic to create, update and delete Groups.
Update Device page with Groups info

https://user-images.githubusercontent.com/26611935/183896360-3a3c3751-5857-41bc-8bb0-b2df0370303f.mp4

https://user-images.githubusercontent.com/26611935/183896411-9d1db40c-02cd-4f92-b1c7-34d4a38cf0f4.mp4

https://user-images.githubusercontent.com/26611935/183896525-49c90889-5ea2-45cc-81e0-6edbbf761e0c.mp4

Tag update also updates Groups

https://user-images.githubusercontent.com/26611935/183896554-20c9ec9d-6b91-43e4-96b4-e43a1aca141b.mp4

2022-08-16 09:41 UTC, Pavinati requested changes

2022-08-16 09:41 UTC, Pavinati commented on frontend/src/pages/Device.tsx
> +                    <span>
i would use a `<Stack gap={2}>` instead of the combination of `span` + `className="me-2"` on each element

2022-08-16 09:41 UTC, Pavinati commented on frontend/src/pages/DeviceGroup.tsx
> +            device.invalidateRecord();
Here we're invalidating the whole `Device`. It's a good first implementation, but i would leave a TODO to remind us that this can be later optimized to just remove the deleted group from the device group list

2022-08-16 09:41 UTC, Pavinati commented on frontend/src/pages/DeviceGroup.tsx
> +          store.invalidateStore();
instead of invalidating the whole storage, we could invalidate all the devices and the single updated group.
Invalidating the whole storage invalidates other unrelated things like models

2022-08-16 09:41 UTC, Pavinati commented on frontend/src/pages/DeviceGroupCreate.tsx
> +            });
If we know the list of affected device, we could just add the group in their store record (if it exists).
This is a good first implementation but i would leave a TODO here

2022-08-17 09:36 UTC, davidebriani requested changes

2022-08-17 09:36 UTC, davidebriani commented on frontend/src/components/DeviceGroupsTable.tsx
> +export default DevicesTable;
export default ~~DevicesTable~~ DeviceGroupsTable

2022-08-25 08:11 UTC, Pavinati approved these changes

2022-08-25 16:03 UTC, davidebriani approved these changes

2022-08-31 14:14 UTC, rbino approved these changes

2022-09-02 10:55 UTC, bettio approved these changes

2022-09-02 10:55 UTC, merged