Use new Dockerfile template, with images from hex.pm
edgehog-device-manager/edgehog pull request #223
Opened 2022-10-20 16:50 UTC by bettio

This template is based on the Dockerfile that nowadays is generated with mix phx.gen.release, and make use of tagged images with well known versions, rather a rolling tag.
Elixir and OTP version are explicitly set, and should be manually updated.

Signed-off-by: Davide Bettio <davide.bettio@secomind.com>

2023-01-19 10:21 UTC, davidebriani requested changes

2023-01-19 10:21 UTC, davidebriani commented on backend/Dockerfile
> +CMD ["/app/bin/server"]
I guess this command is doomed to fail because the `server` executable is not present.
The Phoenix generator should also provide the additional files that should be included, such as `rel/overlays/bin/server`.

2023-07-13 10:19 UTC, rbino approved these changes

2023-07-13 10:55 UTC, szakhlypa approved these changes

2023-07-13 10:57 UTC, merged