[backend] Add Base Image Collections
edgehog-device-manager/edgehog pull request #229
Opened 2022-12-05 12:03 UTC by rbino

This PR adds a CRUD for Base Image Collections, which is the starting point to support Base Images and OTA Campaigns.

2022-12-05 13:29 UTC, szakhlypa commented
You may also update `seeds.exs` to create a new `base_image_collection`.

2022-12-20 15:43 UTC, davidebriani requested changes

2022-12-20 15:43 UTC, davidebriani commented on backend/test/edgehog/base_images_test.exs
> +    test "create_base_image_collection/1 with valid data creates a base_image_collection", %{
You should update the signature from `create_base_image_collection/1` to `create_base_image_collection/2`.

2022-12-20 15:43 UTC, davidebriani commented on backend/lib/edgehog/base_images.ex
> +    %BaseImageCollection{system_model_id: system_model.id}
You should update the documentation example above to respect the updated signature, requiring a system model as the first argument.

2022-12-20 15:43 UTC, davidebriani commented on backend/lib/edgehog_web/schema/base_images_types.ex
> +    field :handle, non_null(:string)
The identifier of the ~~system model~~ **base image collection**

2022-12-20 17:46 UTC, davidebriani approved these changes

2022-12-21 09:53 UTC, szakhlypa commented on backend/test/edgehog/base_images_test.exs
> +      {:ok, hardware_type: hardware_type, system_model: system_model_fixture(hardware_type)}
There is no usage of `hardware_type` in tests, so we may not add it to the metadata.

2022-12-21 09:53 UTC, szakhlypa commented on backend/test/edgehog_web/schema/mutation/create_base_image_collection_test.exs
> +      {:ok, hardware_type: hardware_type, system_model: system_model_fixture(hardware_type)}
There is no usage of hardware_type in tests, so we may not add it to the metadata.

2022-12-21 16:16 UTC, szakhlypa approved these changes

2023-01-10 09:22 UTC, szakhlypa approved these changes

2023-01-10 10:25 UTC, merged