[frontend] Add Base Image Collections
edgehog-device-manager/edgehog pull request #230
Opened 2022-12-06 08:59 UTC by szakhlypa

Based on #229 

Adds forms and logic to create, update and delete Base Image Collections.

System model is required to create a new Base Image Collection.
![bic_no_system_model](https://user-images.githubusercontent.com/26611935/205865326-ea17f3dd-e693-4c74-b709-b657f537b29a.png)

Create, filter and delete Base Image Collection

https://user-images.githubusercontent.com/26611935/205865917-dc9df75f-8e38-48c7-a165-775c0346650c.mp4

Update Base Image Collection

https://user-images.githubusercontent.com/26611935/205866068-11460ac3-75bf-43c8-a30b-45f916a5c28e.mp4

2023-01-13 09:57 UTC, Pavinati requested changes

2023-01-13 09:57 UTC, Pavinati commented on frontend/src/pages/BaseImageCollections.tsx
> +  Copyright 2022 SECO Mind Srl
2023

2023-01-13 09:57 UTC, Pavinati commented on frontend/src/forms/UpdateBaseImageCollection.tsx
> +  Copyright 2022 SECO Mind Srl
2023

2023-01-13 09:57 UTC, Pavinati commented on frontend/src/pages/BaseImageCollection.tsx
> +  Copyright 2022 SECO Mind Srl
2023

2023-01-18 09:57 UTC, Pavinati approved these changes

2023-01-18 10:17 UTC, davidebriani requested changes

2023-01-18 10:17 UTC, davidebriani commented on frontend/src/forms/CreateBaseImageCollection.tsx
> +          id="base-image-collection-form-name"
I'd say that these IDs should be prefixed with *create*: `id="create-base-image-collection-form-name"`

2023-01-19 09:18 UTC, merged