[frontend] i18n SystemModel description
edgehog-device-manager/edgehog pull request #238
Opened 2023-01-13 16:52 UTC by szakhlypa

2023-01-20 10:15 UTC, davidebriani requested changes

2023-01-20 10:15 UTC, davidebriani commented on frontend/src/pages/SystemModel.tsx
> +                systemModelChanges.description?.text || systemModel.description,
It looks like this won't let you see the updated description when it's an empty text `""`.
You could use the following instead:
```
description: systemModelChanges.description ? systemModelChanges.description.text : systemModel.description
```

2023-01-20 10:18 UTC, Pavinati commented on frontend/src/pages/SystemModel.tsx
> +                systemModelChanges.description?.text || systemModel.description,
or we could start using the `??` operator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2023-01-23 09:45 UTC, davidebriani approved these changes

2023-01-23 10:50 UTC, davidebriani approved these changes

2023-01-25 16:36 UTC, Pavinati approved these changes

2023-01-25 17:02 UTC, rbino approved these changes

2023-01-25 17:02 UTC, merged