Use i18n_helpers to provide i18n
edgehog-device-manager/edgehog pull request #239
Opened 2023-01-16 17:12 UTC by rbino

This currently only involves System Model descriptions. This PR migrates the data from the system_model_descriptions table to an embedded map in the system_model table and fixes the code and tests accordingly.

Signed-off-by: Riccardo Binetti <riccardo.binetti@secomind.com>

2023-01-17 11:02 UTC, Pavinati requested changes
Remember to update the license headers and external license files with 2023

2023-01-17 11:02 UTC, Pavinati commented on backend/priv/repo/migrations/20230111171104_embed_system_model_descriptions.exs
> +    drop table("system_model_descriptions")
Are system_model_descriptions indexes dropped automatically?

2023-01-17 11:36 UTC, davidebriani approved these changes

2023-01-17 16:08 UTC, szakhlypa commented on backend/test/edgehog_web/schema/query/system_model_test.exs
> +        |> put_req_header("accept-language", "fr-FR;q=0.9 it-IT;q=0.5")
I think it should be comma here `fr-FR;q=0.9,it-IT;q=0.5`

2023-01-18 11:15 UTC, rbino commented on backend/priv/repo/migrations/20230111171104_embed_system_model_descriptions.exs
> +    drop table("system_model_descriptions")
[Yes](https://www.postgresql.org/docs/current/sql-droptable.html)

2023-01-18 11:31 UTC, Pavinati approved these changes

2023-01-18 11:59 UTC, szakhlypa approved these changes

2023-01-19 09:58 UTC, merged