Add Base Images
edgehog-device-manager/edgehog pull request #240
Opened 2023-01-18 17:27 UTC by rbino

Allow uploading a Base Image to a Base Image Collection and doing all CRUD operations on it

2023-01-23 11:15 UTC, davidebriani requested changes

2023-01-23 11:15 UTC, davidebriani commented on backend/test/support/mocks/base_images/storage.ex
> +      "uploads/tenants/#{tenant_id}/base_image_collections/#{base_image_collection_id}/base_images/#{version}.#{ext}"
Just nitpicking: the actual uploader does not keep the version in the filename, so you could skip that here too and still have uniformity.

2023-01-23 11:15 UTC, davidebriani commented on backend/lib/edgehog/base_images.ex
> +      base_images: [],
Not sure if loading the entire base image list by default is ideal. It seems to me that you don't use these preloads, since you can always call `BaseImages.list_base_images_for_collection/1` when you need the list.
Is the preload  required when defining the `base_images` assoc in the schema as `translatable_has_many`?

2023-01-23 16:55 UTC, szakhlypa requested changes

2023-01-23 16:55 UTC, szakhlypa commented on backend/lib/edgehog/base_images.ex
> +      iex> fetch_base_image!(123)
Remove exclamation marks in examples (`fetch_base_image!` -> `fetch_base_image`)

2023-01-25 15:22 UTC, rbino commented on backend/lib/edgehog/base_images.ex
> +      base_images: [],
The problem with calling `list_base_images_for_collection` is that it generates an N+1 query problem if, e.g., you're asking for the _list of base image collections_ and then for the _list of base images_ for each of them (which is something you could do using the GraphQL API, since I'm going to add a `base_images` field to the `base_image_collection` object).
Right now I'm always leaning towards the "Preload all the possible associations" approach, which is the fastest way to proceed. Once we have a good amount of code, I want to try to tackle this with a more structured and fine-grained approach (e.g. Dataloader), but I don't want to slow the development in this phase to experiment with this

2023-01-25 15:25 UTC, rbino commented on backend/test/edgehog/base_images_test.exs
> +      assert errors[:version] != nil
TIL

2023-01-25 15:35 UTC, rbino commented on backend/test/edgehog/base_images_test.exs
> +      base_image = create_base_image!()
While I linked the relevant resources, I agree with you that `create_base_image!` and `base_image_fixture` are doing basically the same thing, so I'll remove `create_base_image!` and use `base_image_fixture` (adapting it accordingly) when I'm not _testing_ the creation of the image (but rather I just want an image to use it in a test).
I'll do the same for `create_base_image_collection!`.

2023-01-25 16:14 UTC, davidebriani commented on backend/lib/edgehog/base_images.ex
> +      base_images: [],
Totally legit. Thanks for the explanation!

2023-01-25 16:27 UTC, rbino commented on backend/test/support/mocks/base_images/storage.ex
> +      "uploads/tenants/#{tenant_id}/base_image_collections/#{base_image_collection_id}/base_images/#{version}.#{ext}"
It does though: `storage_dir` creates the prefix, and then `filename` returns the version (the extension gets automatically appended from the original filename)

2023-01-25 17:16 UTC, rbino commented on backend/test/edgehog/base_images_test.exs
> +    end
As discussed out of band, this is an attempt to make tests clearer to concentrate only on the details that matter and reduce unrelated noise

2023-01-27 09:58 UTC, szakhlypa requested changes

2023-01-27 09:58 UTC, szakhlypa commented on backend/lib/edgehog_web/schema/base_images_types.ex
> +    field :base_image_collection, :base_image_collection
`, non_null(:base_image_collection)`

2023-01-30 11:43 UTC, davidebriani requested changes

2023-01-30 11:43 UTC, davidebriani commented on backend/lib/edgehog_web/schema/base_images_types.ex
> +        @desc "The ID of the base image to be updated."
The ID of the base image to be ~~updated~~ **deleted**.

2023-02-10 08:35 UTC, szakhlypa approved these changes

2023-02-23 08:32 UTC, merged