Add Update Channels
edgehog-device-manager/edgehog pull request #243
Opened 2023-02-01 17:36 UTC by rbino

Add a GraphQL CRUD for UpdateChannels, allowing to manage them an associate them with Target Groups

2023-02-02 17:44 UTC, davidebriani requested changes

2023-02-02 17:44 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns.ex
> +      iex> fetch_update_channel(456)
1. ~~Gets~~ **Fetches** a single update_channel
2. Typo in `:not_foun`
3. Update examples so that the function returns `{:ok, %UpdateChannel{}}` and `{:error, :not_found}`

2023-02-02 17:44 UTC, davidebriani commented on backend/test/edgehog/update_campaigns_test.exs
> +      assert UpdateCampaigns.fetch_update_channel(1_234_567) == {:error, :not_found}
`describe "fetch_update_channels/0"` -> `describe "fetch_update_channel/1"`

2023-02-02 17:44 UTC, davidebriani commented on backend/test/edgehog/update_campaigns_test.exs
> +  describe "update_update_channel/1" do
`update_update_channel/1` -> `update_update_channel/2`

2023-02-02 17:44 UTC, davidebriani commented on backend/test/support/fixtures/groups_fixtures.ex
> +  def unique_device_group_handle, do: "test-devices#{System.unique_integer([:positive])}"
Generate a unique ~~update_channel~~ **device_group** handle.

2023-02-02 17:44 UTC, davidebriani commented on backend/test/support/fixtures/groups_fixtures.ex
> +  def unique_device_group_name, do: "Test Devices#{System.unique_integer([:positive])}"
Generate a unique ~~update_channel~~ **device_group** name.

2023-02-02 17:44 UTC, davidebriani commented on backend/test/support/fixtures/groups_fixtures.ex
> +  def unique_device_group_selector, do: ~s<"test#{System.unique_integer([:positive])}" in tags>
Generate a unique ~~update_channel name~~ **device_group selector**.

2023-02-02 17:44 UTC, davidebriani commented on backend/priv/repo/migrations/20230130175529_add_update_channel_id_to_device_groups.exs
> +          )
You might want to add a `match: full` on the foreign key here.

2023-02-02 17:44 UTC, davidebriani commented on backend/test/support/fixtures/update_campaigns_fixtures.ex
> +  def unique_target_group_handle, do: "some-handle#{System.unique_integer([:positive])}"
Generate a unique ~~update_channel~~ **target_group** handle.

2023-02-02 17:44 UTC, davidebriani commented on backend/test/support/fixtures/update_campaigns_fixtures.ex
> +  def unique_target_group_name, do: "some name#{System.unique_integer([:positive])}"
Generate a unique ~~update_channel~~ **target_group** name.

2023-02-02 17:44 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns.ex
> +  ** (Ecto.NoResultsError)
1. ~~Gets~~ **Fetches** a single target group.
2. Update the examples so that the function returns `{:ok, %TargetGroup{}}` or `{:error, :not_found}`

2023-02-02 17:44 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_channel.ex
> +  end
I am missing the broader context, why a different `create_changeset/2` that does not cast or perform all the validations included in `changeset/2`?

2023-02-06 10:34 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel.ex
> +  end
Actually it does, we usually do separate create/update changesets by duplicating the whole function, but I realized that if you need a changeset that is strictly a superset of another one, you can just create the smaller changeset with its function and then add additional validation/casting, which eliminates duplicate code and the need to keep the two changesets in sync for the common parts.
In this case, `target_group_ids` is already cast in the `changeset` function, but when you update an `UpdateChannel` you don't have to necessarily pass `target_group_ids` if you don't need to update them, while you do have to pass them when you create it, so I just add an additional `validate_required` on top of the other changeset

2023-02-06 16:32 UTC, rbino commented on backend/priv/repo/migrations/20230130175529_add_update_channel_id_to_device_groups.exs
> +          )
`match: full` doesn't allow the id to be `NULL` (see [here](https://www.postgresql.org/docs/current/sql-createtable.html)), and since an `device_groups` is allowed to have no connected `update_channel`, this should be supported

2023-02-28 17:45 UTC, szakhlypa commented on backend/test/edgehog_web/schema/query/update_channels_test.exs
> +  describe "updateChannel query" do
`updateChannel` -> `updateChannels`

2023-02-28 17:45 UTC, szakhlypa commented on backend/test/support/fixtures/update_campaigns_fixtures.ex
> +  def unique_target_group_name, do: "some name#{System.unique_integer([:positive])}"
TargetGroup is a readonly, I'm not sure if we need `unique_target_group_handle` and `unique_target_group_name` fixtures.

2023-03-07 11:17 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel.ex
>    def changeset(update_channel, attrs) do
In this case I left this name like this because it's actually reused in `create_changeset` (which is something I suspect we can do more when we split the whole `update/create` stuff). It doesn't make much sense for `create_changeset` to call `update_changeset`, hence the naming.

2023-03-10 09:39 UTC, davidebriani approved these changes

2023-03-21 17:43 UTC, merged