[frontend] Add Update Channels
edgehog-device-manager/edgehog pull request #245
Opened 2023-02-27 14:43 UTC by szakhlypa

Adds forms and logic to create, update and delete `Update Channels`.

#### Create `Update Channel`:

https://user-images.githubusercontent.com/26611935/221592922-7ebf79b3-1e7c-4f23-aef7-df244ad3cbad.mp4

#### Create `Update Channel` (disabled target groups are in use for other `Update Channels`):

https://user-images.githubusercontent.com/26611935/221593266-768187c4-93e2-4169-ad8d-cd7d36c365da.mp4

#### Update and delete `Update Channel`:

https://user-images.githubusercontent.com/26611935/221593299-779eb3d6-b72c-406d-8cbd-4118b93fabf0.mp4

2023-03-01 17:49 UTC, davidebriani requested changes

2023-03-01 17:49 UTC, davidebriani commented on frontend/src/components/MultiSelect.tsx
> +  }
You're returning different components but passing the same props to both. How about:
```tsx
const SelectComponent = creatable ? CreatableSelect : Select;

return (
      <SelectComponent
        {...restProps}
        isMulti
        isDisabled={disabled}
        isLoading={loading}
        components={customComponents}
        className={`multi-select ${invalid ? "is-invalid" : ""}`}
        classNamePrefix="multi-select"
      />
    );
```

2023-03-01 17:49 UTC, davidebriani commented on frontend/src/forms/UpdateUpdateChannel.tsx
> +};
Not sure if this component with all this code is really necessary. I wonder if following the pattern already used for the other error messages would keep the code leaner and clearer:
```
errors.targetGroups?.message && <FormattedMessage id={errors.targetGroups.message} />
```

2023-03-01 17:49 UTC, davidebriani commented on frontend/src/forms/UpdateUpdateChannel.tsx
> +});
You're using `targetGroupWithUpdateChannelLabel` just once. You could evaluate whether to directly define the message inline where you're using it, so that you're colocating the values with the message definition and it's clear how they are rendered in the message. It might also make more evident the relation of this case "group used for channel" with the other cases "group not used" and "group used for this channel".

2023-03-01 20:41 UTC, davidebriani requested changes

2023-03-01 20:41 UTC, davidebriani commented on frontend/src/pages/UpdateChannelCreate.tsx
> +const CREATE_BASE_IMAGE_COLLECTION_MUTATION = graphql`
I guess `CREATE_BASE_IMAGE_COLLECTION_MUTATION` is a left-over from a copy&paste. Or is the name intentional?

2023-03-30 09:02 UTC, Pavinati approved these changes

2023-03-30 09:03 UTC, davidebriani requested changes

2023-05-03 16:03 UTC, szakhlypa commented on frontend/src/forms/UpdateUpdateChannel.tsx
> +};
RHF does not return valid type for `targetGroups` validation errors so we need to type guard it.
I've added comment with more detailed explanation and `TODO` note.

2023-05-03 16:11 UTC, szakhlypa commented on frontend/src/components/Sidebar.tsx
> +      />
We will review Sidebar menu groups after first implementation of fleet operations.

2023-05-03 16:25 UTC, merged