New ota interfaces
edgehog-device-manager/edgehog pull request #274
Opened 2023-05-16 11:03 UTC by rbino

2023-05-18 08:19 UTC, szakhlypa requested changes

2023-05-18 08:19 UTC, szakhlypa commented on backend/lib/edgehog/os_management/ota_operation.ex
> +    canceled: "Canceled"
Should we also add new status code for cases when OTA Operation is failed because device is offline?

2023-05-22 08:56 UTC, rbino commented on backend/lib/edgehog/os_management.ex
> +      if OTAOperation.final_state?(status) do
Imho no, at least for now. Currently we want to reflect the external information as much as possible, otherwise we might find ourselves in an inconsistent state wrt Astarte. If for some reason the device sends another update for the OTA Request even after reaching a final state, we want to be able to detect that.

2023-05-22 10:20 UTC, szakhlypa requested changes
We should also update year in Copyright header for following modified files:
- backend/lib/edgehog/astarte.ex
- backend/lib/edgehog_web/schema/os_management_types.ex
- backend/test/edgehog/astarte_test.exs
- backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
- backend/test/support/astarte_mock_case.ex
- backend/test/support/mocks/astarte/device/device_status.ex

2023-05-24 12:21 UTC, szakhlypa commented on backend/lib/edgehog_web/schema/os_management_types.ex
> +    field :status_progress, :integer
Migration defines `status_progress` as `NOT NULL`, do we also want to define GraphQL field as non-nullable?

2023-05-26 11:07 UTC, szakhlypa requested changes

2023-05-26 11:07 UTC, szakhlypa commented on CHANGELOG.md
> +  [`io.edgehog.devicemanager.OTAEvent`](https://edgehog-device-manager/edgehog-astarte-interfaces/pull/58).
```suggestion
  [`io.edgehog.devicemanager.OTAEvent`](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/58).
```

2023-05-26 11:07 UTC, szakhlypa commented on CHANGELOG.md
> +  v1.0](https://edgehog-device-manager/edgehog-astarte-interfaces/pull/57).
```suggestion
  v1.0](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/57).
```

2023-05-26 14:14 UTC, merged