Add validation for `base_api_url` in Astarte.Cluster changeset
edgehog-device-manager/edgehog pull request #280
Opened 2023-05-22 10:12 UTC by noaccOS

Validate that the given `base_api_url` is a valid URL by cheking that
- The scheme is either `"http"` or `"https"`
- The host is **not** `nil` or `""`

Closes #250

2023-05-22 15:35 UTC, rbino requested changes
This kind of change is localized enough that is should be contained in a single commit, please squash them together and provide a summary of the changes in the commit message.

2023-05-22 15:35 UTC, rbino commented on backend/lib/edgehog/astarte/cluster.ex
> +    with parsed_uri = URI.parse(url),
`with` chains should never start with a `=` match (or generally contain `=` matches which don't depend on the data inside the `with`), so that can be factored out (this was also caught [by the CI](https://github.com/edgehog-device-manager/edgehog/actions/runs/5046799181/jobs/9054549979?pr=280)).
Moreover, both conditions below are simple boolean, so replacing the `with` with an `if` actually makes sense and removes some noise (using pattern matching reduces it further)
```elixir
%URI{scheme: scheme, host: host} = URI.parse(url)
if scheme in ["http", "https"] and to_string(host) != "" do
  []
else
  ...
end
```

2023-05-22 15:35 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +      |> Enum.each(fn cluster -> assert {:error, %Ecto.Changeset{}} = cluster end)
While this leads to a single compact test, it has the defect that the first failing test will stop the testcase so you only discover that more than one case is failing when you fix the first one, opposed to discovering all the failing testcases in a single test run.
I'd create two more separate tests:
```
test "create_cluster/1 with invalid URL schema returns error changeset"
test "create_cluster/1 with invalid URL host returns error changeset"
```

2023-05-23 08:51 UTC, noaccOS commented on backend/test/edgehog/astarte_test.exs
> +      |> Enum.each(fn cluster -> assert {:error, %Ecto.Changeset{}} = cluster end)
> I'd create two more separate tests:

You mean I should have a total of 3 tests? Isn't it better to just split it in two in that case?

2023-05-24 10:07 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +      |> Enum.each(fn cluster -> assert {:error, %Ecto.Changeset{}} = cluster end)
Legit, you can leave the old test as is and introduce a new test that uses the technique above (attrs_list + `each`) to test some different corner cases of the URL validation.
Just a note: to further underline the fact that `name` is not actually relevant for the failur, build the attr_list something like:
```elixir
base_attrs = %{name: unique_cluster_name()}

invalid_url_attrs_list = 
  [
    %{base_api_url: "..."},
    %{base_api_url: "..."},
  ]
  |> Enum.map(&Enum.into(&1, base_attrs))
```
This makes it more evident to the reader that the name is not involved in the validity of the attributes

2023-05-25 10:08 UTC, noaccOS commented on backend/test/edgehog/astarte_test.exs
> +      |> Enum.each(fn cluster -> assert {:error, %Ecto.Changeset{}} = cluster end)
I ended up implementing 3 test blocks for create_cluster, as you originally suggested

I didn't consider there'd be cases of invalid data _outside_ the invalid url stuff, my bad

2023-05-25 10:12 UTC, noaccOS commented on backend/lib/edgehog/astarte/cluster.ex
> +    with parsed_uri = URI.parse(url),
Since I had to validate for "no spaces in host" anyway I preferred declaring `valid_scheme?` and `valid_host?` to make what I was doing more explicit (e4d78b5b518f0fb5248b3348815998539146bd93)

2023-05-26 10:57 UTC, rbino requested changes

2023-05-26 10:57 UTC, rbino commented on backend/lib/edgehog/astarte/cluster.ex
> +      else: [{field, "is not a valid URL"}]
Nit: as coding style, we usually use the keyword `do:` only for short function heads which return a value. For everything else (especially if there's an `else`, no pun intended) we use
```elixir
if ... do
  ...
else
  ...
end
```

2023-05-26 12:54 UTC, noaccOS commented
Commits squashed as requested

2023-05-31 12:55 UTC, rbino approved these changes

2023-05-31 12:55 UTC, merged