Fallback controller init
edgehog-device-manager/edgehog pull request #281
Opened 2023-05-23 09:45 UTC by noaccOS

use a fallback controller for `trigger_controller`'s error paths instead of crashing the process

2023-05-23 09:48 UTC, noaccOS commented
linked to #207

2023-05-31 12:56 UTC, rbino approved these changes

2023-05-31 13:00 UTC, rbino requested changes

2023-06-09 09:46 UTC, szakhlypa requested changes

2023-06-09 12:39 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +        |> post(path, event)
Done!

2023-06-09 14:23 UTC, szakhlypa approved these changes

2023-07-25 10:12 UTC, merged