[docs] Update docs for new OTA interfaces
edgehog-device-manager/edgehog pull request #283
Opened 2023-05-26 15:02 UTC by szakhlypa

Update links and trigger for new OTA interfaces

2023-05-26 15:07 UTC, rbino requested changes

2023-05-26 15:07 UTC, rbino commented on doc/pages/admin/deploying_with_kubernetes.md
> +            "interface_name": "io.edgehog.devicemanager.OTAEvent",
If the idea is supporting them both, at least for now, I'd probably install triggers for both of them (the old `OTAResponse` and the new `OTAEvent`)

2023-05-26 15:38 UTC, szakhlypa commented on doc/pages/admin/deploying_with_kubernetes.md
> +            "interface_name": "io.edgehog.devicemanager.OTAEvent",
Makes sense, added new trigger for OTAEvent.

2023-06-01 15:15 UTC, rbino approved these changes

2023-06-09 09:28 UTC, bettio approved these changes

2023-06-09 09:28 UTC, merged