Update Campaigns Execution
edgehog-device-manager/edgehog pull request #299
Opened 2023-06-16 17:26 UTC by rbino

This PR implements the actual rollout of the Update Campaigns. This makes them functional, with the exception of some corner cases that will be handled in subsequent iterations.

2023-07-03 17:14 UTC, szakhlypa requested changes

2023-07-03 17:14 UTC, szakhlypa commented on backend/test/edgehog/update_campaigns/push_rollout/core_test.exs
> +  test "mark_update_campaign_as_in_progress/1" do
```suggestion
  test "mark_update_campaign_as_in_progress!/1" do
```

2023-07-03 17:14 UTC, szakhlypa commented on backend/test/edgehog/update_campaigns/push_rollout/core_test.exs
> +  test "mark_update_campaign_as_failed/1" do
```suggestion
  test "mark_update_campaign_as_failed!/1" do
```

2023-07-03 17:14 UTC, szakhlypa commented on backend/test/edgehog/update_campaigns/push_rollout/core_test.exs
> +  test "mark_update_campaign_as_successful/1" do
```suggestion
  test "mark_update_campaign_as_successful!/1" do
```

2023-07-03 17:14 UTC, szakhlypa commented on backend/test/edgehog/update_campaigns/push_rollout/core_test.exs
> +  test "mark_target_as_failed/1" do
```suggestion
  test "mark_target_as_failed!/1" do
```

2023-07-03 17:14 UTC, szakhlypa commented on backend/test/edgehog/update_campaigns/push_rollout/core_test.exs
> +  test "mark_target_as_successful/1" do
```suggestion
  test "mark_target_as_successful!/1" do
```

2023-07-06 15:53 UTC, noaccOS requested changes

2023-07-10 12:20 UTC, rbino commented on backend/lib/edgehog/update_campaigns/push_rollout/core.ex
> +    end
I find the current version clearer tbh. The `with :error <- something()` works fine with a single match, but imho you lose clarity if success and failure matches are mixed together.

2023-07-10 12:29 UTC, rbino commented on backend/lib/edgehog/update_campaigns/push_rollout/core.ex
> +  end
The main idea is that `PushRollout.Core` should contain only functions that are used by `PushRollout.Executor`, optimized for this use case. On the other hand, the context functions are the public API exposed to the rest of the application.
Right now I'd prefer to keep the two things separate, because trying to merge them together too early could result in one confusing API instead of two APIs that just do what they need to do. We should at least wait the introduction of another rollout mechanism executor to see more clearly a refactoring path (for example, I expect that at that point this function would be moved in a separate "common" module that all executors can call, since it's not particularly tied to `PushRollou`)

2023-07-10 12:42 UTC, rbino commented on backend/lib/edgehog/update_campaigns/push_rollout/core.ex
> +  end
The code would be more compact (even if I'd use `Ecto.assoc` + `Repo.one!`, because that would better convey the meaning), but this would make this the only function that accepts an `update_campaign` instead of an `update_campaign_id` (other than the ones that actually update the update campaign).
Given the Executor only stores the ID, I'd rather keep the consistency given that we don't actually need all the rest of the struct.

2023-07-10 12:43 UTC, rbino commented on backend/lib/edgehog/update_campaigns/push_rollout/executor.ex
> +  @impl true
Done

2023-07-10 12:45 UTC, rbino commented on backend/test/edgehog/update_campaigns/push_rollout/core_test.exs
> +    Enum.reduce(0..(count - 1), target, fn _idx, target -> Core.increase_retry_count!(target) end)
But counting from 1 kills puppies :dog2:.
JK, done.

2023-07-10 13:29 UTC, rbino commented on backend/lib/edgehog/update_campaigns/push_rollout/executor.ex
> +    end
See above since it's related to that topic

2023-07-10 15:56 UTC, rbino commented on backend/lib/edgehog/os_management.ex
> +        PubSub.publish!(:ota_operation_created, ota_operation)
More than failing fast, the point is failing _loud_: `publish!` can fail only in really strange cases, and we want to know it happened

2023-07-11 08:18 UTC, szakhlypa requested changes

2023-07-11 08:18 UTC, szakhlypa commented on backend/lib/edgehog/update_campaigns.ex
> +      ExecutorSupervisor.start_executor(update_campaign)
Should we start `ExecutorSupervisor` before successful transaction? `PushRollout.Core` may read data from DB (for example in `get_update_campaign!/1`

2023-07-11 12:18 UTC, rbino commented on backend/lib/edgehog/update_campaigns/push_rollout/executor.ex
> +  end
I have not moved this to an internal event because while the other instance made sense since it was duplicated code, here I don't think it adds much value

2023-07-11 12:19 UTC, rbino commented on backend/lib/edgehog/update_campaigns/executor_supervisor.ex
> +      if Mix.env() == :test do
Moved `Mix.env` in the compilation scope so that test arguments are not even compiled in other environments

2023-07-12 10:38 UTC, Pavinati commented on .github/workflows/backend-test.yaml
> +    - name: Cahe Dialyzer's PLT
```suggestion
    - name: Cache Dialyzer's PLT
```

2023-07-13 13:10 UTC, noaccOS commented on backend/test/edgehog/update_campaigns/push_rollout/executor_test.exs
> +      max_errors_percentage = (0.2 + :rand.uniform() * 0.5) * 100
here too

2023-07-14 13:24 UTC, rbino commented on backend/test/edgehog/update_campaigns/push_rollout/executor_test.exs
> +      online_count = Enum.random(0..(target_count - 1))
This was actually correct (see the comment above), but I changed it to randomize the offline count (with your formula) and deriving the offline count from `target_count - offline_count` so it's more direct and clearer

2023-07-14 14:29 UTC, szakhlypa approved these changes

2023-07-14 14:39 UTC, noaccOS approved these changes

2023-07-14 15:03 UTC, merged