feat: Edgehog in 5 minutes
edgehog-device-manager/edgehog pull request #319
Opened 2023-07-06 16:24 UTC by noaccOS

Edgehog in 5 minutes guide, in the likes of [Astarte in 5 minutes](https://docs.astarte-platform.org/1.1/010-astarte_in_5_minutes.html).

Helps setup edgehog using the docker-compose file.

Depends on #311 #317 #318.

2023-11-29 11:48 UTC, rbino commented
@noaccOS all the PR this was depending on were merged, so you can pick it up again. Note that now Edgehog automatically reconciles interfaces and triggers, so the need to do so manually can be dropped from the guide.

2024-02-28 09:27 UTC, rbino requested changes

2024-02-28 09:27 UTC, rbino commented on doc/pages/tutorials/edgehog_in_5_minutes.md
> +First of all navigate to your astarte directory and run this command.
Trigger and interface installation can be removed since we now have the Reconciler which handles this for us

2024-02-28 15:57 UTC, noaccOS commented on doc/pages/tutorials/edgehog_in_5_minutes.md
> +First of all navigate to your astarte directory and run this command.
As the reconciler does not seem to work locally, I have applied the change in a separate commit, so that it can easily be squashed or dropped

2024-02-29 15:21 UTC, szakhlypa requested changes

2024-02-29 15:21 UTC, szakhlypa commented on doc/pages/tutorials/edgehog_in_5_minutes.md
> +Try navigating to `http://localhost:8080`: you should be presented with a login screen!
```suggestion
Try navigating to `http://edgehog.localhost`: you should be presented with a login screen!
```

2024-03-01 09:41 UTC, szakhlypa approved these changes

2024-03-01 09:47 UTC, merged