feat(push_rollout): `max_in_progress_updates` update api
edgehog-device-manager/edgehog pull request #358
Opened 2023-08-17 13:07 UTC by noaccOS

provide an api for updating push_rollout.
for now, only the field `max_in_progress_updates` is exposed through the graphql mutation.

includes edits to `push_rollout_executor` to handle the updates.

closes #278
re-implementation of #305
adapts and includes #325

2023-09-20 08:09 UTC, szakhlypa requested changes

2023-09-20 08:09 UTC, szakhlypa commented on backend/test/edgehog_web/schema/mutation/update_rollout_mechanism_test.exs
> +end
Not sure about naming, but having `updatePushRollout` mutation I think better to rename file to `update_push_rollout_test.exs` and update tests to:
```suggestion
defmodule EdgehogWeb.Schema.Mutation.UpdatePushRolloutTest do
  use EdgehogWeb.ConnCase

  import Edgehog.UpdateCampaignsFixtures

  describe "updatePushRollout mutation" do
    setup do
      {:ok, update_campaign: update_campaign_fixture()}
    end

    test "succeeds to increase max_in_progress_updates", %{
      conn: conn,
      api_path: api_path,
      update_campaign: update_campaign
    } do
      max_in_progress_updates = update_campaign.rollout_mechanism.max_in_progress_updates + 1

      response =
        update_push_rollout_mutation(conn, api_path,
          update_campaign_id: update_campaign.id,
          max_in_progress_updates: max_in_progress_updates
        )

      update_campaign = response["data"]["updatePushRollout"]["updateCampaign"]
      assert update_campaign["rolloutMechanism"]["maxInProgressUpdates"] ==
               max_in_progress_updates
    end

    test "fails to reduce max_in_progress_updates", %{
      conn: conn,
      api_path: api_path,
      update_campaign: update_campaign
    } do
      response =
        update_push_rollout_mutation(conn, api_path,
          update_campaign_id: update_campaign.id,
          max_in_progress_updates: update_campaign.rollout_mechanism.max_in_progress_updates - 1
        )

      assert response["data"]["updateCampaign"] == nil
      assert [%{"status_code" => 422, "message" => message}] = response["errors"]
      assert message =~ "must be greater than or equal to its previous value"
    end

    test "fails when trying to use a non-existing update campaign", %{
      conn: conn,
      api_path: api_path
    } do
      response = update_push_rollout_mutation(conn, api_path, update_campaign_id: "123456")

      assert %{"errors" => [%{"status_code" => 404, "code" => "not_found"}]} = response
    end
  end

  @query """
  mutation UpdatePushRollout($input: UpdatePushRolloutInput!) {
    updatePushRollout(input: $input) {
      updateCampaign {
        rolloutMechanism {
          ... on PushRollout {
            maxInProgressUpdates
          }
        }
      }
    }
  }
  """
  defp update_push_rollout_mutation(conn, api_path, opts) do
    update_campaign_id =
      Absinthe.Relay.Node.to_global_id(
        :update_campaign,
        opts[:update_campaign_id],
        EdgehogWeb.Schema
      )

    input =
      Enum.into(opts, %{})
      |> Map.put(:update_campaign_id, update_campaign_id)

    variables = %{input: input}

    conn = post(conn, api_path, query: @query, variables: variables)

    json_response(conn, 200)
  end
end
```

2023-09-20 09:31 UTC, noaccOS commented on backend/lib/edgehog/update_campaigns/push_rollout/executor.ex
> +      | rollout: rollout,
_if only this were a strongly typed language_

2023-09-20 09:33 UTC, noaccOS commented on backend/lib/edgehog/update_campaigns.ex
> +  end
done

2023-09-20 09:35 UTC, noaccOS commented on backend/lib/edgehog/update_campaigns/push_rollout/executor.ex
> +    if state == :wait_for_available_slots and new_slots_available?(data, new_data) do
makes sense, corrected

2023-09-20 09:35 UTC, noaccOS commented on backend/lib/edgehog/pubsub.ex
> +  defp topic_for_subject({:update_campaign, id}), do: "update_campaign:#{id}"
yeah best to keep it consistent

2023-09-20 09:51 UTC, noaccOS commented on backend/test/edgehog_web/schema/mutation/update_rollout_mechanism_test.exs
> +end
yup, forgot to check naming. thanks

2023-09-20 13:30 UTC, szakhlypa requested changes

2023-09-20 13:30 UTC, szakhlypa commented on backend/lib/edgehog_web/schema/update_campaigns_types.ex
> +    field :max_in_progress_updates, :integer
Should we also make `:max_in_progress_updates` non nullable?
```suggestion
    field :max_in_progress_updates, non_null(:integer)
```

2024-05-30 11:50 UTC, rbino commented
Closing this too, superseded by the Ash porting (the issue remains open, but this needs to be reimplemented on top of Ash)

2024-05-30 11:50 UTC, closed without merging