[frontend] Migrate to Vite
edgehog-device-manager/edgehog pull request #360
Opened 2023-09-01 08:08 UTC by szakhlypa

This PR migrates the frontend's development environment from [Create React App](https://create-react-app.dev/) to [Vite](https://vitejs.dev/).
Notable changes:

- Webpack and custom scripts are removed, and configuring the development environment is now done with Vite and its plugins.
- Proxy definitions for the Webpack's dev server are removed. The frontend now is just provided directly with the backend's URL.
- The [Jest](https://jestjs.io/) test runner has been removed in favor of [Vitest](https://vitest.dev/), an almost drop-in replacement.
- Command `npm run jest:test` has been renamed to `npm run test`, `npm run jest:coverage` to `npm run coverage`
- Other commands (`npm run start` and `npm run build`) and the development UX stay the same.

2023-09-01 09:39 UTC, davidebriani requested changes

2023-09-01 09:39 UTC, davidebriani commented on frontend/src/react-app-env.d.ts
> -}
I think we can remove the entire file, not just these lines, since we're not using `react-scripts` anymore.

Instead, you might want to have a `vite.env.d.ts` file with this content to support TypeScript intellisense:
```
/// <reference types="vite/client" />
/// <reference types="vitest" />
```

2023-09-01 09:39 UTC, davidebriani commented on frontend/vite.config.ts
> +      globals: true,
By enabling globals, you should be able to avoid explicitly importing `vi` in each test file.
Just remember to add `"types": ["vitest/globals"]` to the `compilerOptions` in the tsconfig to support Typescript types, as explained in [Vitest docs](https://vitest.dev/config/#globals).

2023-09-01 10:09 UTC, szakhlypa commented on frontend/vite.config.ts
> +      globals: true,
`vitest` was added as dev dependency, so we do not install it while building docker image `frontend/Dockerfile` (`RUN npm ci --omit=dev`).
In build command `tsc -P tsconfig.build.json && vite build` first part (`tsc -P tsconfig.build.json`) is used for type-checking and second one (`vite build`) runs build using Rollup bundler. Having `"types": ["vitest/globals"]` in `compilerOptions` will fail first part (as no dev dependency will be present).

We can:
- add `vitest` as NOT dev dependency and update `compilerOptions` with `vite/globals`
- stick with named imports from `vitest` (also right now there are lack of `it` and `expect` imports it test files, WIP) and remove `globals: true` from `test` section.

Please let me know what would you prefer, thanks.

2023-09-01 10:13 UTC, szakhlypa commented on frontend/src/react-app-env.d.ts
> -}
This file will be removed in next "clean up" commit.
Triple slash directives for `vite/client` and `vitest` for intellisense were added into `frontend/vite.config.ts`.

2023-09-01 10:45 UTC, davidebriani commented on frontend/vite.config.ts
> +      globals: true,
I really have no preference here, see what's suits you best :)

2023-09-04 08:40 UTC, davidebriani commented on frontend/src/components/MultiSelect.tsx
> +const MultiSelect = ({
Not sure why you removed the generic parameter here.
I think it was there to help infer types for all component's props; for instance, when you supply an array of `TargetGroup` as `options`, then the callbacks `getOptionLabel` and `getOptionValue` would be automatically typed as `(option: TargetGroup) => string`.

2023-09-04 09:03 UTC, davidebriani approved these changes

2023-09-04 10:19 UTC, szakhlypa commented on frontend/src/components/MultiSelect.tsx
> +const MultiSelect = ({
You are totally right.
There were `@typescript-eslint/no-unnecessary-type-constraint` errors on `Option extends any` as `any` does not add restrictions on which types can be used in `Option` but I missed inferring types for other component's props part.
Updated, thanks.

2023-09-04 10:21 UTC, szakhlypa commented on frontend/src/react-app-env.d.ts
> -}
Moved triple slash directives into `frontend/src/vite-env.d.ts`.

2023-09-04 11:53 UTC, davidebriani approved these changes

2023-09-19 12:48 UTC, Pavinati approved these changes

2023-09-19 12:52 UTC, merged