Implement pages for hardware types
edgehog-device-manager/edgehog pull request #39
Opened 2021-11-10 15:58 UTC by davidebriani

Add forms and logic to create and update Hardware Types in the frontend.

https://user-images.githubusercontent.com/60540759/141147473-7a859ab4-7711-4adb-bd65-9e29ed3d4a1e.mp4

2021-11-10 16:49 UTC, Pavinati requested changes

2021-11-10 16:49 UTC, Pavinati commented on frontend/src/forms/index.ts
> +    id: "validation.partNumberFormat",
what about `validation.array.min` and `validation.partNumber.format`?
We might have multiple validations for arrays and common types (ex: `array.max` or `partNumber.alreadyUsed`)

2021-11-10 16:49 UTC, Pavinati commented on frontend/src/forms/index.ts
> +  .matches(/^[a-z\d-]+$/, messages.partNumberFormat.id);
this only checks for the char-set used.
we might add an other match clause making sure it starts with a character and does not end with a hyphen?
Or maybe update the regex but i cannot think of a simple message to describe why the input is not valid
`/^[a-z][a-z\d-][a-z\d]$/`

2021-11-10 16:49 UTC, Pavinati commented on frontend/src/pages/HardwareTypeCreate.tsx
> +              description="Feedback for unknown creation error in the HardwareTypeCreate page"
i would drop descriptions for now, just to keep translations easy to mange once we think of how to index them across components and pages

2021-11-10 16:49 UTC, Pavinati commented on frontend/src/forms/UpdateHardwareType.tsx
> +                    {(errors.partNumbers || [])[index]?.value?.message && (
you can use optional chaining with indexes too `errors?.partNumbers?.[index]?.value?.message`

2021-11-10 16:49 UTC, Pavinati commented on frontend/src/forms/UpdateHardwareType.tsx
> +  const partNumbers = useFieldArray({
i would define this closed to the `useForm` definition, to prevent confusion with many surounding callbacks

2021-11-10 17:08 UTC, Pavinati requested changes

2021-11-10 17:08 UTC, Pavinati commented on frontend/src/mocks/relay.ts
> +      partNumbers: ["PN_0000001"],
this does not match the part number regexp validation

2021-11-10 18:13 UTC, davidebriani commented on frontend/src/mocks/relay.ts
> +      partNumbers: ["PN_0000001"],
There is no regexp validation on partNumbers, they just need to be non-empty strings.

2021-11-10 18:14 UTC, davidebriani commented on frontend/src/forms/index.ts
> +  .matches(/^[a-z\d-]+$/, messages.partNumberFormat.id);
Let's stick with the same regex used in the backend for now.

2021-11-10 18:25 UTC, Pavinati commented on frontend/src/mocks/relay.ts
> +      partNumbers: ["PN_0000001"],
my bad, i confused it with the `handle` property

2021-11-10 18:31 UTC, Pavinati commented on frontend/src/forms/index.ts
> +  .matches(/^[a-z\d-]+$/, messages.partNumberFormat.id);
Ok, but now the feedback field doesn't match what the regexp does. Starting the handle with a `-` would give an error but the user won't understand why.
We can have 2 regex, one for characters and one to say the handle cannot start with `-`, otherwise we have to update out feedback message to reflect the updated check.

2021-11-11 09:14 UTC, davidebriani commented on frontend/src/forms/index.ts
> +  .matches(/^[a-z\d-]+$/, messages.partNumberFormat.id);
Thanks, you're right. I updated the error message to `The part number must start with a letter and only contain lower case characters, numbers or the hyphen symbol -`, so now it matches the RegExp

2021-11-11 09:48 UTC, Pavinati commented on frontend/src/components/HardwareTypesTable.tsx
> +  Copyright 2021 SECO Mind
Missing Srl

2021-11-11 09:51 UTC, Pavinati requested changes

2021-11-11 09:51 UTC, Pavinati commented on frontend/src/i18n/langs/en.json
> +    "defaultMessage": "Only lower case characters, numbers and the hypen symbol are allowed."
this must be updated

2021-11-11 11:00 UTC, Pavinati approved these changes

2021-11-11 11:20 UTC, bettio approved these changes

2021-11-11 11:20 UTC, merged