Provisioning Context
edgehog-device-manager/edgehog pull request #395
Opened 2023-10-16 16:55 UTC by rbino

Add the `Provisioning` context to coordinate the provisioning of a Tenant with an associated realm and cluster

2023-10-16 18:02 UTC, davidebriani requested changes

2023-10-17 08:03 UTC, davidebriani requested changes

2023-10-17 08:47 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +  def upsert_cluster(attrs \\ %{}) do
Yeah I was not fond of the name too, but I didn't find anything better. Just thought, maybe `ensure_cluster`?

On the name update, I separated this exactly because I don't like the fact that you can change the name that was set by another tenant provisioning. Moreover, the name is strictly a display value (hence why I made it nullable), the cluster is identified just by its `base_api_url`.

2023-10-17 12:55 UTC, davidebriani requested changes

2023-10-17 12:55 UTC, davidebriani commented on backend/lib/edgehog/provisioning.ex
> +           {:ok, realm} <- create_realm(cluster, astarte_config) do
I find that using `Repo.put_tenant_id(tenant.tenant_id)` it's not really self-explanatory and it's difficult to understand its implications or what block of code is depending on that `tenant_id`.

Maybe we could add a bit more clarity by moving `Repo.put_tenant(tenant.tenant_id)` near `create_realm(...)`, which is the code that actually depends on the `tenant_id` being set.

As a side note, we could keep the `upsert_cluster` diction instead of `create_cluster`, since that's the operation performed underneath.

2023-10-17 13:02 UTC, davidebriani requested changes

2023-10-17 15:10 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +  def upsert_cluster(attrs \\ %{}) do
I prefer `get_or_create` if we just pass `base_api_url`, `ensure_` would lean me more towards passing an `attrs` map

2023-10-17 16:08 UTC, davidebriani commented on backend/priv/repo/migrations/20231013091205_make_base_api_url_unique.exs
> +  end
Since we already support the option, we might as well use `schema_migration: true` instead of `skip_tenant_id: true` here.

2023-10-17 16:20 UTC, szakhlypa approved these changes

2023-10-17 16:28 UTC, merged