[backend] Add Admin REST API
edgehog-device-manager/edgehog pull request #400
Opened 2023-10-25 17:22 UTC by szakhlypa

Add Admin REST API on `/admin-api/`.
Require JWT authentication with validation via public key.
Expose tenant provisioning via POST to `/admin-api/v1/tenants`.

2023-10-26 16:33 UTC, rbino requested changes

2023-10-26 16:33 UTC, rbino commented on backend/lib/edgehog/config.ex
> +  app_env :admin_api_public_key, :edgehog, :admin_api_public_key,
Not sure which way to go here, but in Astarte Housekeeping API we provide [the path](https://github.com/astarte-platform/astarte/blob/01c851032da01dfa7f476408e75d1ae2a687df0b/apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/config.ex#L39) to a file that contains the public key (using a custom Skogsra type). Let's discuss this to see which approach is better.

2023-10-26 16:33 UTC, rbino commented on backend/lib/edgehog_web/router.ex
> +  forward "/admin-api", EdgehogWeb.AdminAPI.Router
Why do we need a separate router for this? We can just add a scope + `pipeline :admin_api` here I guess

2023-11-03 09:06 UTC, szakhlypa commented on backend/lib/edgehog_web/router.ex
> +  forward "/admin-api", EdgehogWeb.AdminAPI.Router
We may want to divide routes by domain in future, for now - added Admin API scope and pipeline into main router.

2023-11-13 11:06 UTC, merged