add tests for the Tabs component
edgehog-device-manager/edgehog pull request #401
Opened 2023-10-30 12:51 UTC by harisbikovic

Related: #390 
This PR adds tests for the Tabs component.

2023-12-13 07:41 UTC, szakhlypa requested changes

2024-01-15 17:10 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +        screen.getByRole("tab", { name: "Tab 1", selected: true }),
Can we also add a check that `Tab 2` is NOT selected?

2024-01-15 17:10 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +
Let's also check that selected `tab` is changed from `Tab 1` to `Tab 2`

2024-01-15 17:13 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +      expect(screen.queryByTestId("tab2-content")).not.toBeInTheDocument();
Does this like repeat `renders the content of the active tab only` test?

2024-01-15 17:14 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +      expect(screen.getByTestId("tab1-content")).toBeVisible();
Can we also check the selected tab?

2024-01-15 17:18 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +    it("when the key specified is not present in any of the Tabs won't render any Tab's content", () => {
Is this the intended behaviour?

2024-01-15 17:29 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +    it("when defaultActiveKey given and tabsOrder differs from the order of children, renders tabs as specified in tabsOrder", () => {
How does the `tabs` rendering order depend on `defaultActiveKey`?
Do you want to check that if `defaultActiveKey` is present, regardless of the `tabsOrder`, it determines which tab's content is rendered?

2024-01-15 17:34 UTC, szakhlypa commented on frontend/src/components/Tabs.test.tsx
> +  it("renders the Tab component with the specified title", () => {
Does this test repeat the `it("renders tab elements correctly"` above?
Do you want to set `className` here, and if so - what for?

2024-01-18 08:15 UTC, harisbikovic commented on frontend/src/components/Tabs.test.tsx
> +        screen.getByRole("tab", { name: "Tab 1", selected: true }),
Actually line 89 checks that:
`expect(screen.queryByTestId("tab2-content")).not.toBeInTheDocument();`
Is this valid or you have something different on your mind?

2024-01-18 08:38 UTC, harisbikovic commented on frontend/src/components/Tabs.test.tsx
> +      expect(screen.queryByTestId("tab2-content")).not.toBeInTheDocument();
In this case we test what happens when there is no **defaultActiveKey** specified whereas in the above mentioned `renders the content of the active tab only` test we specify the **defaultActiveKey**. So we're testing the same behaviour but in different scenarious. Is this ok wtih you?

2024-01-18 08:52 UTC, harisbikovic commented on frontend/src/components/Tabs.test.tsx
> +    it("when the key specified is not present in any of the Tabs won't render any Tab's content", () => {
Hmm, I'm not sure what can be done about it?

2024-01-18 09:34 UTC, harisbikovic commented on frontend/src/components/Tabs.test.tsx
> +    it("when defaultActiveKey given and tabsOrder differs from the order of children, renders tabs as specified in tabsOrder", () => {
You're right, I mistakenly used `defaultActiveKey` in this section. Therefore, there's no need for this test since there's one  test above called `when specified renders tabs in the requested order` that tests the same thing.

2024-01-23 14:58 UTC, szakhlypa approved these changes

2024-01-23 15:05 UTC, merged