Add Reconciler
edgehog-device-manager/edgehog pull request #403
Opened 2023-11-07 17:10 UTC by rbino

Automatically reconcile Astarte resources in all Tenants. API Key authentication of triggers will be added in a separate PR.

2023-11-08 11:56 UTC, davidebriani approved these changes

2023-11-08 11:56 UTC, davidebriani commented on CHANGELOG.md
> +  tenant ([#403](https://github.com/edgehog-device-manager/edgehog/pull/403))
Since you're referencing the PR and not the actual issue, it would be nice to have the PR linked to the issue: by adding `Closes #286` to this commit and the PR description.

2023-11-08 13:59 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +        {:error, api_error(status: 501, message: "Internal Server Error")}
Right, it started with `500` but then we realized that's what RM returns for "Not found" :smile:

2023-11-08 16:10 UTC, szakhlypa requested changes

2023-11-08 16:10 UTC, szakhlypa commented on backend/lib/edgehog/application.ex
> +      EdgehogWeb.Router.Helpers.astarte_trigger_url(EdgehogWeb.Endpoint, :process_event, slug)
I have not found where we configure backend's host to generate external URLs for triggers.

2023-11-08 16:21 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +
It makes sense given we want to verify the workaround is working

2023-11-08 17:07 UTC, rbino commented on backend/lib/edgehog/application.ex
> +      EdgehogWeb.Router.Helpers.astarte_trigger_url(EdgehogWeb.Endpoint, :process_event, slug)
I added `URL_HOST` as required env variable

2023-11-08 17:23 UTC, szakhlypa requested changes

2023-11-08 17:23 UTC, szakhlypa commented on doc/pages/admin/deploying_with_kubernetes.md
> +- `BACKEND-URL`: the host of the Edgehog backend (see the [Creating DNS
```suggestion
- `BACKEND-HOST`: the host of the Edgehog backend (see the [Creating DNS
```

2023-11-08 17:27 UTC, szakhlypa approved these changes

2023-11-13 17:04 UTC, davidebriani approved these changes

2023-11-13 17:12 UTC, szakhlypa approved these changes

2023-11-13 17:13 UTC, merged