Port Tenants context to Ash
edgehog-device-manager/edgehog pull request #421
Opened 2023-12-13 22:31 UTC by rbino

Let's get the ball rolling

2023-12-14 14:24 UTC, davidebriani requested changes

2023-12-14 14:24 UTC, davidebriani commented on backend/lib/edgehog/validations/validations.ex
> +defmodule Edgehog.Validations do
Is it intended that the `Edgehog.Validations` module lives in the file `edgehog/validations/validations.ex` instead of `edgehog/validations.ex`?
I am curious if there are some practices we want to follow with module names and folder structure, or if it doesn't really matter.

2023-12-14 14:24 UTC, davidebriani commented on backend/lib/edgehog_web/populate_tenant.ex
> +    case Tenants.Tenant.by_slug(tenant_slug) do
Let's update the copyright's year

2023-12-14 14:32 UTC, rbino commented on backend/lib/edgehog/tenants/tenant.ex
> +    end
@szakhlypa it's possible to setup a Spark (the Ash DSL) [formatter plugin](https://hexdocs.pm/ash/development-utilities.html#configuration) that enforces the order of sections inside a resource. There is no predefined order, so we can indulge in some bikeshedding here int the first PR so we come to an agreement and enforce that in all the subsequent ones.

My proposal is: resource, graphql, code_interface, actions, attributes, relationships, calculations, aggregates, validations, preparations, changes, pub_sub, postgres.

The rough idea is going (top to bottom) from user-facing things to internal details.

2023-12-14 14:42 UTC, szakhlypa commented on backend/lib/edgehog/validations/validations.ex
> +defmodule Edgehog.Validations do
It's one of the Ash [recommendations](https://www.ash-hq.org/docs/guides/ash/latest/how_to/structure-your-project) on how to structure project:
`If the resource has a folder, we suggest putting the resource.ex in the folder with the same name.`
This way every context file should be inside context directory.

2023-12-14 15:02 UTC, rbino commented on backend/lib/edgehog/validations/validations.ex
> +defmodule Edgehog.Validations do
We decided to adopt [Ash suggested project structure](https://hexdocs.pm/ash/structure-your-project.html). Of course this is not a requirement (modules work regardless of where you put them), but I've come to appreciate this mainly due to this: if you execute `ls` in Edgehog's backend `lib` directory today, you see this

![2023-12-14-155308_1801x348_scrot](https://github.com/edgehog-device-manager/edgehog/assets/2528778/0aedef20-a9c8-40d0-bb3d-45ce43dd5b08)

If instead you move "root" context files _inside_ their directory, there is much less noise

![2023-12-14-160009_1717x173_scrot](https://github.com/edgehog-device-manager/edgehog/assets/2528778/2a9e25c1-8d66-47f8-88ad-5084d59a1474)

 You either see single-file contexts (`.ex` files) _or_ you see a context directory. This goes on recursively inside (if a `User` resource just has its resource file it will go in the top context level, if it also has some additional module-based stuff it goes inside its `user` directory).

2023-12-14 15:08 UTC, rbino commented on backend/lib/edgehog/validations/validations.ex
> +defmodule Edgehog.Validations do
Oops took too much to reply and you already figured all this out :smile:

2023-12-19 14:36 UTC, szakhlypa approved these changes

2023-12-19 14:37 UTC, merged