Clean up S3 after tenant deletion
edgehog-device-manager/edgehog pull request #422
Opened 2023-12-14 10:55 UTC by szakhlypa

Clean up S3 storage files asynchronously after successfully deleting a tenant.

2023-12-15 10:25 UTC, rbino requested changes
A couple of nits and a couple of tests that can be dropped then we're good to go

2023-12-15 10:25 UTC, rbino commented on backend/lib/edgehog/application.ex
> +      {Task.Supervisor, name: Edgehog.ProvisioningTaskSupervisor}
Nit: this should be started _before_ Endpoint because as it is right now theoretically you could receive a request to the Provisioning controller and not have the cleanup supervisor ready

2023-12-15 10:25 UTC, rbino commented on backend/lib/edgehog/application.ex
> +      {Task.Supervisor, name: Edgehog.ProvisioningTaskSupervisor}
Also, use a namespaced (and more specific) name: `Edgehog.Provisioning.CleanupSupervisor`. This way you can alias it without conflicts.

2023-12-15 10:25 UTC, rbino commented on backend/test/edgehog/provisioning_test.exs
> +    end
You're delaying the tests by 4 second to basically test that `Task.async` works as expected, I'd drop this test

2023-12-15 10:25 UTC, rbino commented on backend/test/edgehog/provisioning_test.exs
> +    end
Imho this is still testing the inner working of `Task.async`, we can drop this too

2023-12-19 09:50 UTC, szakhlypa commented on backend/lib/edgehog/application.ex
> +      {Task.Supervisor, name: Edgehog.ProvisioningTaskSupervisor}
Renamed, moved both supervisors (`Reconciler` and `Provisioning`) to start before Endpoint.

2023-12-19 09:53 UTC, szakhlypa commented on backend/test/edgehog/provisioning_test.exs
> +    end
Removed unnecessary test

2023-12-19 09:53 UTC, szakhlypa commented on backend/test/edgehog/provisioning_test.exs
> +    end
Removed unnecessary test

2023-12-20 17:05 UTC, rbino approved these changes

2023-12-20 17:05 UTC, merged