Port Astarte.Cluster resource to Ash
edgehog-device-manager/edgehog pull request #423
Opened 2023-12-14 16:04 UTC by rbino

2023-12-19 15:24 UTC, szakhlypa requested changes

2023-12-19 15:24 UTC, szakhlypa commented on backend/test/edgehog/astarte_test.exs
> +    test "create/1 with existing base_api_url succeeds and updates the name" do
Do we want to test `and updates the name` part in the same test?
```elixir
    test "create/1 with existing base_api_url succeeds and updates the name" do
      %Cluster{base_api_url: base_api_url} = cluster_fixture()

      assert {:ok, %Cluster{} = cluster} =
               Cluster.create(%{base_api_url: cluster.base_api_url, name: "some updated name"})

      assert cluster.base_api_url == base_api_url
      assert cluster.name == "some updated name"
    end
```
or to have two tests like
```elixir
    test "create/1 with existing base_api_url returns existing cluster" do
      cluster = cluster_fixture()

      assert {:ok, ^cluster} = Cluster.create(%{base_api_url: cluster.base_api_url})
    end

    test "create/1 with existing base_api_url updates the name" do
      %Cluster{id: id, base_api_url: base_api_url} = cluster_fixture()

      assert {:ok, %Cluster{} = cluster} =
               Cluster.create(%{base_api_url: base_api_url, name: "some updated name"})

      assert cluster.id == id
      assert cluster.base_api_url == base_api_url
      assert cluster.name == "some updated name"
    end
```

2023-12-20 10:32 UTC, rbino commented on backend/test/edgehog/astarte_test.exs
> +    test "create/1 with existing base_api_url succeeds and updates the name" do
TBH yesterday I was re-evaluating the behaviour, I think I will not include the name in the upserted fields. The idea is that if a cluster already exists, then its name is not going to be updated when you try to re-create it.

2023-12-22 09:03 UTC, szakhlypa requested changes

2024-01-11 17:28 UTC, szakhlypa approved these changes

2024-01-11 17:28 UTC, szakhlypa commented on backend/test/edgehog/astarte/cluster_test.exs
> +
Do we want to test that `name` is optional?
```elixir
    test "creates cluster without name" do
      %{base_api_url: url} = @valid_attrs

      assert {:ok, %Cluster{} = cluster} = Cluster.create(%{base_api_url: url})
      assert cluster.base_api_url == url
      assert cluster.name == nil
    end
```

2024-01-15 10:52 UTC, szakhlypa approved these changes

2024-01-15 10:53 UTC, merged