Restore Tenant reconciliation
edgehog-device-manager/edgehog pull request #425
Opened 2023-12-18 18:09 UTC by rbino

Expose `:realm_management_client` as calculation from the Realm resource and restructure Interface and Trigger modules to implement an access pattern similar to Ash resources.

2024-01-18 14:37 UTC, rbino commented on backend/lib/edgehog/astarte/realm/calculations/realm_management_client.ex
> +defmodule Edgehog.Astarte.Realm.Calculations.RealmManagementClient do
This is clearly not a renamed file, `git` go home you're drunk

2024-01-18 16:24 UTC, szakhlypa requested changes

2024-01-18 16:24 UTC, szakhlypa commented on backend/lib/edgehog/astarte/realm/realm.ex
> +      allow_nil? false
We declare here that the calculation cannot return `nil`, however, in the implementation it can. Is this intended?

2024-01-18 16:24 UTC, szakhlypa commented on backend/lib/edgehog/tenants/reconciler.ex
> +    |> Tenants.read(load: tenant_reconciliation_loads())
Shoudn't it be `read!` to get list of tenants?
```suggestion
    |> Tenants.read!(load: tenant_reconciliation_loads())
```

2024-01-19 08:51 UTC, davidebriani approved these changes

2024-01-19 09:02 UTC, merged