add tests for HardwareTypesTable component
edgehog-device-manager/edgehog pull request #427
Opened 2024-01-10 14:12 UTC by harisbikovic

This PR adds tests for the HardwareTypesTable component.

2024-01-15 16:47 UTC, szakhlypa requested changes

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +      hardwareTypes && <HardwareTypesTable hardwareTypesRef={hardwareTypes} />
Do we need to check on `hardwareTypes`?

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +  it("does suspension correctly", () => {
```suggestion
  it("suspends correctly", () => {
```

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    const columns = within(head).getAllByRole("columnheader");
Why do we repeat the `columnheader` check in every rendering test? Could we create separate unit-test for it?

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +  it("renders table with multiple rows when data fetched contains multiple elements", async () => {
What the reason to add this test? Rendering multiple rows should be tested on `Table.tsx` level.

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    expect(cells[2]).toHaveTextContent(hwType.partNumbers.join(", "));
We add a test to make sure that `HardwareType` with few `partNumbers`  has them rendered with comma separators, but there is no test for what happens when `HardwareType` has only one partNumber.

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    expect(columns[0]).toHaveTextContent("Hardware Type Name");
I think it's better not to depend on the order of the columns and test them with 

```typescript
expect(screen.getByRole("columnheader", { name: "Hardware Type Name" })).toBeInTheDocument();
```
Same for the cells below.

Please let me know if you agree. Maybe we can have one test with the order check and all the others just checking for presence?

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    expect(tableElements).toHaveLength(2);
Why do we repeat this code in every rendering test? Can we have one unit test for it?

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    ).toBeInTheDocument();
Do we want to test that link has correct href attribute?

2024-01-15 16:47 UTC, szakhlypa commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    expect(cells[0]).toHaveTextContent(hwType.name);
Expect seems redundant, you already tested on link's name just above.

2024-01-16 10:07 UTC, harisbikovic commented on frontend/src/components/HardwareTypesTable.test.tsx
> +    expect(columns[0]).toHaveTextContent("Hardware Type Name");
Yes, I think that's a good idea.

2024-02-21 09:05 UTC, szakhlypa requested changes

2024-02-21 09:06 UTC, szakhlypa approved these changes

2024-02-21 09:07 UTC, merged