Restore Tenant Provisioning
edgehog-device-manager/edgehog pull request #429
Opened 2024-01-15 17:42 UTC by rbino

Move it to the `Tenants` API, removing the `Provisioning` context.
Use AshJsonApi to expose a new JsonApi compatible API.

2024-01-18 17:23 UTC, rbino commented on backend/lib/edgehog/tenants/tenant/manual_actions/reconciler_action.ex
> +    {:ok, result}
Yes, `run` must return an `:ok/:error` tuple as can be seen by the callback
https://hexdocs.pm/ash/Ash.Resource.Actions.Implementation.html#callbacks
(note to self: add the behaviour because it's missing)

2024-01-18 17:24 UTC, davidebriani requested changes

2024-01-18 17:24 UTC, davidebriani commented on backend/lib/edgehog/tenants/tenant/changes/provision_astarte_resources.ex
> +  end
Does this run within a transaction with respect to the action?
I wonder whether it could be that tenant creation succeeds while provisioning the Astarte resources fails.

2024-01-18 17:24 UTC, davidebriani commented on backend/test/edgehog_web/admin_api/tenants/tenant_test.exs
> +      end
Besides `detail`, is a `path` field also available to check that the error is related to the `astarte_config`?

2024-01-19 11:11 UTC, rbino commented on backend/lib/edgehog/tenants/tenant/changes/provision_astarte_resources.ex
> +  end
Yes `after/before_action` are executed inside the transaction, this is shown [here](https://hexdocs.pm/ash/actions.html#action-lifecycle). If the `after_action` fails, the transaction is rolled back.

2024-01-19 11:15 UTC, rbino commented on backend/lib/edgehog/tenants/tenant/tenant.ex
> +    define :provision
I've left it out so the call is `Tenant.provision(%{name: ..., astarte_config: ...})`. If you specify `arg` here, the mentioned argument gets promoted to a positional argument, so `Tenant.provision(astarte_config, %{name: ...,})`. Given `astarte_config` is no more special than the other params, I've decided to just leave it inside the params map.

2024-01-19 11:28 UTC, rbino commented on backend/test/edgehog_web/admin_api/tenants/tenant_test.exs
> +      end
This actually gets printed for attributes
![2024-01-19-122746_948x328_scrot](https://github.com/edgehog-device-manager/edgehog/assets/2528778/5cc7a005-2551-4b3e-8120-f21784abef65)
But not for arguments inside `astarte_config`
![2024-01-19-122820_884x284_scrot](https://github.com/edgehog-device-manager/edgehog/assets/2528778/512fc382-bdf1-4920-9691-4d8ab09323cb)
I'll investigate further but I don't think it's a blocker currently

2024-01-19 11:39 UTC, davidebriani approved these changes

2024-01-19 14:15 UTC, szakhlypa requested changes

2024-01-19 14:16 UTC, szakhlypa commented on backend/lib/edgehog/tenants/tenant/changes/trigger_reconciliation.ex
> +    Ash.Changeset.after_action(changeset, fn _changeset, tenant ->
Do we need to specify that this action should not abort the transaction?
```elixir
    Ash.Changeset.after_transaction(changeset, fn 
      _changeset, {:ok, tenant} -> 
        Tenants.Tenant.reconcile(tenant)
        
        {:ok, tenant}

      _changeset, {:error, error} ->
        
        {:error, error}
    end)
```

2024-01-19 14:22 UTC, szakhlypa commented on backend/test/edgehog_web/admin_api/tenants/tenant_test.exs
> +        |> put_req_header("accept", "application/vnd.api+json")
Should we add headers in `EdgehogWeb.AdminAPI.ConnCase`?

2024-01-19 14:54 UTC, szakhlypa commented on backend/lib/edgehog/tenants/astarte_config.ex
> +  alias Edgehog.Validations
```suggestion
```

2024-01-19 15:41 UTC, szakhlypa commented
`Edgehog.Tenants.Reconciler.Behaviour` [expects](https://github.com/edgehog-device-manager/edgehog/blob/from-ash-we-rise/backend/lib/edgehog/tenants/reconciler/behaviour.ex#L24) `Edgehog.Tenants.Tenant` to have a typespec `@type t()`.
Ash.Resource has [`@type record :: struct()`](https://github.com/ash-project/ash/blob/main/lib/ash/resource.ex#L9C3-L9C27).

I think we can start with `@type record :: Ash.Resource.record()` for `Tenant` and `Tenant.record()` in `Reconciler.Behaviour`

2024-01-19 15:52 UTC, szakhlypa commented on backend/lib/edgehog/tenants/tenant/changes/provision_astarte_resources.ex
> +  alias Edgehog.Tenants
Unused aliases that you may have wanted to use for pattern matching.

2024-01-19 16:01 UTC, szakhlypa commented on backend/test/edgehog/tenants_test.exs
If module `Edgehog.Tenants` has `lib/edgehog/tenants/tenants.ex` path, should also `Edgehog.TenantsTest` be   in `test/edgehog/tenants/tenants_test.exs` ?

2024-01-22 09:20 UTC, rbino commented on backend/lib/edgehog/tenants/tenant/changes/trigger_reconciliation.ex
> +    Ash.Changeset.after_action(changeset, fn _changeset, tenant ->
`after_action` doesn't get executed if the action is not successful

2024-01-22 09:27 UTC, rbino commented on backend/lib/edgehog/tenants/tenant/changes/trigger_reconciliation.ex
> +    Ash.Changeset.after_action(changeset, fn _changeset, tenant ->
Ok I see you changed to `after_transaction`, but the original action can't fail, so I guess using `after_action` is the same (and it's more compact because you don't have to handle the error case).

Moreover, in the future we could start leveraging the Notification mechanism of Ash since I think this fits nicely that pattern (I'll add a TODO comment)

2024-01-22 12:25 UTC, rbino commented on backend/test/edgehog/tenants_test.exs
Imho that's a different convention because `tenants` != `tenants_test` (and the `_test` suffix is required by ExUnit). I'd leave the tests as they are for now.

2024-01-22 14:22 UTC, szakhlypa requested changes

2024-01-22 14:22 UTC, szakhlypa commented on backend/test/edgehog_web/admin_api/auth_test.exs
> +      |> put_req_header("accept", "application/vnd.api+json")
No need to add headers (anymore), they are now added in the `EdgehogWeb.AdminAPI.ConnCase`.

2024-01-22 14:22 UTC, szakhlypa commented on backend/lib/edgehog/tenants/tenant/manual_actions/reconciler_action.ex
> +  alias Edgehog.Tenants.Tenant.Reconciler
There is still an alias for `Edgehog.Tenants.Tenant.Reconciler` (module does not exists), we need to use `alias Edgehog.Tenants.Reconciler`.

2024-01-22 16:03 UTC, szakhlypa approved these changes

2024-01-22 16:05 UTC, merged