Initialize AshGraphQL and port tenantInfo query
edgehog-device-manager/edgehog pull request #430
Opened 2024-01-17 21:55 UTC by rbino

Also revamp auth and context generation, leveraging Ash utilities

2024-01-22 17:33 UTC, davidebriani approved these changes

2024-01-22 17:33 UTC, davidebriani commented on backend/test/support/conn_case.ex
> -        authenticate_connection(conn, tenant_private_key)
You can remove the `authenticate_connection` function if it's not used anymore.

2024-01-22 17:33 UTC, davidebriani commented on backend/test/edgehog_web/auth_test.exs
> +  # This can't be async: true since it modifies the Application env
I'm not sure what this refers to, the `ConnCase` doesn't seem to touch the `Application` env, at least directly.

2024-01-23 07:03 UTC, rbino commented on backend/test/support/conn_case.ex
> -        authenticate_connection(conn, tenant_private_key)
It's actually used in `auth_test` (it gets imported there)

2024-01-24 14:54 UTC, szakhlypa requested changes

2024-01-24 15:06 UTC, rbino commented on backend/lib/edgehog/tenants/tenant/tenant.ex
> +      read_one :tenant_info, :current_tenant
Fixed both

2024-01-25 09:05 UTC, szakhlypa approved these changes

2024-01-25 09:05 UTC, merged