Port Hardware Type to Ash
edgehog-device-manager/edgehog pull request #433
Opened 2024-01-23 16:31 UTC by rbino

Add all the relevant tests in the Graphql part and remove unused old code

2024-01-24 16:05 UTC, davidebriani approved these changes

2024-01-31 14:30 UTC, szakhlypa requested changes

2024-01-31 14:30 UTC, szakhlypa commented on backend/lib/edgehog/devices/hardware_type.ex
> +      update :update_hardware_type, :update
```graphql
  updateHardwareType(
    id: ID
    input: UpdateHardwareTypeInput
  ): UpdateHardwareTypeResult
```
Same here, `ID` and `input` should be non-nullable

2024-01-31 14:30 UTC, szakhlypa commented on backend/lib/edgehog/devices/hardware_type.ex
> +      destroy :delete_hardware_type, :destroy
```graphql
deleteHardwareType(id: ID): DeleteHardwareTypeResult
```
id should be non-nullable

2024-01-31 14:30 UTC, szakhlypa commented on backend/test/edgehog_web/schema/mutation/delete_hardware_type_test.exs
>            id
Querying `partNumbers` of deleted HardwareType (add next fields after `id`)
```graphql
          partNumbers {
            partNumber
          }
```
returns `null` in `result` with 
```elixir
errors: [
    %{
      message: "Cannot return null for non-nullable field",
      path: ["deleteHardwareType", "result", "partNumbers", 0, "partNumber"],
      locations: [%{line: 6, column: 9}]
    }
  ]
```

2024-01-31 14:30 UTC, szakhlypa commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +    test "returns error for empty part_numbers", %{tenant: tenant, hardware_type: hardware_type} do
We can also check for invalid `part_number` like
```elixir
    test "returns error for invalid part_number", %{tenant: tenant, hardware_type: hardware_type} do
      result =
        update_hardware_type_mutation(
          tenant: tenant,
          id: hardware_type.id,
          part_numbers: [""]
        )

      assert %{"fields" => ["part_number"], "message" => "is required"} =
               extract_error!(result)
    end
```
But we have no `partNumber` input field, not sure how to return this error better.

2024-01-31 14:30 UTC, szakhlypa commented on backend/lib/edgehog/devices/hardware_type_part_number.ex
> +    type :hardware_type_part_number
```graphql
type HardwareTypePartNumber {
  id: ID!

  "The part number identifier."
  partNumber: String!

  hardwareType: HardwareType
}
```
Should `hardwareType` field be non-nullable?

2024-01-31 14:30 UTC, szakhlypa commented on backend/test/edgehog_web/schema/query/hardware_types_test.exs
> +            partNumber
Having option to query `hardwareType` field on `HardwareTypePartNumber` type, do we want to test nested queries? like
```graphql
          partNumbers {
            partNumber
            hardwareType {
              name
              handle
              partNumbers {
                partNumber
                hardwareType {
                  name
                  handle
                }
              }
            }
          }
```

2024-01-31 14:54 UTC, rbino commented on backend/lib/edgehog/devices/hardware_type.ex
> +      destroy :delete_hardware_type, :destroy
See above

2024-01-31 14:59 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/delete_hardware_type_test.exs
>            id
Minor, move to `ash-porting` issue

2024-01-31 15:00 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +    test "returns error for empty part_numbers", %{tenant: tenant, hardware_type: hardware_type} do
Minor, move to `ash-porting` issue

2024-01-31 15:00 UTC, rbino commented on backend/lib/edgehog/devices/hardware_type_part_number.ex
> +    type :hardware_type_part_number
See above

2024-01-31 15:01 UTC, rbino commented on backend/test/edgehog_web/schema/query/hardware_types_test.exs
> +            partNumber
We'll re-evaluate filters and sorts at the end of the porting process, please open a generic issue about this with the `ash-porting` label so that we have an item tracking this

2024-01-31 17:52 UTC, rbino commented on backend/lib/edgehog/devices/hardware_type_part_number.ex
> +    type :hardware_type_part_number
I've checked and currently `hardware_type_id` is actually nullable at the DB level (see [here](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/priv/repo/migrations/20211108144240_create_hardware_type_part_numbers.exs#L31)), so this is coherent with the status-quo.
The goal of the first step of the migration is having the resources reflect the current state of the database, then we can start adjusting the constraint with subsequent migrations.

2024-02-13 08:39 UTC, szakhlypa approved these changes

2024-02-13 08:39 UTC, merged