Port System Model to Ash
edgehog-device-manager/edgehog pull request #442
Opened 2024-02-08 14:48 UTC by rbino

Note that this is still missing descriptions (and their localization), but since they're not critical they will be handled in a second round (see #441).

2024-02-09 18:27 UTC, davidebriani requested changes

2024-02-09 18:27 UTC, davidebriani commented on backend/lib/edgehog/devices/system_model.ex
> +      end
I have a couple of doubts here:
1. What is the purpose of `Edgehog.Types.RelayId`?
2. Why using something related to Relay in a generic `action`?

2024-02-12 08:44 UTC, rbino commented on backend/lib/edgehog/devices/system_model.ex
> +      end
When I started working on this https://github.com/ash-project/ash_graphql/pull/109 was not merged so the `RelayId` type was also handling the translation between Relay and database IDs as a temporary workaround. 

Meanwhile that got merged, so in reality it makes no sense to call that `RelayId` so I'll change it to `Id`. We still need that because Ash kind of assumes that you use UUIDs as IDs, so the `:uuid` type gets exposed as `:id` at the GraphQL level, while the `:integer` type (which is what we use as ID) does not, the custom type basically just handles that.

2024-02-13 13:53 UTC, davidebriani approved these changes

2024-02-27 15:48 UTC, szakhlypa requested changes

2024-02-27 15:48 UTC, szakhlypa commented on backend/test/support/fixtures/devices_fixtures.ex
>    def system_model_fixture(opts \\ []) do
```suggestion
  def system_model_fixture(opts) do
```
We shouldn't define `[]` as the default value for `opts`, `opts` must be a non-empty keyword list with (at least) the `:tenant` key.

2024-02-27 15:48 UTC, szakhlypa commented on backend/lib/edgehog/devices/system_model/changes/handle_picture_upload.ex
> +    _ = Assets.delete_system_model_picture(system_model, picture_file)
Shouldn't we use `picture_url` to delete the uploaded picture?

2024-02-28 17:20 UTC, rbino commented on backend/test/support/fixtures/devices_fixtures.ex
>    def system_model_fixture(opts \\ []) do
The problem (and reason I'm providing `opts` with a default value) is that if you do that you get:
```
error: undefined function system_model_fixture/0 (expected Edgehog.BaseImagesTest to define such a function or for it to be imported, but none are available)
  test/edgehog/base_images_test.exs:35: Edgehog.BaseImagesTest.__ex_unit_setup_0_0/1
[...]
```
and other errors, because unfortunately even if tests are excluded with `--only`, they still all get compiled and an undefined function is a compilation error, and I don't want to fix all calling code in tests that are probably going to be removed anyway.

I plan on removing all default opts at the end of the porting.

2024-02-28 17:31 UTC, rbino commented on backend/lib/edgehog/devices/system_model/changes/handle_picture_upload.ex
> +    _ = Assets.delete_system_model_picture(system_model, picture_file)
Fixed, and since this was not caught by tests I've added two test cases covering this (i.e. image cleanup for failed create/update)

2024-03-05 15:42 UTC, szakhlypa requested changes

2024-03-05 15:42 UTC, szakhlypa commented on backend/lib/edgehog/devices/system_model/changes/handle_picture_upload.ex
> +  alias Edgehog.Devices.SystemModel
unused alias
```suggestion
```

2024-03-05 15:42 UTC, szakhlypa commented on backend/test/edgehog_web/schema/mutation/update_system_model_test.exs
> +
Maybe I'm missing something, I've tried to test the error response in case of `picture_file` uploading error with code below:
(also added expectation that `:delete` should not be invoked in this case)
```elixir
    test "returns error when fails to update picture_file", %{tenant: tenant, id: id} do
      Edgehog.Assets.SystemModelPictureMock
      |> expect(:upload, fn _, _ -> {:error, :no_space_left} end)
      |> expect(:delete, 0, fn _, _ -> :ok end)

      result =
        update_system_model_mutation(
          tenant: tenant,
          id: id,
          picture_file: %Plug.Upload{path: "/tmp/image.jpg", filename: "image.jpg"}
        )

      assert %{
        fields: [:picture_file],
        message: "failed to upload"
      } = extract_error!(result)
    end
```
But got in response `something_went_wrong`
```
%{
  fields: [],
  message: "Something went wrong. Unique error id: `0ad07194-8ee3-4d26-b5e1-8784e600e234`",
  code: "something_went_wrong",
  locations: [%{line: 2, column: 3}],
  path: ["updateSystemModel"],
  short_message: "Something went wrong.",
  vars: %{}
}
```

2024-03-11 16:35 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_system_model_test.exs
> +
This was actually a bug, the cleanup was tried even if the upload failure was the case of the failure and crashed on `apply_attributes` in `maybe_cleanup`.

I've refactored the code to only cleanup in case of successful uploads and added your test in the testsuite.

2024-03-13 09:08 UTC, szakhlypa approved these changes

2024-03-13 09:09 UTC, merged