Refactor device location fragment
edgehog-device-manager/edgehog pull request #443
Opened 2024-02-09 09:29 UTC by harisbikovic

This commit gets rid of relay/unused-fields lint warnings for the Device page.

2024-02-15 15:39 UTC, szakhlypa requested changes

2024-02-15 15:39 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +  fragment DeviceGroup_DeviceGroupFragment on DeviceGroup {
How does this fragment resolve the `relay/unused-fields` warning?

[Quote](https://relay.dev/docs/principles-and-architecture/thinking-in-relay) from the Relay documentation:
 `components use one or more GraphQL fragments to describe their data requirements. These fragments are then nested within other fragments, and ultimately within queries`.

My assumption is that the form component should have a relay fragment and that we should spread it into a query on the current page.

2024-02-27 09:36 UTC, szakhlypa requested changes

2024-02-27 09:36 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +      <Page.Header title={deviceGroupData.name} />
If the `name` field  of `DeviceGroup` GraphQL type has been removed from `GET_DEVICE_GROUP_QUERY`, where do we get the Device Group `name` to render in the header?
Unless you're planning to create a separate component for the Device Group header with its own fragment, I think we should fetch for `name` in the query (as we use query result in `DeviceGroupContent`).

2024-02-27 14:18 UTC, szakhlypa requested changes

2024-02-27 14:18 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +            deviceGroupRef={_.pick(deviceGroupData, [
Why do we need to pick data here? The `UpdateDeviceGroupForm` expects [fragment reference](https://relay.dev/docs/api-reference/use-fragment/#arguments) in the `deviceGroupRef` property

2024-02-27 15:26 UTC, harisbikovic commented on frontend/src/pages/DeviceGroup.tsx
> +      <Page.Header title={deviceGroupData.name} />
Is it the same for the `DeleteModal` where we need to pass `handle`, therefore we need to read it in the query too?

2024-02-27 16:14 UTC, szakhlypa requested changes

2024-02-27 16:14 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +  if (!deviceGroupData) {
`deviceGroupData` is always `true`, do you want to check on `deviceGroupData.deviceGroup`?

2024-02-27 16:18 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +      <Page.Header title={deviceGroupData.name} />
Yes, any Device Group data in `DeviceGroupContent` that you want to use/to pass by value should be fetched in the query.

Also with the current query and `const deviceGroupData = usePreloadedQuery(...`, the Device Group fields can be found in `deviceGroupData.deviceGroup?.<fieldName>` (e.g.  `name` -> `deviceGroupData.deviceGroup?.name`). We can change it to `const { deviceGroup } = usePreloadedQuery(...` since we are not using `deviceGroupData` directly.

2024-02-28 14:22 UTC, szakhlypa requested changes

2024-02-28 14:22 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +  //);
Don't you want to delete these lines?

2024-02-28 14:22 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +        <DevicesTable devicesRef={deviceGroup.devices || []} hideSearch />
`devices` is not nullable field, why do we need an empty array here?

2024-02-28 14:22 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> +            confirmText={deviceGroup.handle || ""}
`handle` is not nullable field, why do we need an empty string here?

2024-02-28 14:22 UTC, szakhlypa commented on frontend/src/forms/UpdateDeviceGroup.tsx
> +type DeviceGroupData = UpdateDeviceGroup_DeviceGroupFragment$data;
`UpdateDeviceGroup_DeviceGroupFragment$data` has ` $fragmentType` property, shouldn't it be omitted in `DeviceGroupData` type? I don't think we need fragment property in `useForm` and `onSubmit`.

2024-02-28 14:22 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
I think we should also update the `UPDATE_DEVICE_GROUP_MUTATION` to use `UpdateDeviceGroup_DeviceGroupFragment` in the selection set.

2024-02-29 14:27 UTC, szakhlypa requested changes

2024-02-29 14:27 UTC, szakhlypa commented on frontend/src/pages/DeviceGroup.tsx
> -        selector
Why do we remove `name` and `handle` fields from the selection when we use them on the current page?

2024-02-29 14:27 UTC, szakhlypa commented on frontend/src/forms/UpdateDeviceGroup.tsx
> +    id
How do you use `id` field of this fragment?

2024-04-16 13:57 UTC, szakhlypa approved these changes

2024-04-16 13:57 UTC, merged