Add GraphQL APIs to request forwarder sessions
edgehog-device-manager/edgehog pull request #455
Opened 2024-02-22 15:25 UTC by davidebriani

The PR implements:
- A `forwarderSession` GraphQL query that can be used by clients to inspect the status of a device → Forwarder session, and know whether the session is ready to be accessed and it is closed.
- A `requestForwarderSession` mutation to allow clients to request a device → Forwarder session for a specific deviceId.

To support the request of a forwarder session, the backend does the following:
- It checks whether the device is online. If not, an error is returned.
- It queries the existing forwarder sessions for the device.
  - If there is a session that is not :disconnected, i.e. it's either connected or re-connecting, then the backend returns the details about that session.
  - If there is no available session, it generates a new session token and sends a request to the device asking to establish that session. It then returns the details about that session.

With this approach, any existing forwarder sessions is reused whenever possible, and devices are not forced to establish a high number of simultaneous connections.

The backend assumes that there is a single instance of the [cloud Forwarder](https://github.com/edgehog-device-manager/edgehog_device_forwarder), and it expects to be configured with the host, port and protocol relative to forwarder's instance. The configuration is supplied through environment variables.

Closes #445, #446

2024-02-27 15:59 UTC, szakhlypa requested changes

2024-02-27 15:59 UTC, szakhlypa commented on backend/lib/edgehog/astarte/device/forwarder_session.ex
> +    data = %{session_token: session_token, host: forwarder_hostname, port: forwarder_port}
`ForwarderSessionRequest` interface was updated  with `/request/secure` endpoint

2024-02-27 16:56 UTC, davidebriani commented on backend/lib/edgehog/astarte/device/forwarder_session.ex
> +    data = %{session_token: session_token, host: forwarder_hostname, port: forwarder_port}
Nice catch, thanks. I added support for a `EDGEHOG_FORWARDER_SECURE_SESSIONS` boolean environment variable that define whether the sessions are requested as secure or not.

2024-02-28 11:24 UTC, rbino requested changes

2024-02-28 11:24 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +  defp fetch_forwarder_sessions(%Device{} = device) do
If you look at all the other functions above, they accept an `%AppEngine{}` client, not a `%Device{}`.

Keep the same convention by using `Devices.appengine_client_from_device/1` in the resolver (check out the [Astarte resolver](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog_web/resolvers/astarte.ex#L28) for the general pattern)

2024-02-28 11:24 UTC, rbino commented on backend/lib/edgehog/astarte.ex
> +      @forwarder_session_module.fetch_session_states(client, device.device_id)
Let's do `list_session_states` so the two function names jump a little more to the eye w.r.t. `fetch_session_states` and `fetch_session_state`

2024-02-28 11:30 UTC, szakhlypa requested changes

2024-02-28 12:31 UTC, davidebriani commented on backend/config/config.exs
> +
Yes, the configuration is actually used in the tests that verify the behaviour of the module itself, i.e. where the module is not mocked.

2024-02-28 12:32 UTC, davidebriani commented on backend/lib/edgehog/astarte.ex
> +  defp fetch_forwarder_sessions(%Device{} = device) do
Thanks, fixed

2024-02-28 12:32 UTC, davidebriani commented on backend/lib/edgehog/astarte.ex
> +      @forwarder_session_module.fetch_session_states(client, device.device_id)
Legit. I renamed the functions to `list_sessions` + `fetch_session`, and `list_forwarder_sessions` + `fetch_forwader_session`.

2024-02-28 12:33 UTC, davidebriani commented on backend/config/runtime.exs
> +    enabled?: Enum.all?([forwarder_hostname, forwarder_port, forwarder_secure_sessions?])
Nice catch! I fixed it

2024-03-05 08:59 UTC, rbino requested changes

2024-03-05 08:59 UTC, rbino commented on backend/config/runtime.exs
> +  forwarder_port = forwarder_port && String.to_integer(forwarder_port)
Should we default this to 443 give it will be the majority of the cases?

2024-03-05 08:59 UTC, rbino commented on backend/config/runtime.exs
> +  forwarder_hostname = System.get_env("EDGEHOG_FORWARDER_HOSTNAME")
We've been bitten by this in the past, so do a very simple check here: if it starts with `http`, raise an error detailing the fact that you must pass an hostname, not a URL

2024-03-05 08:59 UTC, rbino commented on doc/pages/admin/deploying_with_kubernetes.md
> +- `EDGEHOG-FORWARDER-HOSTNAME`: the host for the instance of [Edgehog Device Forwarder](https://github.com/edgehog-device-manager/edgehog_device_forwarder).
Also add details here to ensure users don't pass a URL instead of a host

2024-03-05 11:05 UTC, szakhlypa commented
Should the `:remote_terminal` capability be removed from the device capabilities list when `:edgehog_forwarder` is disabled?

E.g. device has required interfaces for `:remote_terminal` capability in introspection, but backend has unconfigured `EDGEHOG_FORWARDER_HOSTNAME`.

2024-03-05 11:18 UTC, davidebriani commented on doc/pages/admin/deploying_with_kubernetes.md
> +- `EDGEHOG-FORWARDER-HOSTNAME`: the host for the instance of [Edgehog Device Forwarder](https://github.com/edgehog-device-manager/edgehog_device_forwarder).
Updated

2024-03-05 11:19 UTC, davidebriani commented on backend/config/runtime.exs
> +  forwarder_hostname = System.get_env("EDGEHOG_FORWARDER_HOSTNAME")
Legit, I added the check

2024-03-05 11:20 UTC, davidebriani commented on backend/config/runtime.exs
> +  forwarder_port = forwarder_port && String.to_integer(forwarder_port)
I updated the code so that the port is inferred as 443 or 80 depending on the `EDGEHOG_FORWARDER_SECURE_SESSIONS` variable.
However if a `EDGEHOG_FORWARDER_PORT` is specified, it takes precedence.

2024-03-05 14:00 UTC, szakhlypa commented on backend/config/runtime.exs
> +    enabled?: Enum.all?([forwarder_hostname, forwarder_port])
Nitpicking: after recent changes, `EDGEHOG_FORWARDER_PORT` env variable is no longer required, `forwarder_port` will always have a valid value, so the `enabled?` value should only depend on `forwarder_hostname`

2024-03-05 17:58 UTC, davidebriani commented on backend/config/runtime.exs
> +    enabled?: Enum.all?([forwarder_hostname, forwarder_port])
Thanks, now `enabled?` is computed as `forwarder_hostname != nil`.

2024-03-11 17:06 UTC, rbino approved these changes

2024-03-12 10:37 UTC, szakhlypa approved these changes

2024-03-12 15:29 UTC, merged