Refactor update channel's info
edgehog-device-manager/edgehog pull request #463
Opened 2024-03-08 15:23 UTC by harisbikovic

Create GraphQL fragment for data into CreateUpdateChannel form and use it on UpdateChannelCreate page

2024-03-18 17:03 UTC, szakhlypa requested changes

2024-03-18 17:03 UTC, szakhlypa commented on frontend/src/pages/UpdateChannelCreate.tsx
>      deviceGroups {
Is there any reason to query the `deviceGroups` field  in `pages/UpdateChannelCreate.tsx`, when when it is only used in `forms/CreateUpdateChannel.tsx`?

2024-03-19 13:52 UTC, harisbikovic commented on frontend/src/pages/UpdateChannelCreate.tsx
>      deviceGroups {
Do you think that query should be transferred and used in  `forms/CreateUpdateChannel.tsx` instead? If not, what do you suggest?

2024-03-25 12:00 UTC, szakhlypa commented on frontend/src/pages/UpdateChannelCreate.tsx
>      deviceGroups {
I suggest you update `CREATE_UPDATE_CHANNEL_FRAGMENT` to query for the `deviceGroups` field `on RootQueryType` and use the fragment in `GET_DEVICE_GROUPS_QUERY`. You can also update component propetry name, like `targetGroupsRef` -> `createUpdateChannelRef`

2024-05-14 15:34 UTC, szakhlypa commented
Closing as superseded by #505

2024-05-14 15:34 UTC, closed without merging