Document the implemented support for Edgehog Device Forwarder
edgehog-device-manager/edgehog pull request #470
Opened 2024-03-18 16:52 UTC by davidebriani

Note down a summary of the implemented functionality in the changelog file, and expand the documentation page on deployments to describe how the [Device Forwarder](https://github.com/edgehog-device-manager/edgehog_device_forwarder) can be configured alongside Edgehog.

2024-03-20 12:02 UTC, rbino requested changes

2024-03-20 12:02 UTC, rbino commented on doc/pages/admin/deploying_with_kubernetes.md
> +    nginx.ingress.kubernetes.io/proxy-send-timeout: <CONNECTION-TIMEOUT>
Given we're not configuring the Forwarder timeout, I'd just put `120` here for both to minimize the _tl;dr_ factor (also given that right now there's only one good default and it's 120s)

2024-03-20 13:08 UTC, davidebriani commented on doc/pages/admin/deploying_with_kubernetes.md
> +    nginx.ingress.kubernetes.io/proxy-send-timeout: <CONNECTION-TIMEOUT>
> there's only one good default and it's 120s

I'm not sure about that. It could be 61s or 180s, only experience will tell.
The timeout value also has implications on connections to Edgehog's frontend and backend.
In addition, a high value might facilitate DoS attacks.

I agree about the TL;DR, although I would still note down the reason why we are messing with these timeouts somewhere.

2024-03-20 15:28 UTC, rbino commented on doc/pages/admin/deploying_with_kubernetes.md
> +    nginx.ingress.kubernetes.io/proxy-send-timeout: <CONNECTION-TIMEOUT>
works for me

2024-03-20 17:10 UTC, davidebriani commented on doc/pages/admin/deploying_with_kubernetes.md
> +    nginx.ingress.kubernetes.io/proxy-send-timeout: <CONNECTION-TIMEOUT>
Brilliant. I edited it so that it's more copy&paste-friendly while keeping the explanation on the succeeding notes.

2024-03-21 09:51 UTC, rbino requested changes

2024-03-21 09:51 UTC, rbino commented on doc/pages/admin/deploying_with_kubernetes.md
> +        image: edgehogdevicemanager/edgehog-device-forwarder:snapshot
Let's use `edgehog-device-forwarder:0.1.0` since it's there now

2024-03-21 10:03 UTC, davidebriani commented on doc/pages/admin/deploying_with_kubernetes.md
> +        image: edgehogdevicemanager/edgehog-device-forwarder:snapshot
Done

2024-03-21 10:04 UTC, rbino approved these changes

2024-03-21 10:05 UTC, merged