Port Device Tags features to Ash
edgehog-device-manager/edgehog pull request #482
Opened 2024-03-28 06:50 UTC by rbino

2024-04-02 10:41 UTC, davidebriani requested changes

2024-04-02 10:41 UTC, davidebriani commented on backend/lib/edgehog/labeling/tag.ex
> +    end
We will probably need some normalization on the `name` attribute so that `tag`, `Tag`, `TAG`, and `      TAG     ` result in the same tag `tag` being applied.

2024-04-02 10:41 UTC, davidebriani commented on backend/lib/edgehog/devices/device/device.ex
> +      # Move it there once it's fixed
It seems *someone* already fixed that and we can just update our Ash.GraphQL dependency.

2024-04-02 10:41 UTC, davidebriani commented on backend/lib/edgehog/devices/device/device.ex
> +      end
Does this respect the tenant that was set in the context or it will list all tags from all tenants?

2024-04-03 07:55 UTC, rbino commented on backend/lib/edgehog/devices/device/device.ex
> +      end
The tenant is inside the context, `context_to_opts` + passing those opts to `list` does exactly that job.

In fact, this should be enforced by Ash by returning an error if you don't pass a tenant (it is, for example, when using `Ash.read/1`), but I have to check because from a quick test it seems it's not enforced on aggregates.

Still, the code as is currently passes the tenant.

2024-04-03 07:58 UTC, rbino commented on backend/lib/edgehog/devices/device/device.ex
> +      end
Oh ok we just have to update, [someone](https://github.com/ash-project/ash/pull/952) has already fixed that :eyes:

2024-04-03 08:00 UTC, rbino commented on backend/lib/edgehog/labeling/device_tag.ex
> +    tenant_id_in_primary_key?: true
I think it already was here
https://github.com/edgehog-device-manager/edgehog/blob/main/backend/priv/repo/migrations/20220517063737_create_devices_tags.exs#L28

Anyway, at the end of the porting there will for sure be a pass to exactly match the tables from the current migrations with the ones generated by Ash; right now we're still not generating them from Ash but reusing the old ones but in the end we have to make sure they match so we can start to use Ash generators from that point onwards.

2024-04-03 13:10 UTC, szakhlypa commented on backend/lib/edgehog/labeling/tag/tag.ex
The `Tag` type in the latest GraphQL schema has a `tenant` field, is this intentional?

```graphql
type Tag {
  id: ID!
  name: String!
  tenant: TenantInfo!
}
```

2024-04-03 13:33 UTC, davidebriani commented on backend/lib/edgehog/labeling/tag/tag.ex
> +    attribute :name, :string, allow_nil?: false
Users might provide `        ` or an empty string as the tag, and they would end up persisted as an empty string tag, which doesn't seem so valuable. 
We might want to add `min_length: 1` here.

2024-04-03 13:33 UTC, davidebriani commented on backend/test/edgehog_web/schema/mutation/add_device_tags_test.exs
> +    end
Do we want to support normalizing the user input also when trying to remove tags?
For example, a user might first add a `FOO` tag and then try to remove the `FOO` tag: I fear that the tag won't be removed, since `FOO` will not match the persisted `foo` tag.

2024-04-03 13:33 UTC, davidebriani commented on backend/lib/edgehog/labeling/device_tag.ex
> +    tenant_id_in_primary_key?: true
It can actually make sense to have it in the primary key, since foreign keys that reference device tags should also match on the tenant_id anyways, to properly link multi-tenant resources.
Ok, let's review this whole topic at the end of the migration to Ash.

2024-04-04 14:42 UTC, davidebriani approved these changes

2024-04-04 14:42 UTC, merged