Port Device Groups to Ash
edgehog-device-manager/edgehog pull request #487
Opened 2024-04-03 16:27 UTC by rbino

2024-04-04 15:01 UTC, rbino commented on backend/lib/edgehog/groups/device_group/manual_relationships/devices.ex
> +    # We're doing N+1 queries here, but it's probably inevitable at this point
Note that we were doing N+1 queries also before. I might have an idea to maybe skip the N+1 here, but I'll think about that in a second pass.

2024-04-04 15:02 UTC, rbino commented on backend/lib/edgehog/groups/device_group/device_group.ex
> +    # TODO: custom type here
Left this for a second pass, the idea being parsing the selector on load instead of doing it inside the `devices` manual relationship

2024-04-05 10:15 UTC, davidebriani requested changes
The ported code is missing some functionalities, you might want to track them as TODOs:
- retrieving the groups of a device
- relationship of a group with the update channel

2024-04-05 10:15 UTC, davidebriani commented on backend/test/edgehog_web/schema/mutation/delete_device_group_test.exs
> +  @moduletag :ported_to_ash
We don't need to specify `@moduletag :ported_to_ash` twice for the same module.

2024-04-10 08:56 UTC, davidebriani approved these changes

2024-04-10 08:56 UTC, merged