Ash 3.0 update
edgehog-device-manager/edgehog pull request #488
Opened 2024-04-10 09:12 UTC by rbino

- Update Elixir and Erlang versions
- Update Ash and all Ash components to 3.0 compatible versions
- Rename Api to Domain
- Remove legacy breaking-change compatibility options
- Explicitly accept attributes in actions
- Mark all public attributes, calculations and relationships
- Add the context argument to module based validations and calculations
- Explicitly load relationship fields in calculations
- Change Ash.Calculation to Ash.Resource.Calculation
- Remove hide_fields almost everywhere, relying instead on the public? option
- Mark non atomic actions with require_atomic? false
- Remove unnecessary domain from cross-domain relationships
- Replace Ash.Query.expr with Ash.Expr.expr
- Implement Ash.ToTenant for the Tenant resource
- Replace calls to domain modules with calls to the Ash module
- Handle new nested errors in JSON API tests

2024-04-10 09:23 UTC, szakhlypa requested changes

2024-04-10 09:23 UTC, szakhlypa commented on .tool-versions
We should also update `backend/Dockerfile`

2024-04-10 10:43 UTC, davidebriani requested changes

2024-04-10 10:43 UTC, davidebriani commented on backend/lib/edgehog/devices/device/device.ex
>        attribute_writable? true
`attribute_writable? true` on `system_model_part_number` should not be needed, since when not set it will default to the relationship's `writable?` setting, which defaults to `true`.

2024-04-10 10:43 UTC, davidebriani commented on backend/lib/edgehog/devices/system_model_part_number.ex
> +    end
Since `create` and `update` now only accepts `[:part_number]`, how does the `system_model_id` get populated?
The same doubt stands for the HardwareTypePartNumber.

2024-04-10 13:48 UTC, rbino commented on backend/lib/edgehog/devices/system_model_part_number.ex
> +    end
That gets populated from the other using `manage_relationship` (see e.g. [here](https://github.com/edgehog-device-manager/edgehog/pull/488/files/2b31c47af1c6e07b59589a0fb8460369274073fb#diff-d891c3746b552f30751597445010d266903425bcebc4544bdbd5dd6206aa9709R99)) which is always able to modify the join attributes of the two resources

2024-04-10 14:44 UTC, szakhlypa commented on backend/lib/edgehog/astarte/realm/realm.ex
> +      public? true
Should [`sensitive? true`](https://hexdocs.pm/ash/dsl-ash-resource.html#attributes-attribute-sensitive?) be added as well?

2024-04-10 15:49 UTC, szakhlypa commented
new GraphQL schema adds few fields like
```graphql
type HardwareTypePartNumber {
  hardwareTypeId: Int
}
type SystemModelPartNumber {
  systemModelId: Int
  devices(sort: [DeviceSortInput], filter: DeviceFilterInput, limit: Int, offset: Int): [Device!]!
}
type SystemModel implements Node {
  hardwareTypeId: Int
}
type Device implements Node {
  systemModelPartNumber: SystemModelPartNumber
}
```
Is this intentional?

2024-04-10 15:51 UTC, szakhlypa commented
Do we want to have nullability on "relationships" fields even if we expect them to be not nullable?
```graphql
type SystemModel implements Node {
  hardwareType: HardwareType
}
```

2024-04-10 17:58 UTC, rbino commented
Regarding the first, what is exactly the difference w.r.t pre-3.0?

Regarding the second, it derives from the fact that not all relationships have `allow_nil? false`. This was already like this and will be fixed when we do the pass to make sure that the initial DB schema matches the existing one.

2024-04-10 19:38 UTC, szakhlypa commented
> Regarding the first, what is exactly the difference w.r.t pre-3.0?

There are new fields in GraphQL schema types (commit hash `442275c` -> `1f047b9`):
| Type  | new field | new field type | 
| ------------- | ------------- | ------------- |
| HardwareTypePartNumber  | hardwareTypeId  | Int |
| SystemModelPartNumber  | systemModelId  | Int |
| SystemModelPartNumber  | devices  | [Device!]! |
| SystemModel  | hardwareTypeId  | Int |
| Device  | systemModelPartNumber  | SystemModelPartNumber |



expanded example for `HardwareTypePartNumber` type below:

GraphQL schema pre (`442275c` commit's hash)
```graphql
type HardwareTypePartNumber {
  id: ID!
  partNumber: String!
  hardwareType: HardwareType
}
```

GraphQL schema after (`1f047b9` commit's hash)
```graphql
type HardwareTypePartNumber {
  id: ID!
  partNumber: String!
  hardwareTypeId: Int
  hardwareType: HardwareType
}
```
So the type `HardwareTypePartNumber` gets new field `hardwareTypeId` of type `Int`. Same for other fields from the table above.

2024-04-11 07:55 UTC, rbino commented
@szakhlypa fixed

2024-04-11 13:19 UTC, szakhlypa approved these changes

2024-04-11 13:20 UTC, merged