Port Base Images to sh
edgehog-device-manager/edgehog pull request #490
Opened 2024-04-12 09:35 UTC by davidebriani

2024-04-12 12:08 UTC, rbino requested changes
Some nitpicking but overall a very good start with Ash!

2024-04-12 12:08 UTC, rbino commented on backend/lib/edgehog/base_images/base_image/changes/handle_file_deletion.ex
> +    if file_url != nil do
`:url` is `allow_nil? false` so you can assume it's not nil and remove the conditional check

2024-04-12 12:08 UTC, rbino commented on backend/test/support/fixtures/base_images_fixtures.ex
> +    |> Mox.stub(:store, fn _, _ -> {:ok, file_url} end)
Instead of doing this you could have an alternative `create` action (e.g. `create :no_upload`) that accepts the `:file_url` and gets called by the fixture. This way you don't have to deal with Mox here (and leave the calling code "pure", as in no stubs implicitly defined)

2024-04-12 12:08 UTC, rbino commented on backend/test/edgehog_web/schema/query/base_image_test.exs
> +    |> expect(:delete, fn _ -> :ok end)
Same here, you can define a utility `destroy` action that you can use in tests without worrying about stubbing the storage

2024-04-15 15:54 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/create_base_image_collection_test.exs
> +      # TODO: wrong fields returned by AshGraphql
What is the upstream problem here?

2024-04-17 09:16 UTC, szakhlypa requested changes

2024-04-17 13:33 UTC, davidebriani commented on backend/lib/edgehog/base_images/base_image_collection/base_image_collection.ex
You're right, I kept just the single file without the wrapping folder for now.

2024-04-18 14:47 UTC, merged