Port Device Trigger handling to Ash
edgehog-device-manager/edgehog pull request #491
Opened 2024-04-12 09:51 UTC by rbino

2024-04-12 10:07 UTC, rbino commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +  describe "process_event for device events" do
Note that _before_ changing all tests I've verified the old ones passed (apart from the changed error codes), to make sure that we're still compatible with the existing triggers

2024-04-15 07:30 UTC, szakhlypa requested changes

2024-04-15 10:56 UTC, davidebriani requested changes

2024-04-15 10:56 UTC, davidebriani commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +    with {:ok, realm} <- Realm.fetch_by_name(realm_name, query: read_query) do
If I am not mistaken, different Edgehog tenants could have Astarte realms with the same name.
Instead of fetching the realm only by name and load the tenant as a realm's association, we could instead identify *both* the correct realm and tenant beforehand, thanks to the route params of the API that handles incoming triggers (`/tenants/:tenant_slug/triggers`) and the `Astarte-Realm` HTTP header of the request. The tenant can then be pushed downstream to the database queries.

2024-04-15 10:56 UTC, davidebriani commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +          last_disconnection: utc_now_second() |> DateTime.add(-50, :minute),
Nitpicking: the device is not online, but it has a `last_connection` more recent than `last_disconnection`.

2024-04-15 10:56 UTC, davidebriani commented on backend/lib/edgehog/devices/device/device.ex
> +      change Changes.InitializeFromDeviceStatus
Why the comment says that the change is only run when the resource is created? How does that happen?

2024-04-15 11:06 UTC, davidebriani commented on backend/lib/edgehog_web/controllers/trigger_controller.ex
> +    # than a 500 does not do much good.
For instance, we could produce an evident log when the realm does not exist, and return a 404 or 400 error.

2024-04-15 12:25 UTC, rbino commented on backend/lib/edgehog_web/controllers/trigger_controller.ex
> +    # than a 500 does not do much good.
True that, I took a shortcut and conflated the two things because even implementing [`Plug.Exception`](https://hexdocs.pm/phoenix/custom_error_pages.html#custom-exceptions) the exception is not written to the log if it has an error in the 4xx range. In this case it's better to restore the Fallback controller and handle the error handling/logging there.

2024-04-15 12:41 UTC, rbino commented on backend/lib/edgehog/devices/device/changes/initialize_from_device_status.ex
> +  end
The current implementation is coherent with the [old implementation](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/astarte.ex#L439): the device was created if not existing, retrieving the initial info from Astarte, and _then_ it was updated with the event, so the event changes were winning.

Here we do things differently due to the fact that we're able to do an atomic change (i.e. before we were doing two DB calls, read and then update, for each event, here we do a single one), so we actually retrieve the info from Astarte _after_ we upsert the device, only if some fields are `nil` (otherwise we would do an API call each time there's an event).

All that said, your observation makes sense, theoretically your corner case would be rectified just afterwards since we should receive a `device_disconnected` event, but given we have the info we should consider `Astarte` to be the authority here, I'll change it

2024-04-15 13:23 UTC, davidebriani commented on backend/lib/edgehog/devices/device/device.ex
> +      change Changes.InitializeFromDeviceStatus
II agree with making things more explicit as possible, comments included since as stated right now the comment is not clear.

For instance, in the future we might have some automatic mechanism that creates devices on Edgehog if they exist on Astarte: so a device registered in Astarte would appear in Edgehog even though it never connected yet. Implementing such a feature would subtly change the logic here, where we made the assumption that a created device does not have `nil` fields.

2024-04-15 16:38 UTC, davidebriani approved these changes

2024-04-18 15:35 UTC, davidebriani approved these changes

2024-04-18 15:35 UTC, merged