Port Geolocation functionalities to Ash
edgehog-device-manager/edgehog pull request #511
Opened 2024-05-02 16:45 UTC by davidebriani

The PR adds a `location` calculation field on the Device resource, which is computed thanks to the business logic contained in the Geolocation context.

2024-05-06 14:41 UTC, rbino requested changes

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/astarte/device/geolocation/sensor_position.ex
> +# Copyright 2022-24 SECO Mind Srl
Typo, should be the full year

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +         {:ok, device} <- Ash.load(device, [:sensor_positions], tenant: device.tenant),
Shouldn't you be able to do both of these in a single load?

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +         {:ok, device} <- Ash.load(device, [:sensor_positions], tenant: device.tenant),
Also, I'd use `reuse_values?: true` for this kind of loads, otherwise `load!` re-reads from the database everytime (see motivation [here](https://hexdocs.pm/ash/3.0.0-rc.45/upgrading-to-3-0.html#calculations-do-not-reuse-values-by-default), which shouldn't be relevant in our case).
I'll open an issue to check this in the existing codebase, but let's try to do the correct thing for new code.

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +# Copyright 2022-24 SECO Mind Srl
Full year

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +          {:ok, location} -> location
`{:ok, address} -> address`

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +      device_location = %DeviceLocation{
Internal note to be considered before the release: right now we always do both Geolocation and Geocoding. Given we can now easily make calculations depend upon each other, it might be smart to split the two values also at the API level. This way you can ask for Geolocation only (and not "pay" for an API call to the Geocoding provider) or you can ask for the address (which will depend on Geolocation)

2024-05-06 14:41 UTC, rbino commented on backend/lib/edgehog/devices/device/types/device_location.ex
> +defmodule Edgehog.Devices.Device.Types.DeviceLocation do
Given this is a (embedded) resource I'd move it out of `Types` (which I've created to store `Ash.Type`s, and tbh I probably will rollback)

2024-05-06 14:53 UTC, davidebriani commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +          {:ok, location} -> location
Here I am being consistent with the Geocoding providers where `reverse_geocode` returns a `Edgehog.Geolocation.Location`.
Right now `Edgehog.Geolocation.Location` is just a `String.t()`, but it would be nice in the future to expose a structured location instead of a formatted address.

If you feel this overcomplicates things and we should just call all of them *formatted_address*, let me know.

2024-05-06 14:56 UTC, rbino commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +          {:ok, location} -> location
It just feels strange that something that gets assigned to an `address` variable and the to an `address` field in a struct is internally called `location` (which is always in turn the name given to the whole struct when is returned). It felt like a copy-paste error tbh, I'd keep the naming consistent throughout.

2024-05-06 14:58 UTC, davidebriani commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +         {:ok, device} <- Ash.load(device, [:sensor_positions], tenant: device.tenant),
The fact is that I need the tenant fist in order to set the `tenant` option in the second `Ash.load`.
If I don't set the tenant option, Ash will complain about the option not being set.

If agree this is not ideal.
Another solution would be to accept a `tenant` argument besides the input `device`: `geolocate(tenant, device)`.
Howvever that feels odd: the `device` should be enough, and why allowing to pass a tenant that is potentially different from the one of the device?

Do you have any insights here?

2024-05-06 15:10 UTC, davidebriani commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +      device_location = %DeviceLocation{
I had the same thought and it makes sense to me.
That's why I clearly separated the two concerns in the Geolocation context, although I kept the previouus GraphQL API on the outside.

I will experiment with defining two separate calculations to see if we like the APIs.
It could be something like:

```graphql
device {
  position {
    latitude
    longitude
    accuracy
    altitude
    altitudeAccuracy
    heading
    speed
    timestamp
  }
  location {
    formattedAddress
    timestamp
  }
}
```

where in the future we could expand the Location type to also hold the address parts (ZIP code, state, region, city, etc.).

2024-05-06 15:19 UTC, rbino commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +         {:ok, device} <- Ash.load(device, [:sensor_positions], tenant: device.tenant),
That does seem strange since `Ash.load/3` should [pick up the tenant from the record](https://github.com/ash-project/ash/blob/main/lib/ash.ex#L1680). Do you have a stack trace of how Ash complains?

2024-05-06 15:26 UTC, rbino commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +      device_location = %DeviceLocation{
Might be a good occasion to maybe incorporate https://github.com/edgehog-device-manager/edgehog/issues/270?

2024-05-07 10:25 UTC, davidebriani commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +         {:ok, device} <- Ash.load(device, [:sensor_positions], tenant: device.tenant),
The error is
```
{:error,
 %Ash.Error.Invalid{
   path: [:realm], 
   query: "#Query<>", 
   errors: [
     %Ash.Error.Invalid.TenantRequired{
       resource: Edgehog.Astarte.Realm,
       splode: Ash.Error,
       bread_crumbs: [],
       vars: [],
       path: [:realm],
       stacktrace: #Splode.Stacktrace<>,
       class: :invalid
     }
   ]
 }}
```

The device does not have a tenant set.
So that's why I first have to load it with `Ash.load(device, :tenant)`.
However note that I must also set the tenant explicitly in `Ash.load(device, [:sensor_positions], tenant: device.tenant)`, since the device has now a populated `device.tenant` but `device.__metadata__.tenant` is still `nil`: and `Ash.load/3` seems to read from __metadata__ if you don't specify any option.

2024-05-08 10:06 UTC, davidebriani commented on backend/lib/edgehog/astarte/device/geolocation/sensor_position.ex
> +# Copyright 2022-24 SECO Mind Srl
Fixed

2024-05-08 10:06 UTC, davidebriani commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +# Copyright 2022-24 SECO Mind Srl
Fixed

2024-05-08 10:10 UTC, davidebriani commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +          {:ok, location} -> location
This isn't relevant anymore, since I clearly separated a Position struct, which contains GPS coordinates, from a Location struct, which contains a formatted address.

2024-05-08 10:11 UTC, davidebriani commented on backend/lib/edgehog/devices/device/calculations/device_location.ex
> +      device_location = %DeviceLocation{
I separated a Position struct, which contains GPS coordinates, from a Location struct, which contains a formatted address.
I added a `source` field on both structs that can contain details about how the fields are estimated, as suggested by #270

2024-05-08 10:11 UTC, davidebriani commented on backend/lib/edgehog/devices/device/types/device_location.ex
> +defmodule Edgehog.Devices.Device.Types.DeviceLocation do
Fixed

2024-05-08 10:11 UTC, davidebriani commented on backend/lib/edgehog/geolocation/providers/device_geolocation.ex
> +         {:ok, device} <- Ash.load(device, [:sensor_positions], tenant: device.tenant),
Basically, for some reason, the calculation provides a list of records that do not have the `tenant` set in `__metadata__`.
We can either try to dig deeper into Ash, or fix it later if we don't come up with a good solution right away.

2024-05-09 15:53 UTC, rbino requested changes

2024-05-09 15:53 UTC, rbino commented on backend/lib/edgehog/devices/device/calculations/location.ex
> +      end
Not a fan of the fact that `if` without `else` implicitly return `nil`.

I'd do:
```elixir
Enum.map(devices, &(get_location(&1.position))

defp get_location(nil), do: nil

# ...
```

2024-05-09 20:30 UTC, davidebriani commented on backend/lib/edgehog/devices/device/calculations/location.ex
> +      end
Not a fan of accepting `nil` as function arguments, but the implicit `nil` for the missing `else` case definitely stinks more, I agree.
It's fixed.

2024-05-10 10:00 UTC, merged