Port Update Channels to Ash
edgehog-device-manager/edgehog pull request #521
Opened 2024-05-20 17:00 UTC by davidebriani

2024-05-21 12:12 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel/changes/relate_target_groups.ex
> +      {:ok, update_channel}
Possible idea (let's open an issue to iterate on this since it's not critical and I don't want this to become a blocker).

Here you're filtering on `is_nil(update_channel)` and then setting the update channel. If the length of records is less then what you expect, then you know some of the target groups already had an update channel.

This works fine but this way you can't say _which_ target groups failed. My idea is that you could use `if` _inside_ an atomic update expression (see [here](https://elixirforum.com/t/conditions-on-atomic-changes/61200/6))

```elixir
atomic_update(:update_channel_id, if is_nil(update_channel_id) do
  # This is the one you're passing
  ^update_channel_id
else
  # This is the existing one
  update_channel_id
end)
```

and then on the returned records you can check if all of them have the correct `update_channel_ids`. If some of them don't, you can indicate to the caller _which_ ones.

2024-05-21 12:32 UTC, rbino requested changes

2024-05-21 12:32 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel/update_channel.ex
> +      list :update_channels, :list
Let's not do this on new resources, this is something I did initially to have different descriptions for the two queries, but now the description can be passed [inline](https://hexdocs.pm/ash_graphql/dsl-ashgraphql-resource.html#graphql-queries-get-description), and `get? true` doesn't really have any effect on GraphQL, so we should just use the default read for both.

Note that the default read paginates by default, so you have to pass `paginate_with: nil` to the `list` query until we handle pagination project-wide.

```elixir
queries do
  get :update_channel, :read do
    description "blabla"
  end
  
  list :update_channels, :list do
    description "blablab"
    paginate_with nil
  end
end

# ...
actions do
  defaults [:read]
end
```

2024-05-21 12:32 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel/update_channel.ex
> +      list :update_channels, :list
I've also opened an issue to track this for existing resources

2024-05-21 12:35 UTC, rbino requested changes

2024-05-21 12:35 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel/update_channel.ex
> +      public? true
This is public so it should be exposed on GraphQL. Is this tested somewhere? I'd add a test in `update_channel_test.exs`, with a custom document to just return updatable devices

2024-05-21 12:40 UTC, rbino requested changes

2024-05-21 12:40 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_channel/calculations/updatable_devices.ex
> +    |> Ash.load!(target_groups: [devices: :system_model])
Why are you not filtering at the database level?

```elixir
devices_query =
  Device
  |> Ash.Query.filter(device_id == ^system_model_id)
  
update_channels
|> Ash.load!(target_groups: [devices: devices_query])
# ...
```

I _think_ this should work because the `Devices` ManualRelationship in Groups [considers the load query](https://github.com/edgehog-device-manager/edgehog/blob/from-ash-we-rise/backend/lib/edgehog/groups/device_group/manual_relationships/devices.ex#L33) and then [applies additional filters](https://github.com/edgehog-device-manager/edgehog/blob/from-ash-we-rise/backend/lib/edgehog/groups/device_group/manual_relationships/devices.ex#L44) on top of it

2024-05-23 16:42 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_channel/calculations/updatable_devices.ex
> +    |> Ash.load!(target_groups: [devices: :system_model])
Good point.
Ash complains about `Edgehog.Devices.Device.system_model is not filterable`.
So I would need to dig deeper into why that happens.

2024-05-23 16:46 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_channel/update_channel.ex
> +      public? true
Nice catch.
I added the tests to the PR.
But I also made the field private: it would be better to expose device lists with pagination, so I am still not sure that a calculation is the best way to compute this field, a custom read action might be more appropriate. I'll leave to our future selves to figure out if we really need to expose this info in the first place.

2024-05-24 09:00 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_channel/update_channel.ex
> +      list :update_channels, :list
Very true.
My only concern is that by adding the documentation on GraphQL queries I would also have to add documentation to other APIs / code interfaces, while I could add the documentation just once directly on actions.

2024-05-24 10:21 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_channel/changes/relate_target_groups.ex
> +      {:ok, update_channel}
This is the draft I ended up with, which is still not working.
We can carry on with the current implementation and maybe review this approach in the future.

```elixir
  defp relate_target_groups(tenant, update_channel, target_group_ids) do
    update_channel_id = update_channel.id

    update_expr =
      Ash.Expr.expr(
        if is_nil(update_channel_id) do
          # This is the one you're passing
          ^update_channel_id
        else
          # This is the existing one
          update_channel_id
        end
      )

    %Ash.BulkResult{status: status, records: records} =
      DeviceGroup
      |> Ash.Query.filter(id in ^target_group_ids)
      |> Ash.Query.set_tenant(tenant)
      |> Ash.bulk_update(:update_update_channel, %{},
        atomic_update: %{update_channel_id: update_expr},
        return_records?: true
      )

    group_ids_with_preexisting_channel =
      records
      |> Enum.filter(&(&1.update_channel_id != update_channel_id))
      |> Enum.map(& &1.id)

    group_ids_not_found =
      Enum.filter(target_group_ids, fn id -> not Enum.any?(records, &(&1.id != id)) end)

    cond do
      not Enum.empty?(group_ids_not_found) ->
        {:error,
         Ash.Error.Changes.InvalidArgument.exception(
           field: :target_group_ids,
           message: "some target groups were not found: #{inspect(group_ids_not_found)}"
         )}

      not Enum.empty?(group_ids_with_preexisting_channel) ->
        {:error,
         Ash.Error.Changes.InvalidArgument.exception(
           field: :target_group_ids,
           message:
             "some target groups are already associated with an update channel: #{inspect(group_ids_with_preexisting_channel)}"
         )}

      status != :success or length(records) != length(target_group_ids) ->
        {:error,
         Ash.Error.Changes.InvalidArgument.exception(
           field: :target_group_ids,
           message: "is invalid"
         )}

      true ->
        {:ok, update_channel}
    end
  end
```

2024-05-24 11:17 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_channel/update_channel.ex
> +      list :update_channels, :list
As discussed in person, it's better to maintain a single `:read` action so that if we need to support low-level functionalities we would need to only implement them once.

I updated the queries as you suggested.

2024-05-27 07:44 UTC, rbino requested changes

2024-05-27 07:44 UTC, rbino commented on backend/test/support/fixtures/devices_fixtures.ex
> +    {base_image_id, opts} = Keyword.pop!(opts, :base_image_id)
This was changed but it doesn't get used anywhere, maybe it's from the next PR? I'd like to see it in context to check the reason for the change

2024-05-27 08:27 UTC, davidebriani commented on backend/test/support/fixtures/devices_fixtures.ex
> +    {base_image_id, opts} = Keyword.pop!(opts, :base_image_id)
I agree, although the fixture is already being used for this PR in [`backend/test/edgehog/update_campaigns/update_channel_test.exs`](https://github.com/edgehog-device-manager/edgehog/blob/3f7296c8fb182c51b04b66965e139071a98a530d/backend/test/edgehog/update_campaigns/update_channel_test.exs#L53).

2024-05-27 08:29 UTC, rbino commented on backend/test/support/fixtures/devices_fixtures.ex
> +    {base_image_id, opts} = Keyword.pop!(opts, :base_image_id)
Missed that, good to go

2024-05-27 09:06 UTC, merged