Port Update Campaigns to Ash
edgehog-device-manager/edgehog pull request #530
Opened 2024-05-27 12:55 UTC by davidebriani

Closes #343

2024-05-30 08:06 UTC, szakhlypa requested changes

2024-05-30 10:34 UTC, rbino requested changes
Great (and massive) work.
The main comments have been on using more semantic actions instead of manually using `Ash.Query` etc in the `Core` module.
We don't have to do everything now, I'd go for the low hanging fruits and then iterate. The idea is that if we can encode stuff in the action, the action can then become a code interface, so the endgame would be calling `UpdateCampaigns.increase_retry_count_for_target(target, tenant: tenant)`.

So let's try to do step 1 towards that (which is trying to keep semantics inside actions) and see where we go from there.

2024-05-30 10:34 UTC, rbino commented on backend/lib/edgehog/update_campaigns/rollout_mechanism/push_rollout/core.ex
> +    Ash.update!(target, %{retry_count: target.retry_count + 1})
```elixir
Ash.update!(target, action: :increase_retry_count)
```
i.e. let's have specific update actions that more or less map to the various updates we do from Core. In some cases (like this one) you don't even need attributes and you can make them atomic by increasing the retry count at the database level with `atomic_update` (which shouldn't be a problem in our case since only a single process updates the target at a time, but why not)

2024-05-30 10:34 UTC, rbino commented on backend/lib/edgehog/update_campaigns/rollout_mechanism/push_rollout/executor.ex
> +        Core.subscribe_to_ota_operation_updates!(pending_target.ota_operation.id)
It's the same, but `target` should still have an `ota_operation_id` attribute (generated from the relationship)

2024-05-30 10:34 UTC, rbino commented on backend/test/edgehog/update_campaigns/resumer/core_test.exs
> +      tenant = tenant_fixture()
Nit: maybe just put the tenant creation in the setup

2024-05-30 10:34 UTC, rbino commented on backend/lib/edgehog/update_campaigns/executor_supervisor.ex
> +      Ash.load!(update_campaign, [:id, :rollout_mechanism, :tenant_id], reuse_values?: true)
This should be fixed by the dedicated action (see other comment), but I'd expect `:id` and `:tenant_id` to always be loaded since they are attributes

2024-05-30 10:34 UTC, rbino commented on backend/lib/edgehog/update_campaigns/rollout_mechanism/push_rollout/push_rollout.ex
> +    end
While we're changing this, let's deal with #343 (those defaults should be already pushed from the frontend IIRC)

2024-05-30 10:36 UTC, rbino commented
@davidebriani given I think we've now touched all available fixtures, check if #267 can be considered closed and if so add it to the "Closes" list of your PR

2024-05-31 10:58 UTC, davidebriani commented on backend/lib/edgehog/os_management/ota_operation/ota_operation.ex
> +      require_atomic? false
Because Ash

> cannot atomically run a changeset with an after_transaction hook

At least that's the error I'm getting if I don't specify `require_atomic? false`.

2024-05-31 12:53 UTC, davidebriani commented
Issue #267 is almost done, but a few more changes are required and it's better to include them in a separate PR.

2024-05-31 13:07 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/rollout_mechanism/push_rollout/core.ex
> +    target = Ash.load!(target, :ota_operation)
Right!
Although I would also need to specify the tenant:

```elixir
OTAOperation
|> Ash.get!(target.ota_operation_id, tenant: target.tenant_id)
|> OSManagement.send_update_request()
```

So I am trying this version to make Ash respect the tenant automatically:
```elixir
target
|> Ash.load!(:ota_operation)
|> Map.fetch!(:ota_operation)
|> OSManagement.send_update_request()
```

Another option would be the following, although I find it less readable:
```elixir
target
|> Ash.load!(:ota_operation)
|> then(& OSManagement.send_update_request(&1.ota_operation))
```

2024-05-31 16:48 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/rollout_mechanism/push_rollout/core.ex
> +  end
There is now a single place where I need to fetch the base image from an update campaign's id.
So I just manually loaded the relationship instead of defining a `for_rollout` read action, which didn't suit my case properly anymore.

2024-06-06 10:32 UTC, rbino requested changes

2024-06-06 10:32 UTC, rbino commented on backend/lib/edgehog/update_campaigns/update_campaign/update_campaign.ex
> +      change set_new_attribute(:start_timestamp, &DateTime.utc_now/0)
```elixir
argument :start_timestamp, :utc_datetime_usec do
  default &DateTime.utc_now/0
end
change set_attribute(:start_timestamp, arg(:start_timestamp))
```

2024-06-06 10:35 UTC, davidebriani commented on backend/lib/edgehog/update_campaigns/update_campaign/update_campaign.ex
> +      change set_new_attribute(:start_timestamp, &DateTime.utc_now/0)
Fixed, thanks

2024-06-06 11:24 UTC, rbino approved these changes

2024-06-06 11:24 UTC, merged