Port tests on OTA operations to Ash
edgehog-device-manager/edgehog pull request #537
Opened 2024-06-11 08:46 UTC by davidebriani

The PR converts the old tests that were run on the function of the OSManagement context and run them on the available Ash actions.

It also adds a missing piece of logic on OTA operations before porting the relative tests: cleaning up the ephemeral image of manual OTA operation once they reach a terminal status and the rollout is ended.

2024-06-11 12:14 UTC, Pavinati commented on backend/test/edgehog/os_management_test.exs
> +      |> expect(:update, fn _client, ^device_id, ^ota_operation_id, ^base_image_url ->
here we're testing against a specific OTA operation ID and base image URL, i would expect those components to be parts of the test itself instead of relying to external initialization
```elixir
ota_operation = manual_ota_operation_fixture(tenant: tenant,
  device_id: "mspcBscfW7KaYjpy7GAO7A",
  operation_id: "some-id",
  base_image_url: "some-url"
)

Edgehog.Astarte.Device.OTARequestV1Mock
|> expect(:update, fn _client, "mspcBscfW7KaYjpy7GAO7A", "some-id", "some-url" -> ... end)
```

2024-06-17 09:29 UTC, davidebriani commented on backend/test/edgehog/os_management_test.exs
> +      |> expect(:update, fn _client, ^device_id, ^ota_operation_id, ^base_image_url ->
Sounds right, I moved the setup for the OTA operation within the test.
Actually, there's no ota operation in the `setup` block anymore: each test creates one when needed.

2024-06-17 09:33 UTC, Pavinati approved these changes

2024-06-17 11:38 UTC, szakhlypa requested changes

2024-06-18 09:21 UTC, davidebriani commented on backend/lib/edgehog/os_management/ota_operation/changes/handle_ephemeral_image_deletion.ex
> +    Ash.Changeset.after_action(changeset, &cleanup_base_image_url/2)
It makes sense, I changed it to `after_transaction/3`.

2024-06-20 17:12 UTC, merged