Clear the warnings contained in the test files
edgehog-device-manager/edgehog pull request #561
Opened 2024-07-05 13:40 UTC by safeta87

Removed unused imports, variables, functions and
aliases

2024-07-05 14:08 UTC, rbino requested changes

2024-07-05 14:08 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_base_image_test.exs
> +      base_image: _base_image,
If variables from the context are not used just remove them from the match entirely

2024-07-05 14:08 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_device_group_test.exs
> +      device_group: _device_group,
See above

2024-07-05 14:08 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +      hardware_type: _hardware_type,
See above

2024-07-05 14:08 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +      hardware_type: _hardware_type,
Etc

2024-07-05 14:08 UTC, rbino commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +      _fixture = hardware_type_fixture(tenant: tenant, part_numbers: ["A", "B", "C"])
You can remove the assignment, we're just interested in creating a fixture here, without the need of holding a reference to it

2024-07-05 14:08 UTC, rbino commented on backend/test/edgehog_web/schema/query/system_models_test.exs
> +    _sort = opts[:sort]
Just remove both since they're not used

2024-07-05 14:09 UTC, Pavinati requested changes

2024-07-05 14:09 UTC, Pavinati commented on backend/test/edgehog_web/schema/mutation/update_base_image_test.exs
> +      base_image: _base_image,
this row can be removed entirely

2024-07-05 14:09 UTC, Pavinati commented on backend/test/edgehog_web/schema/mutation/update_device_group_test.exs
> +      device_group: _device_group,
same here

2024-07-05 14:09 UTC, Pavinati commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +      hardware_type: _hardware_type,
and here

2024-07-05 14:09 UTC, Pavinati commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +      hardware_type: _hardware_type,
and here

2024-07-05 14:09 UTC, Pavinati commented on backend/test/edgehog_web/schema/mutation/update_hardware_type_test.exs
> +      hardware_type: _hardware_type,
and other matches perfomed directly on `test " ... "`

2024-07-08 07:22 UTC, rbino approved these changes

2024-07-08 07:30 UTC, merged