Support redirection to a specific page
edgehog-device-manager/edgehog pull request #585
Opened 2024-08-14 13:08 UTC by Emina-M

Support redirection to a specific page after successful authentication. For example, if the user requested `Update Campaigns` page in the url, instead of going to `Devices` page after authentication, go to `Update Campaigns`.

2024-08-14 14:15 UTC, Pavinati requested changes

2024-08-14 14:15 UTC, Pavinati commented on frontend/src/contexts/Auth.tsx
> +    sameSite: "none",
This doesn't feel related to this PR

2024-08-14 14:15 UTC, Pavinati commented on frontend/src/Router.tsx
> +  Copyright 2021-2023 SECO Mind Srl
newly created components should report the year of their creation

2024-08-14 14:15 UTC, Pavinati commented on frontend/src/Router.tsx
> +}): React.ReactElement | undefined => {
This file adds a lot of noise to the PR, just to accept a single `redirectTo` parameter.
We could just define this component inside the `App.tsx` file, keeping the diff nice and clean

2024-08-14 15:03 UTC, Pavinati requested changes

2024-08-14 15:03 UTC, Pavinati commented on frontend/src/App.tsx
> +};
We don't even need this component. We can leave everything as it was in `App`, and just `navigate` if the user completed the login.

```javascript
      auth.login(authConfig, false).then((isValidLogin) => {
        setAttemptingLogin(false);
        if (isValidLogin) {
          navigate(redirectTo)
        }
      });
```

2024-08-19 09:29 UTC, Pavinati approved these changes

2024-08-21 10:47 UTC, davidebriani requested changes

2024-08-21 10:47 UTC, davidebriani commented on frontend/src/App.tsx
> +  const redirectTo = searchParams.get("redirectTo") || "";
Adding the logic in the `App.tsx` file means that I can use any URL to attempt the login, it just has to include the needed search params.
For instance `localhost:3000/hardware-types?tenantSlug=<tenant-slug>&authToken=<auth-token>` works, but it will first try to load the page of the Hardware Types, even tough it will not be displayed to the user after the login attempt: either the Devices or the Login page will be shown depending on whether the login was successful.
In addition, we could avoid always reading the search params: e.g. even when they are used because the user is simply navigating throughout the app.

We could use a dedicated route and page for this logic. Let's say we have:
- a `/try-login` route that correspond to a TryLogin page. This route should always be available, regardless of the user already being authenticated or not: i.e. both `publicRoutes` and `authenticatedRoutes`.
- the TryLogin page reads the search params and attempts the login. It redirects to `"/"` in case of failure, or it redirects to the `redirectTo` param in case of success.
- besides this logic, the TryLogin just renders a loading spinner (instead of displaying it from the App file).

cc @Pavinati

2024-08-21 10:47 UTC, davidebriani commented on frontend/src/App.tsx
> +          navigate(redirectTo);
When navigating to a different route, it would be better to replace the current route with the new one in the browser's history instead of just adding the new route to the browser's history.
The reason is that if the user pushed the Back button of the browser to go back in history, it would reach again this route where the login is attempted and the user is automatically redirected to a new route. So the user wouldn't be able to go back in history, always being redirected to the latest page.

```suggestion
          navigate(redirectTo, { replace: true });
```

2024-08-21 10:54 UTC, davidebriani commented on frontend/src/App.tsx
> +  const redirectTo = searchParams.get("redirectTo") || "";
Of course, I have no strong opinion, `/auth` is fine.

2024-09-09 10:22 UTC, Pavinati approved these changes

2024-09-09 10:23 UTC, davidebriani approved these changes

2024-09-09 10:23 UTC, merged