Add descriptions to fields of the GraphQL schema
edgehog-device-manager/edgehog pull request #60
Opened 2021-11-19 14:49 UTC by davidebriani

Add @desc annotations to document the meaning and purpose of fields in the GraphQL schema.

2021-11-22 11:52 UTC, Pavinati commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    @desc "A string to match against the part number of the device's appliance model. The match is case-insensitive and tests whether the string is included in the part number of the device's applian
Those lines are pretty long. Is there a way to split the desc code in multiple lines without changing the resulting doc string?

2021-11-22 15:10 UTC, rbino requested changes

2021-11-22 15:10 UTC, rbino commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +        """
Missing `@desc`?

2021-11-22 15:10 UTC, rbino commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +        """
Missing `@desc`?

2021-11-22 15:10 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    @desc "A string to match against the part number of the device's appliance model. The match is case-insensitive and tests whether the string is included in the part number of the device's applian
It's possible to do something like
```
@desc "A long string " <>
  "on multiple " <>
  "lines"
```
but it becomes ugly quickly: it's a mess to maintain if you have to add something to a line, you have to remember the spaces at the end of the line etc.

Imho we either accept the long lines or use heredocs (accepting the newlines in the resulting doc) where needed

2021-11-22 15:40 UTC, Pavinati commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    @desc "A string to match against the part number of the device's appliance model. The match is case-insensitive and tests whether the string is included in the part number of the device's applian
That's a good point.
In this case, I personally vouch for heredocs.
I think documentation in code should be readable without having to scroll horizontally or configuring the editor to wrap long lines.

2021-11-22 16:10 UTC, davidebriani commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    @desc "A string to match against the part number of the device's appliance model. The match is case-insensitive and tests whether the string is included in the part number of the device's applian
Actually using heredocs produces the correct output, adopting the `\` character to break lines.
So for shorter lines we can use `@desc "some desc"` and for the longer ones use:

```elixir
    [...]
    field :device_id, :string

    @desc """
    A string to match against the part number of the device's appliance model.
    
    The match is case-insensitive and tests whether the string is included in \
    the part number of the device's appliance model.
    """
    field :appliance_model_part_number, :string
    
    [...]
```

This way the leading whitespace is stripped from each, based on the trailing space of the last line
```
    """
```
and lines broken by `\` will produce a single line without line-breaks.

2021-11-24 12:57 UTC, bettio requested changes

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  Denotes the type of appliance that a device's hardware can be plugged to.
`plugged into` maybe?

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +    @desc "The reference name of the appliance model."
`The identifier` maybe?

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +    @desc "The reference name of the hardware type."
`The identifier` maybe?

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +        The reference name of the hardware type.
`The identifier` maybe?

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +        The reference name of the hardware type.
`The identifier` maybe?

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +        The reference name of the appliance model.
`The identifier` maybe?

2021-11-24 12:57 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +        The reference name of the appliance model.
`The identifier` maybe?

2021-11-25 15:26 UTC, bettio requested changes

2021-11-25 15:26 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  It refers to the physical components embedded in a device's board.
I would change to "It refers to the physical components embedded in an appliance."

2021-11-25 15:26 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  It refers to the physical components embedded in a device's board.
@rbino any comment here?

2021-11-25 15:26 UTC, bettio commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  Denotes the type of appliance that a device's hardware can be plugged into.
I was thinking about this twice, and it sound a bit weird. @rbino any comment here?

2021-11-25 15:39 UTC, rbino requested changes

2021-11-25 15:39 UTC, rbino commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  It refers to the physical components embedded in a device's board.
I'd go with your proposal, maybe adding "This can represent, e.g., multiple revisions of a PCB (each with a different part number) which are functionally equivalent from the appliance point of view."

2021-11-25 15:39 UTC, rbino commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  with.
@bettio proposal for replacement of the highlighted lines:

Represents a specific appliance model. An appliance model corresponds to what the users thinks as functionally equivalent appliances (e.g. two revisions of an appliance containing two different embedded chips but that have the same enclosure and the same functionality).

2021-11-25 15:39 UTC, rbino commented on backend/lib/edgehog_web/schema/appliances_types.ex
> +  Denotes the type of appliance that a device's hardware can be plugged into.
See other comment

2021-11-25 17:38 UTC, bettio approved these changes

2021-11-25 17:39 UTC, merged