Edgehog containers
edgehog-device-manager/edgehog pull request #607
Opened 2024-10-04 13:28 UTC by lusergit

Added the `Container` domain with the `ImageCredentials` resource. The resource has the attributes decribed with issue #606 and the domain exposes the required operations. All operations are tested with Absinthe.

2024-10-07 13:37 UTC, rbino requested changes

2024-10-07 13:37 UTC, rbino commented on backend/lib/edgehog_web/schema.ex
> +      Edgehog.Containers
Nit: let's maintain alphabetical order

2024-10-07 13:37 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +# Copyright 2021-2024 SECO Mind Srl
New files should have only `2024`

2024-10-07 13:37 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +    identity :name_tenant_id, :name
The `_tenant_id` suffix format has been superseded by #608, it was used just to be consistent with existing indexes.
It should be `identity :name, :name` (does the second parameter also accepts a single atom instead of a list of atoms? TIL)

2024-10-07 13:37 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +    repo(Edgehog.Repo)
Extra parentheses, they shouldn't be there

2024-10-07 13:37 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +    identity :name_tenant_id, :name
Note that I think you have to run again the generator after you change this. Don't do two different migrations for the rename, just recreate the migration from scratch. You have to throw away both the generated migration _and_ its relative resource snapshot JSON to do so.

2024-10-07 13:37 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +      sensitive? true
`allow_nil? false` here too I guess, unless there's some usecase where you want to authenticate with a registry just with a username (I don't think there is)

2024-10-07 13:37 UTC, rbino commented on backend/test/edgehog_web/schema/query/image_credentials_test.exs
> +  require IEx
Leftover

2024-10-07 13:37 UTC, rbino commented on backend/test/edgehog_web/schema/query/image_credentials_test.exs
> +# Copyright 2021-2024 SECO Mind Srl
Year

2024-10-07 13:37 UTC, rbino commented on backend/test/edgehog_web/schema/query/image_credentials_test.exs
> +defmodule EdgehogWeb.Schema.Query.ImageCredentialsTest do
We usually do one-file-per-query so split into `ImageCredentialsTest` and `ListImageCredentialsTest`

2024-10-07 13:37 UTC, rbino commented on backend/config/config.exs
> +  Edgehog.Containers,
See other comment, let's keep these in alphabetical order

2024-10-08 10:19 UTC, rbino approved these changes

2024-10-10 13:25 UTC, noaccOS commented on backend/lib/edgehog/containers/containers.ex
> +# Copyright 2021-2024 SECO Mind Srl
```suggestion
# Copyright 2024 SECO Mind Srl
```

2024-10-10 13:50 UTC, noaccOS commented on backend/lib/edgehog/containers/image_credentials.ex
> +    repo Edgehog.Repo
```suggestion
```

I believe the repo is already defined in [`Edgehog.MultitenantResource`](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/lib/edgehog/multitenant_resource.ex#L50)

2024-10-10 14:10 UTC, noaccOS commented on backend/lib/edgehog/containers/containers.ex
> +  end
In general, how do we want to approach image credentials? 
imo we should use the same guidelines as the images:

> `Let's not add any GraphQL queries for now and just add them as we go to satisfy the frontend needs.`

How about we split this PR in two: one for the resources, one draft pr for the graphql mutations?

2024-10-10 14:55 UTC, noaccOS commented on backend/lib/edgehog/containers/image_credentials.ex
> +    end
```suggestion
    create :create do
      primary? true
      accept [:name, :username, :password]
    end
```

how about we mark this as primary?

2024-10-11 07:47 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +    repo Edgehog.Repo
Indeed it is, but I think this is the status quo for basically all existing resource. Let's keep it consistent for now and decide later if want to remove it from the MultitenantResource or from the single resources in a separate PR.

2024-10-11 07:49 UTC, rbino commented on backend/lib/edgehog/containers/containers.ex
> +  end
Here it makes sense to have GraphQL functionalities from the get-go (as requested in #606) because in the initial flow that was sketched credentials are added in an explicit separate step (while, e.g., Images, currently are not). I'd keep the GraphQL mutations/queries, we can always change them later if there are different requirements from the frontend.

2024-10-11 12:57 UTC, merged