feat: azure support
edgehog-device-manager/edgehog pull request #613
Opened 2024-10-09 16:40 UTC by noaccOS

add azure support by adding a waffle compatible storage module based on azurex.

the configuration mostly maps to existing s3 configuration, so for now I did not deem it necessary to separate the configuration. I am however open to implementing a separate configuration if this was preferred though.

Two new environment variables were added for configuration:
- STORAGE_TYPE, which can be either s3 or azure
- AZURE_API_URL, because it needs more flexibility than just scheme, host and port.

also add integration tests and allow runtime configuration of s3 storage

2024-10-11 12:56 UTC, rbino requested changes
Not urgent, but before merging this needs:
- Changelog entry
- Documentation about how to use Azure Blob Storage in the "Deploying with Kubernetes" page

2024-12-05 14:48 UTC, lusergit approved these changes

2024-12-09 11:54 UTC, davidebriani requested changes

2024-12-09 11:54 UTC, davidebriani commented on backend/lib/edgehog/base_images/bucket_storage.ex
> +
This was broken from previous releases.
It would be nice to have this fix in v0.9 and forward-port it to main.

2024-12-09 13:24 UTC, noaccOS commented on backend/lib/edgehog/base_images/bucket_storage.ex
> +
Done in #764

2024-12-19 12:03 UTC, davidebriani requested changes
Brilliant PR!
If we manage to use a more informative changelog line, it's a merge

2024-12-19 14:21 UTC, davidebriani approved these changes

2024-12-19 14:21 UTC, merged