feat(containers): add support fot available deployments interface
edgehog-device-manager/edgehog pull request #638
Opened 2024-10-15 13:28 UTC by lusergit

Closes #625. Implements the astarte interface
`io.edgehog.devicemanager.apps.AvailableDeployments` between a device and edgehog

2024-10-15 14:02 UTC, rbino requested changes

2024-10-15 14:02 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    @desc "The delpoyment status, can be :idle, :starting, :started, :stopping, :stopped or :error"
Typo: deployment

2024-10-15 14:02 UTC, rbino commented on backend/lib/edgehog/devices/device/calculations/astarte_interface_value.ex
> +  defp value_id_to_fetch_fun(:available_deployments), do: &@available_deployments.get/2
Nit: keep alphabetical order

2024-10-17 08:22 UTC, shinnokdisengir commented on backend/lib/edgehog/astarte/device/available_deployments.ex
> +      case parameters["status"] do
Wouldn't it be better to create a static map at the module level?
```elixir
@map_status %{
    "Idle" => :idle
  }
  ```

2024-10-17 10:19 UTC, rbino commented on backend/lib/edgehog/astarte/device/available_deployments.ex
> +      case parameters["status"] do
Recently Elixir docs have been updated to [discourage the usage of module attributes as constants](https://hexdocs.pm/elixir/module-attributes.html#as-compile-time-constants)

A case/map inside the function also makes information more local, which helps with not having to jump around

2024-10-17 10:20 UTC, rbino approved these changes

2024-10-17 10:20 UTC, merged