Display StorageStats for devices
edgehog-device-manager/edgehog pull request #64
Opened 2021-11-22 14:27 UTC by davidebriani

Fetch StorageStats from AppEngine and display the info in a tab on the Device page.

![Screenshot 2021-11-22 at 13-14-52 Edgehog](https://user-images.githubusercontent.com/60540759/142878698-8f716477-3c83-4288-aded-41c63ea21e71.png)

2021-11-22 15:25 UTC, rbino requested changes

2021-11-24 11:58 UTC, bettio approved these changes

2021-11-24 14:01 UTC, rbino commented on backend/lib/edgehog/astarte/device/storage.ex
> +  ]
Following the changes in the GraphQL API, we could put the struct in a separate module here too (i.e. `Storage.get` returns a list of `Storage.StorageUnit`)

2021-11-24 14:03 UTC, rbino commented on backend/lib/edgehog/astarte/device/hardware_info.ex
> +    # TODO: right now we request the whole interface at once, so `memory_total_bytes` can't
You should copy this TODO also in the `Storage.get` function

2021-11-24 14:09 UTC, rbino commented on backend/lib/edgehog/astarte/device/storage.ex
> +        data["storage"]
This will crash if the interface is empty (so there's no `storage` key in `data`), since you will call `Enum.map(nil, fun)`.
You have to decide what you want to return in case of an empty interface.
- If you want to return an empty list, then you can do
```elixir
Map.get(data, "storage", %{})
|> Enum.map(...)
```
- If you want to return `{:ok, nil}`, you will probably get away with an `if`.
Imho the first approach makes sense (and it's the behaviour you're declaring in the typespec), but if that's the case then the GraphQL type wille become `non_null(list_of(non_null(:storage_unit)))` because you're effectively always returning a (possibly empty) list

2021-11-24 18:25 UTC, davidebriani commented on backend/lib/edgehog/astarte/device/storage.ex
> +        data["storage"]
I went with `Enum.map(data, ...)` so it should avoid the `nil` case since `data` should not be empty.
This way we get:
- an empty list when the device supports the interface but has no storage units
- `nil` if the device does not support the interface, which will result in the frontend not showing the Storage tab

2021-11-26 11:45 UTC, bettio approved these changes

2021-11-30 09:33 UTC, rbino approved these changes

2021-11-30 09:34 UTC, merged