feat(contianers): implemented create image request interface
edgehog-device-manager/edgehog pull request #640
Opened 2024-10-16 13:05 UTC by lusergit

Closes #630

- Implemented the `create_image` behaviour
- Implemented the `base64_json` calculation in the `image_credentials` resource
- Implemented the manual action `send_create_image_request` in the `device` resource. This is inteded to be internally called with an `Image` and an optional `ImageCredentials` struct to send the appropriate astarte call to the device.

2024-10-17 08:44 UTC, shinnokdisengir commented on backend/lib/edgehog/devices/device/manual_actions/send_create_image_request.ex
> +    credentials =
no check is done on `credentials` (e.g. that it is %{el1, el2}). In the case wouldn't it be better to put it inside the `with`?

2024-10-17 10:32 UTC, lusergit commented on backend/lib/edgehog/devices/device/manual_actions/send_create_image_request.ex
> +    credentials =
Yess now the code checks for correct credentials calculation thanks 👍🏻

2024-10-17 13:24 UTC, noaccOS commented on backend/lib/edgehog/containers/image_credentials/base64_json_encoding.ex
> +  def calculate(records, _opts, _context) do
Let's use `@impl` to mark this function as part of `Ash.Resource.Calculation`

2024-10-17 13:24 UTC, noaccOS commented on backend/lib/edgehog/containers/image_credentials/base64_json_encoding.ex
> +    end)
Just like in #645, we're dealing with structs so we already know their attributes.
nit/tip: pipelines are your friend
nit/tip 2: sometimes the code is (arguably) clearer using for comprehensions

```suggestion
    for record <- records do
      %{username: record.username, password: record.password}
      |>  JSON.encode()
      |> Base.encode64()
    end
```

2024-10-17 15:12 UTC, noaccOS commented on backend/lib/edgehog/devices/device/device.ex
> +        allow_nil?: true
let's use the do notation as that's what's being used in the codebase when there is more than one option

2024-10-18 08:43 UTC, rbino requested changes

2024-10-18 08:43 UTC, rbino commented on backend/lib/edgehog/containers/image_credentials.ex
> +    calculate :base64_json, :string, {Base64JsonEncoding}
No need for tuple (not sure it even works to be quite frank). Should be either [`module` or `{module, args}`](https://hexdocs.pm/ash/dsl-ash-resource.html#calculations-calculate-calculation) (or possibly `expr(...)`)

2024-10-18 10:06 UTC, rbino approved these changes

2024-10-18 10:06 UTC, merged