Feature/create container request
edgehog-device-manager/edgehog pull request #646
Opened 2024-10-17 13:59 UTC by lusergit

Depends on #645 ,
closes #628

2024-10-18 09:39 UTC, rbino requested changes

2024-10-18 09:39 UTC, rbino commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +      hostname: container.hostname,
Is this (and all other fields) guaranteed to be non-nil? Otherwise I think we have to default to empty string at some level (e.g. `container.hostname || ""`) because IIRC the Rust SDK is not happy if an object aggregation sends a null field (cc @joshuachp for confirmation)

2024-10-18 10:10 UTC, joshuachp commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +      hostname: container.hostname,
Yes, it was agreed that we will never receive incomplete object aggregates from Astarte.

2024-10-18 10:17 UTC, lusergit commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +      hostname: container.hostname,
Makes sense, I think is best to place the constraints in the resource with `allow_nil? false` and `constraints [allow_empty?: true]`

2024-10-18 16:02 UTC, rbino requested changes

2024-10-18 16:02 UTC, rbino commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +  defp to_correct_string(:on_failure), do: "unless-stopped"
Typo I guess.

Also, I'd probably handle this either replacing `_` with `-` or using something like [Recase](https://github.com/wemake-services/recase) (probably the former, given you know that you always have a snake case atom as input)

The reasoning is that if you add a new multi-word restart policy you'd have to change the code in two different places with the current solution

2024-10-21 11:56 UTC, noaccOS commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +      data = %{
```suggestion
      data = %RequestData{
```

I think dyalizer wouldn't like this as it is. Let's give it "proper" typing

2024-10-21 13:21 UTC, lusergit commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +      data = %{
The `send_datastream` function accepts a map as input, not a `RequestData` instance. For simplicity I intially just wrote a map but proer typing is better I agree

2024-10-21 13:36 UTC, noaccOS commented on backend/lib/edgehog/devices/device/manual_actions/send_create_container.ex
> +      data = %{
It works, but it breaks the contract: [`9f02250` (#646)](https://github.com/edgehog-device-manager/edgehog/pull/646/commits/9f02250a6df6a69c2a9ac62d7624ba485dfc78e8#diff-b705cafe3b60fe47455496a41accaa2ac6316f9c2ac96d2ddd0dd70fb6b94db7R29)

2024-10-21 14:01 UTC, noaccOS commented on backend/lib/edgehog/astarte/device/create_container_request.ex
> +    request_data_map = Map.from_struct(request_data)
Is this needed?

2024-10-22 09:31 UTC, rbino commented on backend/lib/edgehog/astarte/device/create_container_request.ex
> +    request_data_map = Map.from_struct(request_data)
Probably yes since `send_datastream` expects a map

2024-10-22 09:32 UTC, merged