feat(containers): application upgrade interface
edgehog-device-manager/edgehog pull request #654
Opened 2024-10-21 09:01 UTC by noaccOS

expose a way to upgrade an application to a newer release.

- does not allow downgrading
- the releases must be of the same application

depends on #653 and is drafted because the last commit (which must be removed before merging) depends on it
closes #619

2024-10-21 10:19 UTC, lusergit commented on backend/lib/edgehog/devices/device/manual_actions/send_application_command.ex
> +      end
maybe nit: Wouldn't it be better to move this behaviour (specifically the error handling in the `case do ... end`) in the `Edgehog.Astarte.Device.DeploymentCommand` (and do the same for all those kinds of modules?) this way we can handle this as
```elixir
with :ok <- @deployment_command.send_deployment_command(...) do
  {:ok, device}
end
```
while still ensuring that the error is correctly handled by `send_deployment_command` itself
```elixir
@impl Edgehog.Astarte.Device.DeploymentCommand.Behaviour
  def send_deployment_command(client, device_id, deployment_id, command) do
    path = "/#{deployment_id}/command"
    case AppEngine.Devices.send_datastream(client, device_id, @interface, path, command) do
      {:error, api_error} -> ...
      :ok -> :ok
  end
```

2024-10-21 10:19 UTC, lusergit commented on backend/lib/edgehog/astarte/device/deployment_update.ex
> +    AppEngine.Devices.send_datastream(client, device_id, @interface, "/release", data)
Maybe we should be consistent with this kind of modules; choosing whether we make these calls with the whole `request_data` (see #646 [`create_container_request` request data](https://github.com/edgehog-device-manager/edgehog/pull/646/files#diff-2b04344ec44f5192aab41c44036af5f1407b9fea3c58315f3a621cf0b2ea8558) ) or if we want to pass the individual fields

2024-10-21 11:58 UTC, noaccOS commented on backend/lib/edgehog/devices/device/manual_actions/send_application_command.ex
> +      end
I did it this way because that how it was done elsewhere and I didn't give it much thought, but yeah I also think doing it at the API level makes more sense (I'm actually unsure why the astarte client doesn't do that by default)

2024-10-21 12:03 UTC, noaccOS commented on backend/lib/edgehog/astarte/device/deployment_update.ex
> +    AppEngine.Devices.send_datastream(client, device_id, @interface, "/release", data)
Passing individual fields every time quickly becomes unmaintainable (you don't really want to have functions with 7 parameters)
I agree, it's probably best to have a consistent interface between the api calls though, I'll add a structure for this interface

2024-10-30 16:06 UTC, lusergit approved these changes

2024-11-07 11:20 UTC, lusergit requested changes

2024-11-07 11:20 UTC, lusergit commented on backend/lib/edgehog/astarte/device/deployment_update.ex
> +    api_call = AppEngine.Devices.send_datastream(client, device_id, @interface, "/release", data)
The interface changed: it now needs to be called on the `/deployment` endpoint (see [interfaces PR](https://github.com//pull/64/files#diff-0482701a7ded078199e43f0fcfc2291ca0b384dc5be49ac52969a3d3938e1e17))
```suggestion
    api_call = AppEngine.Devices.send_datastream(client, device_id, @interface, "/deployment", data)
```

2024-11-07 11:20 UTC, lusergit commented on backend/lib/edgehog/astarte/device/deployment_update/request_data.ex
> +          to: Deployment.t()
I think we want to send ids and not structs
```suggestion
          from: String.t(),
          to: String.t()
```

2024-11-07 11:20 UTC, lusergit commented on backend/lib/edgehog/devices/device/manual_actions/update_application.ex
> +    with {:ok, from} <- fetch_deployment(device, from),
I think here is better to stuck with `Ash` intended behaviour and fetch arguments trough `Ash.Changeset` functions
```suggestion
    device = changeset.data

    with {:ok, from} <- Ash.Changeset.fetch_argument(changeset, :from),
         {:ok, to} <- Ash.Changeset.fetch_argument(changeset, :to),
         {:ok, from} <- fetch_deployment(device, from),
```

2024-11-07 11:20 UTC, lusergit commented on backend/lib/edgehog/devices/device/manual_actions/update_application.ex
> +         data = %RequestData{from: from, to: to},
Related to previous comment we should send ids to the device according to the interface, therefore here we have to extract them
```suggestion
         data = %RequestData{from: from.id, to: to.id},
```

2024-11-07 11:20 UTC, lusergit commented on backend/priv/astarte_resources/interfaces/io.edgehog.devicemanager.apps.DeploymentUpdate.json
This interface has changes after IRL discussions, see [interfaces PR](https://github.com//pull/64/files#diff-0482701a7ded078199e43f0fcfc2291ca0b384dc5be49ac52969a3d3938e1e17))

2024-11-08 09:50 UTC, lusergit approved these changes

2024-11-08 11:01 UTC, lusergit approved these changes

2024-11-08 11:03 UTC, merged