feat(containers): release deployment mechanism
edgehog-device-manager/edgehog pull request #660
Opened 2024-10-24 12:26 UTC by lusergit

closes #656

The deployment mechanism consists of an `executor.ex` that handles the stages of the deployment, sending the appropriate calls to the device asyncronously. The `Devices` domain now exposes code interfaces for the `Device` resource

2024-10-25 16:01 UTC, rbino requested changes
General comment: in this specific phase I would avoid having to deal with executor processes, waiting for acks and so on.

What I would do is wrap the logic that given a deployment sends all the stuff to Astarte in a generic action. This is similar to what is done [here](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/os_management/ota_operation/ota_operation.ex#L127) with `:send_ota_request`, which given an `OTARequest` database resource sends the appropriate message to Astarte. Of course the implementation of the Deployment would have more moving parts since it needs to send images and containers, but imho for now the idea would be to send everything without worrying about acks, but just short-circuiting (i.e. returning an error) if any request returns an error at any point.

With that, you can create a corresponding change (see the one for the `OTARequest` [here](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/os_management/ota_operation/changes/send_update_request.ex)) that can be called at the end of the `:deploy` action. Note that the change uses `after_action` instead of `after_transaction`, so if any of the requests fails, the whole action returns an error _and_ the `Deployment` is not persisted to the database.

2024-10-28 15:47 UTC, noaccOS commented on backend/lib/edgehog/containers/manual_actions/send_deploy_request.ex
> +      end
I'm not against this approach as a first step but:

The device returns an error if we send it a create image for an image it already has.
This means that this algorithm will fail if the same image is in use by multiple containers

This could be mitigated by using `containers |> Enum.map(& &1.image) |> Enum.uniq`, which might even be alright for now if we also include a comment explaining why.

Of course the real solution is to actually identify the resources we need to send requests for, but that will be done later :tm:

2024-10-29 11:46 UTC, noaccOS approved these changes

2024-10-29 11:50 UTC, rbino requested changes

2024-10-29 11:50 UTC, rbino commented on backend/lib/edgehog/containers/manual_actions/send_deploy_request.ex
> +      Devices.send_create_deployment_request(device, deployment)
From my previous long comment:

> [...] but just short-circuiting (i.e. returning an error) if any request returns an error at any point

i.e. even in this phase we can (and should) at least check if there's an error _during the request_ and bubble it up

```elixir
def run(input, _opts, _context) do
  # ...

  with :ok <- send_create_image_requests(device, images),
      :ok <- send_create_container_requests(device, containers) do
    Devices.send_create_deployment_request(device, deployment)
  end
end

defp send_create_image_requests(device, images) do
  # Usually short-circuiting is done using Enum.reduce_while/3, or with manual recursion
  Enum.reduce_while(images, :ok, fn image, _acc ->
    case Devices.send_create_image_request(device, image) do
      :ok -> {:cont, :ok}
      {:error, reason} -> {:halt, {:error, reason}}
    end
  end)
end

# Same for send_create_container_requests
```

2024-10-29 17:08 UTC, lusergit commented
The happy path now works with astarte 1.2.0 (locally tested). I've added the necessary fixes to make it work to this PR as the changes are needed in order to implement the release deployment mechanism feature

2024-10-30 15:20 UTC, noaccOS commented
please fixup 06015e0 onto 6e6ac3a

2024-10-30 15:30 UTC, noaccOS approved these changes

2024-10-30 15:34 UTC, noaccOS commented
I'll merge this as the error propagation was addressed. The code can still be modified with a followup pr in case.

2024-10-30 15:34 UTC, merged