Display system status for devices
edgehog-device-manager/edgehog pull request #70
Opened 2021-11-29 12:16 UTC by davidebriani

Fetch SystemStatus data from AppEngine and display the info in a tab on the Device page

![Screenshot 2021-11-29 at 13-14-55 Edgehog](https://user-images.githubusercontent.com/60540759/143866589-847643b0-6a53-4890-a7ff-dbd2554d54f4.png)
.

2021-11-30 16:55 UTC, rbino requested changes

2021-11-30 16:55 UTC, rbino commented on backend/lib/edgehog_web/resolvers/astarte.ex
> +      {:ok, [system_status | _tail]} -> {:ok, system_status}
I'd move the list unpacking in `fetch_system_status/1`. The fact that you obtain a list of SystemStatus is an implementation detail imho, and we're only interested in the last one right now.

2021-11-30 16:55 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :timestamp, non_null(:datetime)
Why only this is `non_null`? Since it's an object aggregation I expect that either we have all fields or none (so the `non_null` would be one layer above)

2021-11-30 17:28 UTC, davidebriani commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :timestamp, non_null(:datetime)
Last time I checked I could send object aggregated with null values. So I'd take that into account. The `timestamp` however will be present for sure.

2021-12-01 10:23 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :timestamp, non_null(:datetime)
Makes sense

2021-12-01 12:05 UTC, Pavinati commented on frontend/src/pages/Device.tsx
> +            <FormRow
we have loads of form rows that are all the same.
I think we can create an array of objects and map over them
```
[
  {
    value: hardwareInfo.cpuArchitecture,
    type: "text",
    label: <FormattedMessage id="Device.hardwareInfo.cpuArchitecture" defaultMessage="CPU architecture" />
  },
  {
    value: hardwareInfo.cpuModel,
    type: "text",
    label: <FormattedMessage id="Device.hardwareInfo.cpuModel" defaultMessage="CPU model code" />
  },
].map(ReadOnlyValue)
```
```
const ReadOnlyValue = ({ value, type, label }) => {
  if (!value) {
    return null;
  }

  if (type === "numeric") {
    [...]
  }
  // text
  [...]
}
```

2021-12-02 10:11 UTC, rbino approved these changes

2021-12-02 10:11 UTC, merged