Device battery status [backend]
edgehog-device-manager/edgehog pull request #71
Opened 2021-11-29 14:35 UTC by szakhlypa

Fetch BatteryStatus data from AppEngine and expose it via GraphQL

2021-11-29 15:03 UTC, davidebriani requested changes

2021-11-29 15:03 UTC, davidebriani commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :status, non_null(:string)
It's better to wrap lines at 80 characters to improve readability.
You can write the @desc using heredocs notations, such as:
```elixir
    @desc """
    The current status of the battery.
    
    It can be any of: Charging, Discharging, Idle, EitherIdleOrCharging, \
    Failure, Removed, Unknown.
    """
```

Using heredocs produces the correct output, adopting the \ character to break lines.
So for shorter lines we can use @desc "some desc" and for the longer ones use the multiline @desc.
This way the leading whitespace is stripped from each line, based on the trailing space of the last line
```elixir
    """
```
and lines broken by `\` will produce a single line without line-breaks.

2021-11-29 15:03 UTC, davidebriani commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    @desc "The list of battery slots with status of the device."
Maybe just `@desc "The status of the battery slots of the device."`

2021-11-29 15:41 UTC, davidebriani approved these changes

2021-11-30 11:44 UTC, rbino requested changes
@szakhlypa the PR is good, I just suggested an improvement that fits nicely here. Also please rebase it on main since it's conflicting now that I merged device status PR.

2021-11-30 11:44 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :status, non_null(:string)
Let's go the extra mile here and expose the battery status as a GraphQL enum.
Here's a sketch of what needs to be done

In `AstarteTypes`:
```elixir
  enum :battery_status do
    value :charging
    value :discharging
    ...
  end
```
(note: use `snake_case` for GraphQL enum values)
and
```
   field :status, non_null(:battery_status) do
     resolve &Resolvers.Astarte.battery_status_to_enum/2
   end
```

In `Resolvers.Astarte`:
```elixir
  def battery_status_to_enum(status, _context) do
    case status do
      "Charging" -> {:ok, :charging}
      "Discharging" -> {:ok, :discharging}
      ...
      _other -> {:error, :invalid_battery_status}
    end
  end
```

2021-12-02 16:20 UTC, rbino requested changes

2021-12-03 09:17 UTC, rbino requested changes

2021-12-03 09:17 UTC, rbino commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    value :unknown, description: "The battery status cannot be determined."
Let's be consistent with everything else:
```
@desc "The battery is charging"
value :charging
...
```

2021-12-03 11:01 UTC, rbino approved these changes

2021-12-03 11:01 UTC, merged