Handle optional configuration for geolocation providers
edgehog-device-manager/edgehog pull request #72
Opened 2021-11-30 18:25 UTC by davidebriani

Use an optional and general config to define geolocation/geocoding providers.
- The list of providers to use is directly defined via Config
- Providers are enabled only if properly configured via environment variables, otherwise they are not used.
- a Device instance is given directly to Geolocation providers and they are free to implement the logic to fetch device's info and compute its location

2022-02-08 09:45 UTC, rbino requested changes

2022-02-08 09:45 UTC, rbino commented on backend/config/runtime.exs
> +    }
Why do you provide the config as a map just to convert it to a Keyword list in `Enum.each`? Just use a Keyword list here directly

2022-02-08 09:45 UTC, rbino commented on backend/lib/edgehog/geolocation/geolocation_provider.ex
>          }
We should probably convert this to a struct since this is returned by a behaviour (and a struct gives you stronger guarantees when you build it about not using the wrong key names etc).
Something like `Edgehog.Geolocation.Position`

2022-02-08 09:45 UTC, rbino commented on backend/lib/edgehog/geolocation/providers/google_geolocation.ex
> +        end
When dealing with booleans just use an `if`
```elixir
if Enum.empty?(...) do
...
else
...
end
```

2022-02-08 17:59 UTC, davidebriani commented on backend/lib/edgehog/geolocation/providers/google_geolocation.ex
> +        &(DateTime.diff(latest_scan.timestamp, &1.timestamp, :second) < 1)
`latest_scan.timestamp` is the latest timestamp of the list, since we already computed the max a few lines before.
Therefore, the diff cannot be negative.

2022-02-08 18:04 UTC, Pavinati approved these changes

2022-02-10 17:49 UTC, bettio approved these changes

2022-02-10 17:49 UTC, merged