chore(containers): update status
edgehog-device-manager/edgehog pull request #724
Opened 2024-11-18 11:40 UTC by lusergit

Deployment status update at each container interface trigger, status interface richer, expresses new deployment statuses:
- `:created` when the backend has recived the deployment description
- `:sent` when the deployment description has been sent to the device
- `:puled_images` when the device has created all the image resources
- `:created_networks` when the device has set up all the network resources
- `:created_containers` when the device has created all the container resources
- `:created_deployment` when the device has set up the deployment resource
- `:ready` when all resources have been created and the deployment is ready to be started

2024-11-18 15:50 UTC, noaccOS requested changes

2024-11-18 15:50 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +        :ok
the case where we don't know the path should be an error. see https://github.com/edgehog-device-manager/edgehog/pull/696#discussion_r1840131511

2024-11-18 15:50 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +            |> Enum.uniq()
Even if something errors out, I'd say we want to update the status of the containers we were able to gather. And possibly logging the error:

```suggestion
          releases =
            containers
            |> Enum.map(&Containers.releases_with_container(&1.id, tenant: tenant))
            |> Enum.flat_map(fn
              {:ok, releases} -> releases
              {:error, reason} -> 
                Logger.error("Error reading releases from containers: #{inspect(reason)}")
                []
            end)
            |> Enum.uniq()
```

2024-11-18 15:50 UTC, noaccOS commented on backend/lib/edgehog/containers/manual_actions/update_status.ex
> +    Ash.update(changeset)
I don't like the current approach: reading these lines, it only looks like you're checking the images.
I would rather see all actions explicitly top level:

```suggestion
    changeset
    |> check_images(context)
    |> check_networks(context)
    |> check_containers(context)
    |> check_deployments(context)
    |> Ash.update()
```

Being changesets, it's easy to apply the next action only if the one before has succeeded. I see two possible ways to approach this:
- by using `Ash.Changeset.fetch_argument_or_change` to get the current status of the changeset (which could have been updated by previous actions), and only going forward with the check if the status is the expected status
- adding an error to the changeset in case not all resources are available. this allows removing all intermediate states (pulling_images, creating_networks, ...) if we want to go in that direction, but changes the semantic meaning of a failed `UpdateStatus.update`

2024-11-18 15:50 UTC, noaccOS commented on backend/lib/edgehog/containers/manual_actions/update_status.ex
> +      end
1. As a rule of thumb, do not do double negations (`reject` and `not in`)
2. Reason being, I think you only need one negation here (you want to take (ie `filter`) all images `not in` pulled images)

```elixir
iex(1)> images = [1,2,3,4,5]
[1, 2, 3, 4, 5]
iex(2)> pulled = [2,4,1]
[2, 4, 1]
iex(3)> images |> Enum.reject(& &1 not in pulled)
[1, 2, 4]
```

3. Bonus, but you're treating lists like sets: you can use sets
```suggestion
      deployment_images = deployment.release.containers |> Enum.map(& &1.image.id) |> MapSet.new()

      available_images =
        deployment.device
        |> Devices.available_images(tenant: tenant)
        |> Enum.filter(& &1.pulled)
        |> Enum.map(& &1.id)
        |> MapSet.new()
        
      all_images_available? = MapSet.subset?(deployment_images, available_images)

      if all_images_available? do
        changeset
      else
        check_networks(changeset, context)
      end
```

2024-11-18 15:50 UTC, noaccOS commented on backend/lib/edgehog/containers/types/deployment_status.ex
> +      creating_deployment: "The device is setting up the release of the the deployment.",
I personally don't like the idea of exposing these states because they're internal states and don't necessarily reflect the status for the device (a device could already have all containers created but still missing some images)

also, the device only pulls images once we actually start the deployment, so that would be "creating_images"

still, we plan to change the implementation for good once we have time to do so, so if you need these intermediary states I'm not _that_ against them

2024-11-20 08:53 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +        |> Ash.update!()
I believe you can just

```suggestion
        [tenant: tenant, device_id: device.id, release_id: release.id, status: :sent]
        |> deployment_fixture()
```

2024-11-20 09:05 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +
As this was heavily modified in the following commit, could this be squashed inside it?
TBF tests could go into the same commit as the change, so that could also be an option

2024-11-20 09:43 UTC, lusergit commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +
Yes, will do it :+1:

2024-11-20 09:51 UTC, lusergit commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +        |> Ash.update!()
Actually no since the deployment creation does not allow to set the initial status. I think this is the inteded behaviour since the status is an internal rapresentation that depends on the communication with the device. I'll keep it like this for now insted of creating a new `create` action for the deployment just for this test

2024-11-20 10:51 UTC, noaccOS commented on backend/lib/edgehog/containers/deployment.ex
> +      change set_attribute(:status, :created)
how about we instead set the default value to `:created` and disallow `nil`?

2024-11-20 11:31 UTC, lusergit commented on backend/lib/edgehog/containers/deployment.ex
> +      change set_attribute(:status, :created)
I was thinking the same thing :+1:

2024-11-20 16:56 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +            Containers.deployment_update_satus(deployment)
This change should be applied to available deployments (probably also only on status: stopped but whatever)
Deployment events can only happen after we have sent a start, or if the device encountered an error during creation

In both circumstances, we want to set the state it's given us

Also, just noticed: `update_satus`

2024-11-25 10:00 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +               Enum.reduce_while(containers, {:ok, []}, &releases_from_container(&1, &2, tenant)),
https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1846780287

2024-11-25 10:01 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +             {:ok, relations} <- Ash.load(relations, [:container]),
https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1850362629

2024-11-25 10:01 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +             {:ok, relations} <- Ash.load(relations, :release),
https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1850362629

2024-11-25 10:02 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +               Enum.reduce_while(releases, {:ok, []}, &deployments_from_release(&1, &2, tenant)) do
https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1846780287

2024-11-25 10:02 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status(&1))}
Just a bit clearer

```suggestion
          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
```

2024-11-25 10:03 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +               Enum.reduce_while(releases, {:ok, []}, &deployments_from_release(&1, &2, tenant)) do
https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1846780287

2024-11-25 10:03 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status(&1))}
/1

2024-11-25 10:03 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +               Enum.reduce_while(releases, {:ok, []}, &deployments_from_release(&1, &2, tenant)) do
https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1846780287

2024-11-25 10:03 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status(&1))}
/1

2024-11-25 10:06 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +
available deployments does not have a message. only deployment event does

2024-11-25 10:10 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
>  end
as a rule of thumb if your function is not an abstraction, it should probably not be a function
of course this helps when your function grows too much, but it's usually better to look for other methods of refactoring.

just a small tip, I expect these functions to be reworked anyways as we don't really care about short circuiting in this instance. That is more important when we don't want to send excessive messages to astarte

2024-11-25 10:12 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +      end)
see if you can reuse this https://github.com/edgehog-device-manager/edgehog/pull/731/files#diff-20bdec863086b49e111b95ffa702843a39d08f2fbc2f1812c8ae5a1ab09da4b5R177

2024-11-25 10:12 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +
see if you can reuse this https://github.com/edgehog-device-manager/edgehog/pull/731/files#diff-20bdec863086b49e111b95ffa702843a39d08f2fbc2f1812c8ae5a1ab09da4b5R177

2024-11-25 10:13 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +
see if you can reuse this https://github.com/edgehog-device-manager/edgehog/pull/731/files#diff-20bdec863086b49e111b95ffa702843a39d08f2fbc2f1812c8ae5a1ab09da4b5R177

2024-11-25 10:51 UTC, lusergit commented on backend/lib/edgehog/devices/devices.ex
> +      define_calculation :available_images, args: [:_record]
Specifies the resource to use to perform the calculation. Without it the signature of the interface becomes `Devices.available_images/1` with only the optional `opts` parameter. I think that in that case the calculation is performed on all the resources that respect the query (which could be either all devices or no device, I have not checked but either way is not the desired behavior)

2024-11-25 10:53 UTC, lusergit commented on backend/lib/edgehog/devices/devices.ex
> +      define_calculation :available_images, args: [:_record]
This has to be done on all the other `available_*` code interfaces too

2024-11-25 11:00 UTC, lusergit commented on backend/lib/edgehog/containers/manual_actions/send_deploy_request.ex
> +        Containers.deployment_set_status(deployment, :sent, nil, tenant: tenant)
I thought that too but thats not the case as `:set_status` action accepts both arguments, hence they are marked as required by default, we can put `{:optional, :message}` in the code action, but since sometimes we need to set the message, and some times the status itself I thought was a better idea to keep the interface and tweak the arguments as needed

2024-11-25 11:01 UTC, lusergit commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +
right I got confused, almost hit myself

2024-11-25 11:02 UTC, lusergit commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +
leaving the `deployment.message` because of [prior comment](https://github.com/edgehog-device-manager/edgehog/pull/724#discussion_r1856395142)

2024-11-25 11:06 UTC, lusergit commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
>  end
I initially introduced these as the linter was complaining of eccessive nesting, I can them and duplicate code if needed

2024-11-25 14:07 UTC, noaccOS requested changes
we're getting closer!
this round is mostly tests and a couple questions

2024-11-25 14:07 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +      assert {:ok, release} = Ash.load(release, containers: [:image, :networks])
You assert something when you want to validate your code is working as expected. You do not want to test external libraries, they have their own tests

```suggestion
      release = release_fixture(containers: 1, tenant: tenant) |> Ash.load!(containers: [:image, :networks])
```

2024-11-25 14:07 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +      {:ok, deployment} = Ash.get(Deployment, deployment.id, tenant: tenant)
don't be afraid of bangs, especially in tests

```suggestion
      deployment = Ash.get!(Deployment, deployment.id, tenant: tenant)
```

2024-11-25 14:07 UTC, noaccOS commented on backend/test/edgehog_web/controllers/astarte_trigger_controller_test.exs
> +      assert response(conn, 200)
`response` already raises if the response does not have the expected exit code

```suggestion
      conn
      |> put_req_header("astarte-realm", realm.name)
      |> post(path, deployment_event)
      |> response(200)
```

2024-11-25 14:21 UTC, lusergit commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
I thought that this way we can also report partial success to the frontend, but maybe the return is a bit unclear this way

2024-11-25 14:23 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
It's only internal database stuff, not "we received invalid data from the device"
Let it crash

```suggestion
          {:ok, Enum.map(deployments, &Containers.deployment_update_status!/1)}
```

2024-11-25 14:56 UTC, lusergit commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
Maybe better: log errors when updating status, but returning `{:ok, deployments}` in any case
```suggestion
        Enum.map(deployments, fn deployment ->
          with {:error, error} <- Containers.deployment_update_status(deployment, tenant: tenant) do
            Logger.error("Error while updating status status of deployment #{deployment.id}: #{inspect(error)}")
          end
        end)

        {:ok, deployments}
```

2024-11-25 15:05 UTC, lusergit commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
I actually think this is ok, the second argument of the  `{:ok, ...}` tuple as return type of the `handle_event` callback is discarded anyway, so for now it does not really matter, this is coincise while doing the right thing (calling the `update_status` on all interested deployments)

2024-11-25 15:18 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
honestly, this is just the callback of a trigger. IMO it is safe to just crash because in normal circumstances, `deployment_update_status` will not fail

if you insist on logging the errors, you could do something like this

```elixir
          {deployments, errors} = 
            deployments
            |> Enum.map(&{&1.id, Containers.deployment_update_status(&1)})
            |> Enum.split_with(&match?({_, {:ok, _}}, &1))
            
          for {deployment_id, {:error, reason}} <- errors do
            Logger.error("Error while updating status status of deployment #{deployment_id}: #{inspect(reason)}")
          end
            
          deployments = deployments |> Enum.map(fn {_, {:ok, deployment}} -> deployment end)
          {:ok, deployments}
```

so that you at least have a separation between program logic and error handling
(yes the double tuple is kind of ugly, this is just an example)

2024-11-25 15:23 UTC, noaccOS commented on backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex
> +          {:ok, Enum.map(deployments, &Containers.deployment_update_status/1)}
> I actually think this is ok, the second argument of the {:ok, ...} tuple as return type of the handle_event callback is discarded anyway

Then I'd argue you make it clear we're only interested in the side effects

```elixir
for deployment <- deployments do
  Containers.deployment_update_status(deployment)
end

{:ok, nil} # or {:ok, deployments} or even :ok (this I don't recommend)
```

2024-11-25 15:40 UTC, noaccOS requested changes
tiny leftovers

2024-11-25 15:40 UTC, noaccOS commented on backend/lib/edgehog/containers/deployment/changes/check_images.ex
> +        |> Enum.reject(&(&1 in pulled_images_ids))
```suggestion
         {:ok, available_images_statuses} <-
           Devices.available_images(deployment.device, tenant: tenant) do
      available_images_ids =
        Enum.map(available_images_statuses, & &1.id)

      missing_images =
        deployment.release.containers
        |> Enum.map(& &1.image.id)
        |> Enum.reject(&(&1 in available_images_ids))
```

2024-11-25 15:55 UTC, noaccOS approved these changes
good job

2024-11-25 15:55 UTC, merged