test(containers): fix deployment start tests
edgehog-device-manager/edgehog pull request #726
Opened 2024-11-18 14:49 UTC by noaccOS

feat(containers): deployment upgrade graphql api

- change the device action to work with deployments instead of releases
- move validations to the graphql api
- add validation for the deployments: they must belong to the same device

currently validations are broken because ash graphql does not work on generic actions: a value of `{:error, term}` becomes an `Ash.Error.Unknown` which is not handled by `AshGraphql.Error`.
The tests pass, it's just that instead of returning nice errors, the request process crashes.

2024-11-18 17:08 UTC, lusergit requested changes
Overall I think the code is very much ready, the only thing I think we would benefit in the mid/long term is to move the validations as they were to keep them first class citizens.

2024-11-18 17:08 UTC, lusergit commented on backend/lib/edgehog/devices/device/device.ex
> -
I think the validation logics should be kept here. If done in this action they are first class citizens. We can keep the logic implemented in `send_deployment_upgrade` but delegate the validations to the update action on the device

2024-11-19 08:20 UTC, noaccOS commented on backend/lib/edgehog/devices/device/device.ex
> -
I like validations where they are now, for a simple reason: ideally, you want to validate data only when receiving data from outside. This way you fail fast and in the rest of the program you can assume your data is valid.
While I agree it would be better to have first class citizen validations, I would argue it's mainly Ash's fault because it does not provide the tools to interact with its own ecosystem to a generic action.

If you really don't like validations as they are now, I propose changing the action to an update:
- We gain the ability to run normal validations on the data, granted we figure out how to pass them the required values (one parameter is the changeset, the other loaded from an argument).
- Our inputs/outputs get messed up. a lot. our api signature becomes `updgradeDeployment(id: ID!, input: %{to: ID})` and return type... one of the two deployments.

2024-11-19 10:35 UTC, noaccOS commented
Repurposed this pr to only  include the fix for the existing test. Will open a draft pr for the deployment upgrade api

2024-11-19 10:47 UTC, lusergit approved these changes

2024-11-19 10:47 UTC, merged