chore(update_channel): better errors
edgehog-device-manager/edgehog pull request #771
Opened 2024-12-10 16:22 UTC by lusergit

When creating and updating an update channel, target group ids are validated to be available, meaning:
- they are present in the DB
- they are not related to any other update channel

closes #529

2024-12-10 16:59 UTC, noaccOS commented on backend/lib/edgehog/update_campaigns/update_channel/changes/relate_target_groups.ex
> +      on_lookup: :relate,
How about using a custom update action instead? IMO the validation is about the group not about the channel

```suggestion
      on_lookup: {:relate, :assign_update_channel},
```

with the related action in `device_group.ex` be something like:

```elixir
update :assign_update_channel do
  accept [:update_channel_id]
  validate attribute_absent(:update_channel_id)
end
```

2024-12-12 09:59 UTC, lusergit commented on backend/lib/edgehog/update_campaigns/update_channel/changes/relate_target_groups.ex
> +      on_lookup: :relate,
I agree, the new commits moved the validation to the device groups instead of the update channels

2025-01-07 10:04 UTC, noaccOS requested changes

2025-01-07 10:45 UTC, noaccOS approved these changes
The copyright for all modified files needs to be updated

Other than that, lgtm

2025-01-07 10:45 UTC, noaccOS commented on backend/test/edgehog_web/schema/mutation/update_update_channel_test.exs
> +      assert name == "\"#{target_group.name}\""
nit: you can use [sigils](https://hexdocs.pm/elixir/sigils.html#strings) to avoid `\"`

```suggestion
      assert name == ~s["#{target_group.name}"]
```

2025-01-08 13:25 UTC, lusergit commented
This depends on ash-project/ash_graphql#257 and ash-project/ash_graphql#253, both have been merged but have yet to be integrated in the next release. When it will be ready we can bump up the ash_graphql and ash version and re open the PR for review.

2025-01-10 16:48 UTC, davidebriani commented
> This depends on [ash-project/ash_graphql#257](https://github.com/ash-project/ash_graphql/pull/257) and [ash-project/ash_graphql#253](https://github.com/ash-project/ash_graphql/pull/253), both have been merged but have yet to be integrated in the next release. When it will be ready we can bump up the ash_graphql and ash version and re open the PR for review.

@lusergit  here it is: https://github.com/ash-project/ash_graphql/releases/tag/v1.5.0

2025-01-13 10:41 UTC, davidebriani approved these changes

2025-01-13 10:41 UTC, merged