doc: add Devices page
edgehog-device-manager/edgehog pull request #92
Opened 2021-12-10 14:49 UTC by davidebriani

Illustrate device pages and displayed device data.

2021-12-10 16:05 UTC, bettio requested changes

2021-12-10 16:05 UTC, bettio commented on doc/pages/user/devices.md
> +Each Device is associated to a specific Appliance, hence a specific Appliance Model. The Appliance
I'm not sure if we want to talk about Astarte interfaces here. I think we should just write that there is some-kind of automatic logic, and leave a link to a more specific page.

2021-12-10 16:05 UTC, bettio commented on doc/pages/user/devices.md
> +estimate a set of GPS coordinates.
maybe we should further discuss how geolocation is estimated.

2021-12-13 11:14 UTC, rbino requested changes

2021-12-13 15:03 UTC, rbino approved these changes

2021-12-13 15:05 UTC, bettio approved these changes

2021-12-13 15:05 UTC, merged