[backend] Device OS info
edgehog-device-manager/edgehog pull request #96
Opened 2021-12-15 10:09 UTC by szakhlypa

Closes #93

2021-12-16 09:09 UTC, szakhlypa commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :os_name, :string
Should we step back from interface naming and expose it as name and version?
os_name -> name
os_version -> version

2021-12-16 10:14 UTC, Pavinati commented on backend/lib/edgehog/astarte/device/os_info.ex
> +defmodule Edgehog.Astarte.Device.OSInfo do
missing license header

2021-12-16 10:27 UTC, szakhlypa commented on backend/lib/edgehog/astarte/device/os_info.ex
> +defmodule Edgehog.Astarte.Device.OSInfo do
Thanks, added headers for OSInfo and HardwareInfo

2021-12-16 10:39 UTC, davidebriani requested changes

2021-12-16 10:39 UTC, davidebriani commented on backend/lib/edgehog/astarte/device/os_info.ex
> +  defstruct @enforce_keys
You are enforcing the presence of the two keys but you have declared them as `nil`lable in the type.
We can opt to keep them nullable, removing `@enforce_keys`:
```
defstruct [:os_name, :os_version]
```

2021-12-16 10:39 UTC, davidebriani commented on backend/lib/edgehog/astarte/device/os_info/behaviour.ex
> +              {:ok, term()} | {:error, term()}
In the return type you can use the correct one instead of `term()`.
```elixir
alias Astarte.Client.AppEngine
alias Edgehog.Astarte.Device.OSInfo

@callback get(client :: AppEngine.t(), device_id :: String.t()) ::
              {:ok, OSInfo.t()} | {:error, term()}
```

2021-12-16 10:39 UTC, davidebriani commented on backend/lib/edgehog_web/schema/astarte_types.ex
> +    field :os_name, :string
Yes I think we could drop the prefix, it is still clear that `name` and `version` refer to the OS.
You could start dropping the prefix since the `parseData` method in the OSInfo module.

2021-12-16 11:10 UTC, davidebriani commented on backend/lib/edgehog/astarte/device/os_info.ex
> +  defstruct @enforce_keys
Sorry, I confused enforcing the presence of the keys with the validation of their values. Your code here is perfectly fine

2021-12-16 11:38 UTC, davidebriani approved these changes

2021-12-17 11:37 UTC, rbino approved these changes

2021-12-17 11:37 UTC, merged